## Summary

The client records downloaded from headquarter patent database contains address info, however, for data analyssi purpose, we need to extract zip code, city, state and country(keep USA only) from the address column. 

To do that, we will import the following 2 files:

- `总部专利客户 as of 2019-08-29.xlsx` 
- `US zip codes.xlsx`

In [1761]:
import pandas as pd
import numpy as np
import re

# import all custom functions from myFunctions.ipynb
from ipynb.fs.full.myFunctions import *

## 1. Loading datasets

### Headquarter client data with address

In [1762]:
HQ_clients = pd.read_excel('../总部专利客户 as of 2019-08-29.xlsx')
print(HQ_clients.index)
print(HQ_clients.info())
HQ_clients.head()

RangeIndex(start=0, stop=3731, step=1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3731 entries, 0 to 3730
Data columns (total 8 columns):
客户代码      3731 non-null object
客户名称      3718 non-null object
客户类别      3731 non-null object
客户地址      3640 non-null object
电话        890 non-null object
传真        784 non-null object
客户中文名称    2690 non-null object
状态        79 non-null object
dtypes: object(8)
memory usage: 233.3+ KB
None

,客户代码,客户名称,客户类别,客户地址,电话,传真,客户中文名称,状态
0,US002562,CERION，LLC,(S),"One Blossom Road, Rochester, NY 14610 USA",NaN,NaN,丝润有限责任公司,NaN
1,US002565,"AD-VANTAGE NETWORKS, INC.",(S),"600 North Brand Blvd., Suite 230 Glendale, CA ...",NaN,NaN,AD-优势网络股份公司,NaN
2,US002566,"TOPS Products, LLC",(S),c/o R.R. Donnelley & Sons Company 111 South Wa...,NaN,NaN,托普斯产品有限责任公司,NaN
3,US002567,"BRIGHENTI, Peter",(S),"430 Carmel Court Canton, Georgia 30114 USA",NaN,NaN,彼得·布里根蒂,NaN
4,US002568,"RANA THERAPEUTICS, INC.",(S),"200 Sidney Street Suite 310 Cambridge, Massac...",NaN,NaN,RANA医疗有限公司,NaN

In [1763]:
''' remove rows without address'''
HQ_clients = HQ_clients.dropna(subset=['客户地址'])
HQ_clients = HQ_clients.reset_index(drop=True).copy() # reset index so position index won't go out of bound
print(HQ_clients.index)
print(HQ_clients.info())
HQ_clients.head()

RangeIndex(start=0, stop=3640, step=1)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3640 entries, 0 to 3639
Data columns (total 8 columns):
客户代码      3640 non-null object
客户名称      3640 non-null object
客户类别      3640 non-null object
客户地址      3640 non-null object
电话        882 non-null object
传真        783 non-null object
客户中文名称    2635 non-null object
状态        67 non-null object
dtypes: object(8)
memory usage: 227.6+ KB
None

,客户代码,客户名称,客户类别,客户地址,电话,传真,客户中文名称,状态
0,US002562,CERION，LLC,(S),"One Blossom Road, Rochester, NY 14610 USA",NaN,NaN,丝润有限责任公司,NaN
1,US002565,"AD-VANTAGE NETWORKS, INC.",(S),"600 North Brand Blvd., Suite 230 Glendale, CA ...",NaN,NaN,AD-优势网络股份公司,NaN
2,US002566,"TOPS Products, LLC",(S),c/o R.R. Donnelley & Sons Company 111 South Wa...,NaN,NaN,托普斯产品有限责任公司,NaN
3,US002567,"BRIGHENTI, Peter",(S),"430 Carmel Court Canton, Georgia 30114 USA",NaN,NaN,彼得·布里根蒂,NaN
4,US002568,"RANA THERAPEUTICS, INC.",(S),"200 Sidney Street Suite 310 Cambridge, Massac...",NaN,NaN,RANA医疗有限公司,NaN

### US zipcode reference

In [1764]:
zipcodes = pd.read_excel('../US zip codes.xlsx')
print(zipcodes.info())
zipcodes.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40933 entries, 0 to 40932
Data columns (total 7 columns):
Zip Code      40933 non-null int64
Place Name    40933 non-null object
State         40918 non-null object
State_Abbr    40933 non-null object
County        40928 non-null object
Latitude      40933 non-null float64
Longitude     40933 non-null float64
dtypes: float64(2), int64(1), object(4)
memory usage: 2.2+ MB
None

,Zip Code,Place Name,State,State_Abbr,County,Latitude,Longitude
0,501,Holtsville,New York,NY,Suffolk,40.8154,-73.0451
1,544,Holtsville,New York,NY,Suffolk,40.8154,-73.0451
2,1001,Agawam,Massachusetts,MA,Hampden,42.0702,-72.6227
3,1002,Amherst,Massachusetts,MA,Hampshire,42.3671,-72.4646
4,1003,Amherst,Massachusetts,MA,Hampshire,42.3919,-72.5248

In [1765]:
'''Fill zip of len < 5 with use of custom fuction `fillzip_leading_0` '''
zipcodes['Zip Code'] = fillzip_leading_0(zipcodes['Zip Code'])

# verify the number of converted zipcodes
len(zipcodes['Zip Code'][zipcodes['Zip Code'].str.len()==5])

40933

## 2. Construct Regex and Functions

In [1766]:
'''Construct regex to capture Country'''

# string pattern in EN
regex_US_EN = (
          # capture `U.S.A` or `USA`
          r"\b(?:U\.?\s?S\.?\s?A?\.?"
          # capture `United States of America`(including mispelling) with or without 'THE' ahead
          # (?:word_to_search?)? - non capturing group (?: ?), plus ? to indicate optional
          # (?:\w){1,2} inside (?:T(?:\w){1,2}\s*\W*)? to capture 1 or 2 numbers of word character (non-optional) after 'T'
          r"|(?:T(?:\w){1,2}\s*\W*)?(?:UN\w*\s+?)[ST]\w*\s+OF\s+A\w*"
          r"|(?:T(?:\w){1,2}\s*\W*)?UN\w*\s+STA\w*"
          r"|UNITED STATES OF AMERICA TATES OF AMERICA)\b"
         )
regex_others_EN =(r"\b(?:CANADA|CHINA|P\.?R\.?C\.?|SWITZERLAND|GERMANY|INDIA|KOREA|ISRAEL)\b")
regex_country_EN = r"(?:" + regex_US_EN + r"|" + regex_others_EN + r")"


# string pattern in CN
regex_US_CN = (r"(?:美国|加州)")
regex_others_CN = (r"(?:中国|上海|新竹市|山东省)")
regex_country_CN = r"(?:" + regex_US_CN + r"|\W*" + regex_others_CN + r")"


# combine US in EN and CN
regex_US_both = regex_US_EN + r"|" + regex_US_CN

# combine other country in EN and CN
regex_others_both = regex_others_EN + r"|" + regex_others_CN

# combine all countries in EN and CN
regex_country = r"(?P<Country>" + regex_US_both + r"|" + regex_others_both + r")"

### Test on the regex
test_s = '''333 CETNENN新竹市IAL Canada usa 美国p.r.c.the united states OF amriCA SUITE B U.sa LOUISVILLE, CO th United States of 
    A china UNITED STATES OF AMERICA 中国 中国 TATES OF AMERICA'''.upper()

#print(regex_country_EN)
#print(address[2882])
re.findall(regex_country, test_s)

['新竹市',
 'CANADA',
 'USA',
 '美国',
 'THE UNITED STATES OF AMRICA',
 'U.SA',
 'TH UNITED STATES OF \n    A',
 'CHINA',
 'UNITED STATES OF AMERICA',
 '中国',
 '中国']

In [1767]:
'''Construct regex to capture zip'''

### ****** SPLIT RAW STRING INTO MULTIPLE LINES ******* ###
# Use parenthesis to trigger automatic line continuation. 
# The strings will be automatically concatenated.'''


regex_zip = (# the digit must be preceded by a word or non-word character(not empty) - forward positive lookaround
           r"(?<=[\w\W])"
           # the digit might be preeceded by word charactor (e.g. CA94105)
           r"\b[a-zA-Z]*?"
           # any digits of len > 4, might be followed by 1 non word character and then extra digits
           # name the captured string as 'Zip'
           r"(?P<Zip>(?:\d{5}\W?\d{4}?|\d{4,})\b)")

### test regex on individual address:
#val = HQ_clients.Address[0]
val='9701 SE JOHNSON CREEK BOULEVARD, APT. 1306 97086 HAPPYVALLEY OREGON UNITED STATES OF AMERICA'
#print("Test string: {}".format(val))
re.findall(regex_zip, val)

['1306', '97086']

In [1768]:
'''Construct regex to capture city from address'''

# construct regex to capture any patterns representing roads or units
regex_roads = (r"(\b(?:RO?A?D|PLACE|AVE|AVENUE|PARK|PARKWAY|WAY|STREET|S\.?T\.?(?!ATES)|" #negative lookahead make sure the captured 'ST' not before 'ATES'
               r"LANE|DRIVE|BOULDER|B\w*L\w*V\w*D|PIKE)"
               r"\b\W*\s*"
               r"(?:N\.?\s?W\.?|N\.?\s?E\.?|S\.?\s?W\.?|S\.?\s?E\.?)?\W*\s*)"
               )

regex_roads_spanish = r"(\b(?:AVENIDA|CAMINO)(?:\s*\w*){0,}\s*\,\s*)" # in Spanish, street name(one word or more) is placed behind (before next ,)

regex_units = (r"((?:\b(?:UNIT|FL(?:OOR)?|APT\.?|SUITE|COURT|B\w*L\w*D\w*G|P\.?O\.?\s*BOX)\s"
               r"|#)"
               r"\s*(?:\d+)?[A-Z]?\W*\s*)") #UNIT followed optionally by number or A-Z
regex_road_or_unit = r"(" + regex_roads + r"|" + regex_roads_spanish + r"|" + regex_units + r")"



# custom functions to get the string after road/unit wording
def idx_aft_roads(val):
    allmatches = re.findall(regex_road_or_unit, val)
    if len(allmatches)>1:
        start_idx = 0
        end_idx = len(val)
        # search till 
        while re.search(regex_road_or_unit, val[start_idx:end_idx]):
            start_idx += re.search(regex_road_or_unit, val[start_idx:end_idx]).end()
        return start_idx
    elif len(allmatches) ==1:
        return re.search(regex_road_or_unit, val).end()
    else:
        return 0
    
def rest_of_str_aft_road_or_unit(val):
    #print("string: " + val)
    return val[idx_aft_roads(val):]

#### Test the above extraction ###
#val = US_addresses.Address.loc[0]
#val = 'P.O. BOX 194344 SAN JUAN, PR 00919 USA'.upper()
#val = '132 N. EL CAMINO REAL REAL, ENCINITAS, CALIFORNIA 92924 USA'
#val = '132 N. EL CAMINO REAL #287, ENCINITAS, CALIFORNIA 92924 USA'
#val = '420 CHESTNUT LANE, WESTON, FL 33226 USA' ### FL as state duplicates FL as floor
#val = '256 ELEANOR STATES ROOSEVELT ST. SAN JUAN, PUERTO RICO 00918 USA'
#val = '9701 SE JOHNSON CREEK BOULEVARD, APT. 1306 97086 HAPPYVALLEY OREGON UNITED STATES OF AMERICA'
#val = '941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA'
#val = '1434 AIR RAIL AVENUE VIRGINIA BEACH'
val = '333 CENTENNIAL PARKWAY SUITE B LOUISVILLE, CO USA'
rest_of_str_aft_road_or_unit(val)

'LOUISVILLE, CO USA'

In [1769]:
# on a single value
def isEnglish(val):
    try:
        str(val).encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return False
    else:
        return True
    
# on a column
def clean_rest_of_str_aft_rd(col):
    return (col.str.replace(regex_US_both, 'USA') # standard USA input
                 .str.replace(r'\d+$', '') # remove digit at the end
                 .str.replace(r'\w*?[\W\s]*?\d', '') # remove any word string before a digit
                 .str.replace(r'(\d+?[\W\s]+)','')
                 .str.strip()
                 .str.replace(r'(^[\.,]*?|[\.,]*?$)', '')) # remove any . or , at the start or the end

## 3. Select US clients (extract country from address)

### Standardize address formatting

In [1770]:
'''use custom fuction `transform_addresses`'''
address=transform_addresses(HQ_clients['客户地址'])
print("Total addresses on file: {}".format(address.shape[0]))
print('Index: {}'.format(address.index))
address.head().tolist()

Total addresses on file: 3640
Index: RangeIndex(start=0, stop=3640, step=1)

['ONE BLOSSOM ROAD, ROCHESTER, NY 14610 USA',
 '600 NORTH BRAND BLVD., SUITE 230 GLENDALE, CA 91203, USA',
 'C/O R.R. DONNELLEY & SONS COMPANY 111 SOUTH WACKER DRIVE CHICAGO, ILLINOIS 60606 U.S.A.',
 '430 CARMEL COURT CANTON, GEORGIA 30114 USA',
 '200 SIDNEY STREET SUITE 310 CAMBRIDGE, MASSACHUSETTS 02139 USA']

### Extract `Country` from `Address`

In [1771]:
'''Extract all matching strings from address data'''
country_extracted = address.str.extractall(regex_country)
print("Index of records with matches found: {}".format(country_extracted.index.get_level_values(0)))
country_extracted.head()

Index of records with matches found: Int64Index([   0,    1,    2,    3,    4,    5,    7,    8,    9,   10,
            ...
            3629, 3630, 3631, 3632, 3633, 3634, 3635, 3637, 3638, 3639],
           dtype='int64', length=3608)

        Country
  match
0 0         USA
1 0         USA
2 0       U.S.A
3 0         USA
4 0         USA

####  1. Fix the addresses without matching countries

In [1772]:
'''Those address cannot find matching country strings'''
no_matching_country = (address[~pd.Series(address.index)
                               .isin(pd.Series(country_extracted.index.get_level_values(0)))])

'''examine data, if any new pattern found, add to regex_country, re-run the extraction'''
print(no_matching_country.shape[0])
no_matching_country.tolist()

50

['5201 GREAT AMERICA PARKWAY, SUITE 270 SANTA CLARA，CA 95054',
 '2717 LINCOLN STREET EVANSTON, IL 60201',
 '300 CARNEGIE CENTER SUITE 220 PRINCETON, NJ 08540',
 'TWO LIBERTY PLACE 50 S. 16TH STREET, SUITE 3200 PHILADELPHIA, PA 19102-2555',
 '150 N MICHIGAN AVE | SUITE 2700 | CHICAGO, ILLINOIS 60601',
 '9530 JEFFERSON BOULEVARD, CULVER CITY, CALIFORNIA 90232',
 '523 OCEAN FRONT WALK VENICE, CALIFORNIA 90291',
 'TWO SEAPORT LANE, BOSTON, MA 02210-2001',
 '600 BANNER PLACE TOWER 12770 COIT ROAD DALLAS, TEXAS 75251',
 '354 TURNPIKE STREET - SUITE 301A CANTON, MA 02021-2714',
 '158 ROUNDHILL RD BOALSBURG, PA 16827',
 '70 WEST MADISON – SUITE 3500 CHICAGO, ILLINOIS 60602-4424',
 '10250 CONSTELLATION BLVD. SUITE 1700 LOS ANGELES, CA 90067',
 '1411 FOURTH AVENUE, SUITE 760 SEATTLE, WASHINGTON 98101',
 '10041 RAMPART COURT #140 LITTLETON, CO 80125',
 '9280 CRESTWYN HILLS DRIVE MEMPHIS, TN 38125',
 '2603 AUGUSTA DRIVE SUITE 1270 HOUSTON, TX 77057',
 '100 EAST WISCONSIN AVENUE, SUITE 1100 MILWAUKEE, WI 53202',
 '44 MONTGOMERY STREET, 36TH FLOOR SAN FRANCISCO, CA 94104',
 '684 MENDELSSOHN AVENUE N. GOLDEN VALLEY, MN 55427',
 'P.O. BOX 268 PITTSBORO, NORTH CAROLINA 27312',
 '6400 SOUTH FIDDLERS GREEN CIRCLE SUITE 1610 GREENWOOD VILLAGE,CO 80111',
 'THREE EMBARCADERO CENTER,SUITE 1350 SAN FRANCISCO, CA 94111',
 '10 SAINT JAMES AVENUE, 11TH FLOOR | BOSTON, MA 021',
 '222 SOUTH MAIN STREET, SUITE 2200 SALT LAKE CITY, UTAH 84101',
 '99 SMITHTOWN BYPASS 2ND FLOOR HAUPPAUGE, NY 11788',
 '2000 UNIVERSITY AVENUE EAST PALO ALTO, CA 94303',
 'TWO LOGAN SQUARE 100 NORTH 18TH STREET, SUITE 300 PHILADELPHIA, PA 19104',
 '875 THIRD AVENUE NEW YORK, NEW YORK 10022',
 '1875 EYE STREET NW, SUITE 1200 WASHINGTON, DC 20006',
 '101 SOUTH SALINA STREET, 7TH FLOOR SYRACUSE, NEW YORK 13202',
 '1500 K STREET, N.W. SUITE 1100, WASHINGTON, DC 20005-1209',
 '4 PENN CENTER, 1600 JFK BLVD., 2ND FLOOR, PHILADELPHIA, PA 19103',
 '8800 NORTH GAINEY CENTER DRIVE SUITE 279 SCOTTSDALE, ARIZONA 85258',
 '77 WEST WACKER DRIVE, FIFTH FLOOR CHICAGO, IL 60601',
 '4624E. MERCER WAY, MERCER ISLAND, WA 98040',
 '19 GREAT OAKS BVLD., SUITE 20, SAN JOSE, CA95119',
 '400 MAIN STREET, MS 132-13 EAST HARTFORD, CT 06108',
 'THE CHRYSLER BUILDING 405 LEXINGTON AVENUE NEW YORK,NY 10174-0208',
 '3150 PORTER DRIVE PALO ALTO, CA 94304-1212',
 'REED SMITH CENTER 225FIFTH AVENUE PITTSBURGH, PA 15222',
 '3580 CARMEL MOUNTAIN ROAD, SUITE 300 SAN DIEGO, CA 92130',
 'C/O GENE MOSHKOVICH 917 LOMA VISTA BEVERLY HILLS, CA 90210',
 '900 DOUGLAS PIKE SMITHFIELD, RI 02903',
 '999 PEACHTREE STREET NE SUITE 1300 ATLANTA, GEORGIA 30309',
 '222 NORTH WASHINGTON SQUARE SUITE 400 LANSING, MI 48933-1800',
 '12531 HIGH BLUFF DRIVE SAN DIEGO, CA 92130-2040',
 '600 ANTON BOULEVARD STUIE 900 COSTA MESA, CA 92626-7221',
 '10 E. UNIVERSITY AVENUE GAINESVILLE, FLORIDA 32601',
 '701 FIFTH AVENUE, SUITE 4800-SEATTLE, WASHINGTON 98104']

In [1773]:
'''After confirming all the above are US addresses, save it to a new dataframe'''

cols = ['ClientID','Address', 'Zip', 'Country', 'City']
clientIDs = HQ_clients.loc[no_matching_country.index, '客户代码']
addresses = no_matching_country
zipCodes = np.full(len(no_matching_country), np.nan)
countries = np.full(len(no_matching_country), 'USA')
cities = np.full(len(no_matching_country), np.nan)

US_addresses = pd.DataFrame(list(zip(clientIDs, addresses,zipCodes,countries, cities)),
                          columns=cols, index=addresses.index)

print("Number of US clients added: {}".format(US_addresses.shape[0]))
US_addresses.head()

Number of US clients added: 50

,ClientID,Address,Zip,Country,City
6,US002570,"5201 GREAT AMERICA PARKWAY, SUITE 270 SANTA CL...",NaN,USA,NaN
64,US002912,"2717 LINCOLN STREET EVANSTON, IL 60201",NaN,USA,NaN
115,US003521,"300 CARNEGIE CENTER SUITE 220 PRINCETON, NJ 08540",NaN,USA,NaN
136,US002719,"TWO LIBERTY PLACE 50 S. 16TH STREET, SUITE 320...",NaN,USA,NaN
162,US002755,"150 N MICHIGAN AVE | SUITE 2700 | CHICAGO, ILL...",NaN,USA,NaN

#### 2. Examine those with matches found and fix any issues

In [1774]:
'''Check the countries captured''' 
country_extracted.Country.value_counts().sort_index()

CANADA                             2
CHINA                              7
INDIA                              3
ISRAEL                             1
KOREA                              2
P.R.C                              1
SWITZERLAND                        2
THE UNITD STATES OF AMERICA        1
THE UNITED STATES OF AMERICA       3
U. S. A                            2
U.S.                               3
U.S.A                            253
UNITED STATE                       1
UNITED STATE OF AMERICA            1
UNITED STATES                     33
UNITED STATES OF AMERCIA           1
UNITED STATES OF AMERICA         539
UNITED STATES OF AMRICA            3
UNITED STATS OF AMERICA            1
UNITES STATES OF AMERICA           1
UNTED STATES OF AMERICA            1
UNTIED STATES OF AMERICA           1
US                                25
US                                 7
USA                             2704
上海                                 1
中国                                 1
加州                                 3
山东省                                2
新竹市                                1
美国                                 2
Name: Country, dtype: int64

In [1775]:
'''If any matches are not countries, replace them with empty string '''
raw_exclude = r"(SITY OF ARIZONA |TOURO STREET|ULSTER ST|UNION SQUARE|UNION STREET|UNIVERSITY (?:SERVICES|STREET))"
country_extracted.Country = country_extracted.Country.str.replace(raw_exclude, 'NA')
(country_extracted.Country=='NA').sum()

0

In [1776]:
'''Make the extracted data more easy to work with'''

# Unstack the multiindexed extracted data frame and then merge 'address' column
address_with_matching_country = country_extracted.unstack()
cols = list(address_with_matching_country.columns.get_level_values(1))
address_with_matching_country.columns = ["country{}".format(col) for col in cols]
address_with_matching_country['Address'] = address[address_with_matching_country.index]
address_with_matching_country['ClientID'] = HQ_clients.loc[address_with_matching_country.index, '客户代码']

print('Number of address found with matching country: {}'.format(address_with_matching_country.shape[0]))
address_with_matching_country.head()

Number of address found with matching country: 3590

,country0,country1,Address,ClientID
0,USA,NaN,"ONE BLOSSOM ROAD, ROCHESTER, NY 14610 USA",US002562
1,USA,NaN,"600 NORTH BRAND BLVD., SUITE 230 GLENDALE, CA ...",US002565
2,U.S.A,NaN,C/O R.R. DONNELLEY & SONS COMPANY 111 SOUTH WA...,US002566
3,USA,NaN,"430 CARMEL COURT CANTON, GEORGIA 30114 USA",US002567
4,USA,NaN,"200 SIDNEY STREET SUITE 310 CAMBRIDGE, MASSACH...",US002568

In [1777]:
''' Now, filter the data with more than 1 matches and save it to a temp df '''
filter_1 = ~address_with_matching_country.country1.isna()
addresses_with_more_than_1match = address_with_matching_country[filter_1].sort_values('country1')
print("Number of records with more than 1 match found: {}".format(addresses_with_more_than_1match.shape[0]))
addresses_with_more_than_1match.sort_index()

Number of records with more than 1 match found: 18

,country0,country1,Address,ClientID
16,US,USA,"600 NORTH US HIGHWAY 45, LIBERTYVILLE, ILLINOI...",US002592
664,US,USA,"US 08648 NJ LAWRENCEVILLE, 1009 LENOX DRIVE, S...",US003161
1163,USA,USA,"CORNELL BUSINESS AND TECHNOLOGY PARK, 20 THORN...",US000240
1278,US,USA,"1815 N. US HIGHWAY 1, ORMOND BEACH, FLORIDA 32...",US000362
1388,CHINA,CHINA,5701 CHINA WORLD TOWER NO.1 JIANGUOMENWAI AVEN...,US000474
1389,US,USA,"1031 US HIGHWAY 22. SUITE 303 BRIDGEWATER, NEW...",US000475
1432,INDIA,INDIA,"NICHOLAS PIRAMAL RESEARCH CENTRE, NICHOLAS PIR...",US000518
1462,CHINA,CHINA,3201 CHINA WORLD TOWER 1 NO. 1 JIANGUOMENWAI A...,US000548
1575,INDIA,UNITED STATES OF AMERICA,"85 EAST INDIA ROW, 15G, BOSTON, MASSACHUSETTS ...",US000662
1586,U.S.,UNITED STATES OF AMERICA,"1801 U.S. HIGHWAY 52 N.W., WEST LAFAYETTE, IND...",US000672
1776,美国,加州,美国加州新港海滨詹伯瑞路4311号,US000862
1866,U.S.,USA,"1000 U.S. ROUTE 202, RARITAN NEW JERSY 08869, USA",US000953
2327,U.S.,USA,"1160 U.S. HIGHWAY 22, SUITE 104, BRIDGEWATER, ...",US001424
2365,美国,加州,美国 加州 佛利蒙 利马街51号,US001463
2393,USA,USA,"C/O SYNERCHIP USA CORP., 845 STEWART DRIVE, SU...",US001491
2661,US,USA,"ONE US BANK PLAZA ST. LOUIS, MO 63101 USA",US001763
2882,CANADA,USA,"5128 STONEGLEN ROAD, LA CANADA, CA 91011, USA",US001995
2902,US,USA,"1001 N. US HIGHWAY 1, JUPITER, FL 33477, USA",US002015

In [1778]:
# inspect a specific address if any issue
addresses_with_more_than_1match.loc[1432].tolist()

['INDIA',
 'INDIA',
 'NICHOLAS PIRAMAL RESEARCH CENTRE, NICHOLAS PIRAMAL INDIA LIMITED, 1, NIRLON COMPLEX, OFF WESTERN EXPRESS HIGHWAY, GOREGAON (EAST). MUMBAI 400063, STATE OF MAHARASHTRA INDIA',
 'US000518']

In [1779]:
'''Update country data for the above with verified selection '''

# Selecte other country and US indices
other_country_idx = filter_rows_with_val2(addresses_with_more_than_1match, ['country1'], regex_others_both).index
us_idx = filter_rows_with_val2(addresses_with_more_than_1match, ['country1'], regex_US_both).index

# Fill in country data in original address_with_matching_country 
address_with_matching_country.loc[us_idx,'Country']='USA'
address_with_matching_country.loc[other_country_idx,'Country']=addresses_with_more_than_1match.loc[other_country_idx, 'country1']

# review the updated data
print("Number of records updated: {}".format(address_with_matching_country[~address_with_matching_country.Country.isnull()].shape[0]))
address_with_matching_country[~address_with_matching_country.Country.isnull()].head()

Number of records updated: 18

,country0,country1,Address,ClientID,Country
16,US,USA,"600 NORTH US HIGHWAY 45, LIBERTYVILLE, ILLINOI...",US002592,USA
664,US,USA,"US 08648 NJ LAWRENCEVILLE, 1009 LENOX DRIVE, S...",US003161,USA
1163,USA,USA,"CORNELL BUSINESS AND TECHNOLOGY PARK, 20 THORN...",US000240,USA
1278,US,USA,"1815 N. US HIGHWAY 1, ORMOND BEACH, FLORIDA 32...",US000362,USA
1388,CHINA,CHINA,5701 CHINA WORLD TOWER NO.1 JIANGUOMENWAI AVEN...,US000474,CHINA

In [1780]:
'''Now, fill in the verified countries for the rest of data (only 1 match) '''

filter_country1_NA = address_with_matching_country.country1.isna()
rest_data_with_only_1match = address_with_matching_country[filter_country1_NA]
print("Number of records with only 1 match found: {}".format(rest_data_with_only_1match.shape[0]))
rest_data_with_only_1match.head()

Number of records with only 1 match found: 3572

,country0,country1,Address,ClientID,Country
0,USA,NaN,"ONE BLOSSOM ROAD, ROCHESTER, NY 14610 USA",US002562,NaN
1,USA,NaN,"600 NORTH BRAND BLVD., SUITE 230 GLENDALE, CA ...",US002565,NaN
2,U.S.A,NaN,C/O R.R. DONNELLEY & SONS COMPANY 111 SOUTH WA...,US002566,NaN
3,USA,NaN,"430 CARMEL COURT CANTON, GEORGIA 30114 USA",US002567,NaN
4,USA,NaN,"200 SIDNEY STREET SUITE 310 CAMBRIDGE, MASSACH...",US002568,NaN

In [1781]:
# Select indices
filter_others = rest_data_with_only_1match.country0.str.contains(regex_others_both)
other_country_idx = rest_data_with_only_1match[filter_others].index.tolist()
filter_US = rest_data_with_only_1match.country0.str.contains(regex_US_both)
us_idx = rest_data_with_only_1match[filter_US].index.tolist()

# Fill in country data
address_with_matching_country.loc[us_idx,'Country']='USA'
address_with_matching_country.loc[other_country_idx, 'Country']=address_with_matching_country.loc[other_country_idx, 'country0']

# Review the final count of countries
address_with_matching_country['Country'].value_counts()

USA            3572
CHINA             5
山东省               2
SWITZERLAND       2
KOREA             2
P.R.C             1
中国                1
CANADA            1
INDIA             1
新竹市               1
上海                1
ISRAEL            1
Name: Country, dtype: int64

In [1782]:
# verify the above result by examining specific country 
filter_rows_with_val2(address_with_matching_country, ['country0','country1'],'山东省')

     country0 country1                 Address  ClientID Country
3326      山东省      NaN  山东省潍坊市奎文区世纪泰华水印公寓D座28层  US002447     山东省
3327      山东省      NaN  山东省潍坊市奎文区世纪泰华水印公寓D座28层  US002448     山东省

In [1783]:
US_addresses.columns

Index(['ClientID', 'Address', 'Zip', 'Country', 'City'], dtype='object')

#### 3. Save above data to corresponding dataframes

In [1784]:
'''Add the data with matching USA to `US_addresses'''
filter_US = address_with_matching_country.Country == 'USA'
cols = US_addresses.columns
US_addresses = US_addresses.append(address_with_matching_country.loc[filter_US, cols]).sort_index().drop_duplicates()
print("Number of US addresses: {}".format(US_addresses.shape[0]))
US_addresses.head()

Number of US addresses: 3622

/Users/catelinn/miniconda3/lib/python3.7/site-packages/pandas/core/indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

,ClientID,Address,Zip,Country,City
0,US002562,"ONE BLOSSOM ROAD, ROCHESTER, NY 14610 USA",NaN,USA,NaN
1,US002565,"600 NORTH BRAND BLVD., SUITE 230 GLENDALE, CA ...",NaN,USA,NaN
2,US002566,C/O R.R. DONNELLEY & SONS COMPANY 111 SOUTH WA...,NaN,USA,NaN
3,US002567,"430 CARMEL COURT CANTON, GEORGIA 30114 USA",NaN,USA,NaN
4,US002568,"200 SIDNEY STREET SUITE 310 CAMBRIDGE, MASSACH...",NaN,USA,NaN

In [1785]:
''' Save the data with other matching countries to `other_addresses`'''
filter_other = address_with_matching_country.Country != 'USA'
other_addresses = address_with_matching_country.loc[filter_other,cols]
print("Number of other addresses: {}".format(other_addresses.shape[0]))
other_addresses.to_excel('Clients in other countries.xlsx')
other_addresses

Number of other addresses: 18

,ClientID,Address,Zip,Country,City
346,US002993,"403, 30 MCHUGH CRT., CALGARY, ALBERTA T2E 7X3 ...",NaN,CANADA,NaN
854,US002836,"33-4, SANGBONGJUNGANG-RO 8-NA-GIL, JUNGNANG-GU...",NaN,KOREA,NaN
1388,US000474,5701 CHINA WORLD TOWER NO.1 JIANGUOMENWAI AVEN...,NaN,CHINA,NaN
1404,US000490,中国北京市朝阳区 延静西里2号华商大厦918,NaN,中国,NaN
1432,US000518,"NICHOLAS PIRAMAL RESEARCH CENTRE, NICHOLAS PIR...",NaN,INDIA,NaN
1462,US000548,3201 CHINA WORLD TOWER 1 NO. 1 JIANGUOMENWAI A...,NaN,CHINA,NaN
1514,US000600,"4TH FLOOR, 27 ZHONGSHAN DONG YI ROAD, SHANGHAI...",NaN,CHINA,NaN
1623,US000708,"SUITE 4201, 42D FLOOR, BUND CENTER 222 YAN AN ...",NaN,CHINA,NaN
1653,US000739,"1F, BUILDING 28, RING BUILDING, ZHONGGUANCUN S...",NaN,P.R.C,NaN
2247,US001344,上海市天钥桥路30号美罗大厦17楼 邮编：200030,NaN,上海,NaN
2304,US001401,新竹市,NaN,新竹市,NaN
2750,US001857,"218 XINGHU STREET A3 BUILDING, SUITE 218, SUZH...",NaN,CHINA,NaN
2800,US001909,BUCHMATTSTRASSE 46 CH 3400 BURGDORF SWITZERLAND,NaN,SWITZERLAND,NaN
2838,US001951,BROWN BOVERI STRASSE 7 5401 BADEN SWITZERLAND,NaN,SWITZERLAND,NaN
3326,US002447,山东省潍坊市奎文区世纪泰华水印公寓D座28层,NaN,山东省,NaN
3327,US002448,山东省潍坊市奎文区世纪泰华水印公寓D座28层,NaN,山东省,NaN
3352,US002473,103-504 MUHAKRO 50 SUNGDONG-GU SEOUL 133-773 R...,NaN,KOREA,NaN
3377,US002500,"TIDHAR 9, 99553 BET SHEMESH, ISRAEL",NaN,ISRAEL,NaN

## 4. Extract Zips from US addresses

### Extract Zip from address

In [1786]:
'''Extract all possible matching strings from address'''
extracted_Zip_from_address = US_addresses.Address.str.extractall(regex_zip).unstack()
print("Matches found: {}".format(extracted_Zip_from_address.shape[0]))
print("\nSample: ")
extracted_Zip_from_address.head()

Matches found: 3577

Sample:

         Zip
match      0    1    2    3
0      14610  NaN  NaN  NaN
1      91203  NaN  NaN  NaN
2      60606  NaN  NaN  NaN
3      30114  NaN  NaN  NaN
4      02139  NaN  NaN  NaN

#### 1. Review unmatched records to catch more pattern

In [1787]:
'''Examine the addresses without zip captured'''
'''look for patterns to capture more zip and add them to regex above, rerun extraction'''
no_matching_zip = US_addresses[~US_addresses.index.isin(extracted_Zip_from_address.index)]
print("Number of records without matches found: {}".format(no_matching_zip.shape[0]))
no_matching_zip.Address.tolist()

Number of records without matches found: 45

['333 CENTENNIAL PARKWAY SUITE B LOUISVILLE, CO USA',
 '1909 K STREET NW, SUITE 900, USA',
 'LAGUNA NIGUEL, CA USA',
 'LAGUNA HILLS, CA USA',
 'DELAWARE USA',
 '1434 AIR RAIL AVENUE VIRGINIA BEACH, VA USA',
 '57 SEAVIEW BOULEVARD PORT WASHINGTON,NY U.S.A.',
 'NORTH CAROLINA, USA',
 'ROCKWALL TEXAS UNITED STATES OF AMERICA',
 'ROCKWALL TEXAS UNITED STATES OF AMERICA',
 '3472 88TH AVENUE NE CIRCLE PINES, MN USA',
 '1613 PINEVIEW DRIVE RALEIGH, NORTH CAROLINA UNITED STATES OF AMERICA',
 '1401 CROOKS ROAD, TROY, MICHIGAN USA',
 '941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA',
 'SAN DIEGO USA',
 '10 SAINT JAMES AVENUE, 11TH FLOOR | BOSTON, MA 021',
 'TEXAS USA',
 'PLYMOUTH, MN USA',
 'BURNSVILLE, MN USA',
 '3411 SILVERSIDE RD., RODNEY BLDG. SUITE 104, WILMINGTON, DELAWARE USA',
 '941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA',
 '9000 CROW CANYON ROAD, SUITE S393, DANVILLE, CALIFORNIA 94S06 USA',
 'IN. U.S.A.',
 'DELAWARE, U.S.A.',
 '美国加州新港海滨詹伯瑞路4311号',
 '301 MERRITT 7, NORWALK, CONNECTICUT UNITED STATES OF AMERICA',
 '2711 CENTERVILLE ROAD, SUITE 400, CITY OF WILMINGTON, COUNTY OF NEW CASTLE, DELAWARE USA',
 'WASHINGTON, DISTRICT OF COLUMBIA USA',
 '225 INDUSTRIAL DRIVE SALINE, MICHIGAN UNITED STATES OF AMERICA',
 '加州95124-3400圣荷西罗吉克路2100号',
 '美国 加州 佛利蒙 利马街51号',
 '6444 SOUTH 6TH STREET ROAD SPRINGFIELD, ILLINOIS USA',
 '2 WARE STREET, APT. 507, CAMBRIDGE, MASSACHUSETTS USA',
 '15025 SW KOLL PARKWAY BEAVERTON, OREGON UNITED STATES OF AMERICA',
 '150 NORTH MARTINGALE ROAD, SCHAUMBURG, ILLINOIS, U.S.A.',
 '8905 S.W. 87TH AVENUE, MIAMI, USA',
 'DELAWARE USA',
 'AUSTIN TEXAS USA',
 '103 CARNEGIE CENTER, SUITE 300, PRINCETON, NJ USA',
 '340 GREEN OAKS LANE, SOUTHLAKE, TX USA',
 '5 PEARL COURT ALLENDALE PARK NEW JERSEY USA',
 '101 PEAVEY ROAD CHASKA, MINNESOTA US',
 'CALIFORNIA, USA',
 'PACIFIC PALISADES, CALIFORNIA USA',
 'LOS ANGELES, CALIFORNIA USA']

In [1788]:
'''Quick fix to specific case'''
# if there is particular error, e.g. `CALIFORNIA 94S06 USA`, fix it right away in `US_addresses`, and then rerun extraction
US_addresses['Address'] = US_addresses.Address.str.replace('94S06', '94506')

In [1789]:
'''Review the result after adding a zip pattern to regex'''
# Use custom function filter_rows_with_zip to check whether the a specific zip code pattern is captured now
# e.g. can it capture '97086' in "APT. 1306 97086 HAPPYVALLEY OREGON UNITED STATES OF AMERICA" now? - Yes!
containZip = filter_rows_with_val(extracted_Zip_from_address, extracted_Zip_from_address.columns, '94506')
US_addresses.Address.loc[extracted_Zip_from_address[containZip].index].tolist()

['5443 BLACKHAWK DRIVE DANVILLE, CALIFORNIA 94506 UNITED STATES OF AMERICA',
 '9000 CROW CANYON ROAD, SUITE S393, DANVILLE, CALIFORNIA 94506, USA']

#### 2. Review the records with matching zip

In [1790]:
'''Make the extracted data more easy to work with'''
extracted_Zip_from_address['Address'] = US_addresses.Address.loc[extracted_Zip_from_address.index]
extracted_Zip_from_address.columns = ['Zip1', 'Zip2', 'Zip3', 'Zip4','Address']
print(extracted_Zip_from_address.shape[0])
extracted_Zip_from_address.sample(10)

3577

,Zip1,Zip2,Zip3,Zip4,Address
3438,92008,NaN,NaN,NaN,"5545 FERMI COURT CARLSBAD, CALIFORNIA 92008 TH..."
2868,94104,NaN,NaN,NaN,"555 CALIFORNIA STREET, 12TH FLOOR SAN FRANCISC..."
1054,30097,NaN,NaN,NaN,"305 GREEN WAY, DULUTH, CA 30097 U.S.A."
739,06268-0503,NaN,NaN,NaN,"P.O. BOX 503 STORRS, CONNECTICUT U.S.A. 06268-..."
3151,92507,NaN,NaN,NaN,"1040 IOWA AVENUE, SUITE 100 RIVERSIDE, CALIFOR..."
2772,84055,NaN,NaN,NaN,"4383 NORTH RIVER ROAD OAKLEY, UTAH 84055 USA"
558,7400,48098,NaN,NaN,"750 TOWER DRIVE, MAIL CODE 7400 TROY, MI 48098..."
3066,60093,NaN,NaN,NaN,"THREE LAKES DRIVE NORTHFIELD, ILLINOIS 60093 USA"
2387,1300,84106,NaN,NaN,"2150 SOUTH 1300 EAST, SUITE 500, SALT LAKE CIT..."
1841,1201,30309-3424,NaN,NaN,ONE ATLANTIC CENTER 1201 WEST PEACHTREE STREET...

## 5. Extract city from addresses without matching zip

In [1791]:
'''Extract the possible city information - any string after road/unit'''
no_matching_zip_extracted_cities = no_matching_zip.Address.apply(rest_of_str_aft_road_or_unit)
clean_rest_of_str_aft_rd(no_matching_zip_extracted_cities)

72                                     LOUISVILLE, CO USA
168                                                   USA
238                                 LAGUNA NIGUEL, CA USA
239                                  LAGUNA HILLS, CA USA
283                                          DELAWARE USA
284                                VIRGINIA BEACH, VA USA
305                                PORT WASHINGTON,NY USA
336                                   NORTH CAROLINA, USA
337                                    ROCKWALL TEXAS USA
338                                    ROCKWALL TEXAS USA
379                                  CIRCLE PINES, MN USA
396                           RALEIGH, NORTH CAROLINA USA
399                                    TROY, MICHIGAN USA
474                            CAMARILLO, CALIFORNIA, USA
520                                         SAN DIEGO USA
589                                            BOSTON, MA
613                                             TEXAS USA
665                                      PLYMOUTH, MN USA
696                                    BURNSVILLE, MN USA
763                              WILMINGTON, DELAWARE USA
892                            CAMARILLO, CALIFORNIA, USA
974                                        DANVILLE,  USA
1071                                              IN. USA
1288                                        DELAWARE, USA
1776                                                    号
1895                             NORWALK, CONNECTICUT USA
2224    CITY OF WILMINGTON, COUNTY OF NEW CASTLE, DELA...
2234                 WASHINGTON, DISTRICT OF COLUMBIA USA
2306                                 SALINE, MICHIGAN USA
2316                                                    号
2365                                        USA USA 佛利蒙 号
2447                            SPRINGFIELD, ILLINOIS USA
2709                         CAMBRIDGE, MASSACHUSETTS USA
2887                                BEAVERTON, OREGON USA
2888                            SCHAUMBURG, ILLINOIS, USA
2981                                           MIAMI, USA
2993                                         DELAWARE USA
3179                                     AUSTIN TEXAS USA
3208                                    PRINCETON, NJ USA
3313                                    SOUTHLAKE, TX USA
3368                                         W JERSEY USA
3411                                CHASKA, MINNESOTA USA
3448                                      CALIFORNIA, USA
3515                    PACIFIC PALISADES, CALIFORNIA USA
3516                          LOS ANGELES, CALIFORNIA USA
Name: Address, dtype: object

In [1792]:
'''Clean up the extracted city information'''

# clean up English data only
onlyEnglish = no_matching_zip_extracted_cities.apply(isEnglish)
no_matching_zip_extracted_cities[onlyEnglish] = clean_rest_of_str_aft_rd(no_matching_zip_extracted_cities[onlyEnglish])
no_matching_zip_extracted_cities

72                                     LOUISVILLE, CO USA
168                                                   USA
238                                 LAGUNA NIGUEL, CA USA
239                                  LAGUNA HILLS, CA USA
283                                          DELAWARE USA
284                                VIRGINIA BEACH, VA USA
305                                PORT WASHINGTON,NY USA
336                                   NORTH CAROLINA, USA
337                                    ROCKWALL TEXAS USA
338                                    ROCKWALL TEXAS USA
379                                  CIRCLE PINES, MN USA
396                           RALEIGH, NORTH CAROLINA USA
399                                    TROY, MICHIGAN USA
474                            CAMARILLO, CALIFORNIA, USA
520                                         SAN DIEGO USA
589                                            BOSTON, MA
613                                             TEXAS USA
665                                      PLYMOUTH, MN USA
696                                    BURNSVILLE, MN USA
763                              WILMINGTON, DELAWARE USA
892                            CAMARILLO, CALIFORNIA, USA
974                                        DANVILLE,  USA
1071                                              IN. USA
1288                                        DELAWARE, USA
1776                                    美国加州新港海滨詹伯瑞路4311号
1895                             NORWALK, CONNECTICUT USA
2224    CITY OF WILMINGTON, COUNTY OF NEW CASTLE, DELA...
2234                 WASHINGTON, DISTRICT OF COLUMBIA USA
2306                                 SALINE, MICHIGAN USA
2316                             加州95124-3400圣荷西罗吉克路2100号
2365                                     美国 加州 佛利蒙 利马街51号
2447                            SPRINGFIELD, ILLINOIS USA
2709                         CAMBRIDGE, MASSACHUSETTS USA
2887                                BEAVERTON, OREGON USA
2888                            SCHAUMBURG, ILLINOIS, USA
2981                                           MIAMI, USA
2993                                         DELAWARE USA
3179                                     AUSTIN TEXAS USA
3208                                    PRINCETON, NJ USA
3313                                    SOUTHLAKE, TX USA
3368                                         W JERSEY USA
3411                                CHASKA, MINNESOTA USA
3448                                      CALIFORNIA, USA
3515                    PACIFIC PALISADES, CALIFORNIA USA
3516                          LOS ANGELES, CALIFORNIA USA
Name: Address, dtype: object

In [1793]:
# Examine speicifc address if needed
US_addresses.loc[2981].tolist()

['US002094', '8905 S.W. 87TH AVENUE, MIAMI, USA', nan, 'USA', nan]

In [1794]:
# Update the non-English data with English city info'''
no_matching_zip_extracted_cities[(~onlyEnglish)]

1776           美国加州新港海滨詹伯瑞路4311号
2316    加州95124-3400圣荷西罗吉克路2100号
2365            美国 加州 佛利蒙 利马街51号
Name: Address, dtype: object

In [1795]:
no_matching_zip_extracted_cities[(~onlyEnglish)] = ['New Port, CA USA','San Jose, CA USA','Fremont, CA USA']
no_matching_zip_extracted_cities[(~onlyEnglish)]

1776    New Port, CA USA
2316     Fremont, CA USA
2365    New Port, CA USA
Name: Address, dtype: object

In [1796]:
'''Save the extracted cities from no_matching_zip addresses to US_addresses'''
clean = transform_addresses(no_matching_zip_extracted_cities).str.replace(r'[\s\,\.]*?USA$', '')
US_addresses.loc[no_matching_zip_extracted_cities.index,'City'] = clean
print("Number of records with city: {}".format(US_addresses[~US_addresses.City.isna()].shape[0]))
US_addresses[~US_addresses.City.isna()]

Number of records with city: 45

,ClientID,Address,Zip,Country,City
72,US002913,"333 CENTENNIAL PARKWAY SUITE B LOUISVILLE, CO USA",NaN,USA,"LOUISVILLE, CO"
168,US002740,"1909 K STREET NW, SUITE 900, USA",NaN,USA,
238,US002809,"LAGUNA NIGUEL, CA USA",NaN,USA,"LAGUNA NIGUEL, CA"
239,US002810,"LAGUNA HILLS, CA USA",NaN,USA,"LAGUNA HILLS, CA"
283,US003046,DELAWARE USA,NaN,USA,DELAWARE
284,US003048,"1434 AIR RAIL AVENUE VIRGINIA BEACH, VA USA",NaN,USA,"VIRGINIA BEACH, VA"
305,US003485,"57 SEAVIEW BOULEVARD PORT WASHINGTON,NY U.S.A.",NaN,USA,"PORT WASHINGTON,NY"
336,US002977,"NORTH CAROLINA, USA",NaN,USA,NORTH CAROLINA
337,US002963,ROCKWALL TEXAS UNITED STATES OF AMERICA,NaN,USA,ROCKWALL TEXAS
338,US002964,ROCKWALL TEXAS UNITED STATES OF AMERICA,NaN,USA,ROCKWALL TEXAS
379,US002965,"3472 88TH AVENUE NE CIRCLE PINES, MN USA",NaN,USA,"CIRCLE PINES, MN"
396,US003542,"1613 PINEVIEW DRIVE RALEIGH, NORTH CAROLINA UN...",NaN,USA,"RALEIGH, NORTH CAROLINA"
399,US003544,"1401 CROOKS ROAD, TROY, MICHIGAN USA",NaN,USA,"TROY, MICHIGAN"
474,US003072,"941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA",NaN,USA,"CAMARILLO, CALIFORNIA"
520,US002961,SAN DIEGO USA,NaN,USA,SAN DIEGO
589,US003247,"10 SAINT JAMES AVENUE, 11TH FLOOR | BOSTON, MA...",NaN,USA,"BOSTON, MA"
613,US003269,TEXAS USA,NaN,USA,TEXAS
665,US003143,"PLYMOUTH, MN USA",NaN,USA,"PLYMOUTH, MN"
696,US003215,"BURNSVILLE, MN USA",NaN,USA,"BURNSVILLE, MN"
763,US002527,"3411 SILVERSIDE RD., RODNEY BLDG. SUITE 104, W...",NaN,USA,"WILMINGTON, DELAWARE"
892,US003394,"941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA",NaN,USA,"CAMARILLO, CALIFORNIA"
974,US000050,"9000 CROW CANYON ROAD, SUITE S393, DANVILLE, C...",NaN,USA,DANVILLE
1071,US000147,IN. U.S.A.,NaN,USA,IN
1288,US000373,"DELAWARE, U.S.A.",NaN,USA,DELAWARE
1776,US000862,美国加州新港海滨詹伯瑞路4311号,NaN,USA,"NEW PORT, CA"
1895,US000982,"301 MERRITT 7, NORWALK, CONNECTICUT UNITED STA...",NaN,USA,"NORWALK, CONNECTICUT"
2224,US001319,"2711 CENTERVILLE ROAD, SUITE 400, CITY OF WILM...",NaN,USA,"CITY OF WILMINGTON, COUNTY OF NEW CASTLE, DELA..."
2234,US001330,"WASHINGTON, DISTRICT OF COLUMBIA USA",NaN,USA,"WASHINGTON, DISTRICT OF COLUMBIA"
2306,US001403,"225 INDUSTRIAL DRIVE SALINE, MICHIGAN UNITED S...",NaN,USA,"SALINE, MICHIGAN"
2316,US001413,加州95124-3400圣荷西罗吉克路2100号,NaN,USA,"FREMONT, CA"
2365,US001463,美国 加州 佛利蒙 利马街51号,NaN,USA,"NEW PORT, CA"
2447,US001545,"6444 SOUTH 6TH STREET ROAD SPRINGFIELD, ILLINO...",NaN,USA,"SPRINGFIELD, ILLINOIS"
2709,US001815,"2 WARE STREET, APT. 507, CAMBRIDGE, MASSACHUSE...",NaN,USA,"CAMBRIDGE, MASSACHUSETTS"
2887,US002000,"15025 SW KOLL PARKWAY BEAVERTON, OREGON UNITED...",NaN,USA,"BEAVERTON, OREGON"
2888,US002001,"150 NORTH MARTINGALE ROAD, SCHAUMBURG, ILLINOI...",NaN,USA,"SCHAUMBURG, ILLINOIS"
2981,US002094,"8905 S.W. 87TH AVENUE, MIAMI, USA",NaN,USA,MIAMI
2993,US002106,DELAWARE USA,NaN,USA,DELAWARE
3179,US002297,AUSTIN TEXAS USA,NaN,USA,AUSTIN TEXAS
3208,US002327,"103 CARNEGIE CENTER, SUITE 300, PRINCETON, NJ USA",NaN,USA,"PRINCETON, NJ"
3313,US002434,"340 GREEN OAKS LANE, SOUTHLAKE, TX USA",NaN,USA,"SOUTHLAKE, TX"
3368,US002489,5 PEARL COURT ALLENDALE PARK NEW JERSEY USA,NaN,USA,W JERSEY
3411,US003480,"101 PEAVEY ROAD CHASKA, MINNESOTA US",NaN,USA,"CHASKA, MINNESOTA"
3448,US002712,"CALIFORNIA, USA",NaN,USA,CALIFORNIA
3515,US003080,"PACIFIC PALISADES, CALIFORNIA USA",NaN,USA,"PACIFIC PALISADES, CALIFORNIA"
3516,US003081,"LOS ANGELES, CALIFORNIA USA",NaN,USA,"LOS ANGELES, CALIFORNIA"

## 6. Continue to work on the addresses with matching zips - pick the right zip

### Clean all captured zip strings

In [1797]:
### Standardize zip codes formatting
cols = ['Zip1', 'Zip2', 'Zip3', 'Zip4']
extracted_Zip_from_address[cols] = extracted_Zip_from_address[cols].apply(clean_zip_cols)
print("Number of records: {}".format(extracted_Zip_from_address.shape[0]))
extracted_Zip_from_address.sample(10)

Number of records: 3577

,Zip1,Zip2,Zip3,Zip4,Address
1350,52242,NaN,NaN,NaN,"6 GILMORE HALL, 112 N. CAPITOL STREET IOWA CIT..."
575,94107,NaN,NaN,NaN,"303 2ND STREET SAN FRANCISCO, CA 94107 USA"
2609,48083,NaN,NaN,NaN,"1870 TECHNOLOGY DRIVE TROY, MICHIGAN 48083 USA"
393,94539,NaN,NaN,NaN,"47102 MISSION FALLS COURT, SUITE 218 FREMONT, ..."
1247,95670,NaN,NaN,NaN,"2330 GOLD MEADOW WAY, GOLD RIVER, CALIFORNIA 9..."
3456,97223,NaN,NaN,NaN,"7166 SW OLESON ROAD, APT. 47 97223 PORTLAND OR..."
3247,63010,NaN,NaN,NaN,"537 HICKORY MANOR ARNOLD, MISSOURI 63010 USA"
2833,5600,77002-1001,NaN,NaN,"600 TRAVIS SUITE 5600, HOUSTON TEXAS 77002-100..."
916,19103-7505,NaN,NaN,NaN,"1735 MARKET STREET PHILADELPHIA, PA 19103-7505..."
988,06901-3431,NaN,NaN,NaN,"ONE STAMFORD FORUM, 201 TRESSER BOULEVARD, STA..."

### Filtered 1 - those have only 1 matching zip string and length is not shorter than 5 (assumed correct for now)

In [1798]:
# conditions
match_1_only = ~extracted_Zip_from_address[cols[1:]].any(axis=1) # df.any(axis=1) --> check if value in all cols by row 
zip1_len_smaller_than_5 = extracted_Zip_from_address['Zip1'].str.len() < 5

# filtered data
filtered_1 = extracted_Zip_from_address[match_1_only & (~zip1_len_smaller_than_5)].copy()
print(filtered_1.shape)
filtered_1.sample(20)

(3070, 5)

/Users/catelinn/miniconda3/lib/python3.7/site-packages/IPython/core/displayhook.py:271: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  'Flushing oldest {cull_count} entries.'.format(sz=sz, cull_count=cull_count))

,Zip1,Zip2,Zip3,Zip4,Address
1221,06254,NaN,NaN,NaN,"841 ROUTE 32, UNIT 2, FRANKLIN, CONNECTICUT 06..."
3168,02421,NaN,NaN,NaN,"33 HAYDEN AVENUE LEXINGTON, MASSACHUSETTS 0242..."
1187,20151,NaN,NaN,NaN,"4511 SINGER COURT, SUITE 300, CHANTILLY, VIRGI..."
1436,24018,NaN,NaN,NaN,"3959 ELECTRIC ROAD SW, SUITE 330, ROANOKE, VIR..."
764,04103,NaN,NaN,NaN,"500 RIVERSIDE INDUSTRIAL PARKWAY, PORTLAND ME ..."
2883,91107,NaN,NaN,NaN,"2409 ONEIDA STREET, UNIT A, PASADENA, CA 91107..."
760,06851,NaN,NaN,NaN,"761 MAIN AVENUE BUILDING G, 2ND FLOOR, NORWALK..."
106,90017,NaN,NaN,NaN,"725 S. FIGUEROA STREET, SUITE 350 LOS ANGELES,..."
1989,11794-8480,NaN,NaN,NaN,"SUNY, STONY BROOK, HSC, L4, #060 STONY BROOK, ..."
2330,30328,NaN,NaN,NaN,"5871 GLENRIDGE DRIVE, SUITE 300, ATLANTA, GEOR..."
2051,94025,NaN,NaN,NaN,"1080 MARSH ROAD, MENLO PARK, CA 94025 USA"
3229,77377,NaN,NaN,NaN,"29307 IMPERIAL CREEK DRIVE, TOMBALL, TX 77377,..."
259,46250,NaN,NaN,NaN,"2552 SILVER OAKS DRIVE CARMEL, INDIANA 46250 U..."
3443,48933-1800,NaN,NaN,NaN,"222 NORTH WASHINGTON SQUARE SUITE 400 LANSING,..."
2422,48309,NaN,NaN,NaN,"1993 CHALMERS DRIVE, ROCHESTER HILLS, MICHIGAN..."
993,10103-3198,NaN,NaN,NaN,"666 FIFTH AVENUE, 31ST FLOOR NEW YORK, NEW YOR..."
1441,48084,NaN,NaN,NaN,"2135 WEST MAPLE ROAD TROY, MICHIGAN 48084 USA"
1011,02210,NaN,NaN,NaN,"ONE MARINA PARK DRIVE BOSTON, MA 02210 USA"
37,94103,NaN,NaN,NaN,"239 8TH STREET#11 SAN FRANCISCO, CA 94103 USA"
3413,01752,NaN,NaN,NaN,"181 CEDAR HILL ST. MARLBOROUGH, MA 01752, USA"

In [1799]:
''' save the extracted zips to `US_addresses'''
US_addresses.loc[filtered_1.index, 'Zip']=filtered_1['Zip1']
print(US_addresses.loc[filtered_1.index].shape[0])
US_addresses.loc[filtered_1.index].head()

3070

,ClientID,Address,Zip,Country,City
0,US002562,"ONE BLOSSOM ROAD, ROCHESTER, NY 14610 USA",14610,USA,NaN
1,US002565,"600 NORTH BRAND BLVD., SUITE 230 GLENDALE, CA ...",91203,USA,NaN
2,US002566,C/O R.R. DONNELLEY & SONS COMPANY 111 SOUTH WA...,60606,USA,NaN
3,US002567,"430 CARMEL COURT CANTON, GEORGIA 30114 USA",30114,USA,NaN
4,US002568,"200 SIDNEY STREET SUITE 310 CAMBRIDGE, MASSACH...",02139,USA,NaN

### Filter 2 - those have only 1 matching zip string and length is shorter than 5 (there must be some issues)

In [1800]:
filtered_2 = extracted_Zip_from_address.loc[match_1_only & zip1_len_smaller_than_5].copy()

# inspect the filtered data
for row in filtered_2.iterrows():
  print("index: {} \n".format(row[0]), 
        "Zip: {}\n".format(row[1][0]), 
        "Address: {}".format(row[1][4]),
        "\n")

index: 1085
 Zip: 1760
 Address: INTERNATIONAL TOWER, SUITE 1760 S. FIGUEROA ., LOS ANGELES, CALIFORNIA, U.S.A.

index: 1351
 Zip: 2042
 Address: 810 VERMONT AVENUE N. W., WASHINGTON, D. C. 2042 USA

index: 2263
 Zip: 3465
 Address: 2227 WELBILT BOULEVARD, NEW PORT RICHEY, FLORIDA 3465 USA

index: 2812
 Zip: 0962
 Address: 330 BLAISDELL ROAD ORANGEBURG, NEW YORK 0962, UNITED STATES OF AMERICA

index: 2944
 Zip: 2800
 Address: OFFICE OF TECHNOLOGY TRANSFER & ECONOMIC DEVELOPMENT, 2800 WOODLAWN DRIVE, SUITE 280 HONOLULU, HI, USA

In [1801]:
# Create a dict to store city info with row index as key for the above
dataMap = {1085: ('', 'Los Angeles, CA, USA'),
           1351: ('20420', 'Washington, DC, USA'),
           2263: ('34655', 'NEW PORT RICHEY, FL, USA'),
           2812: ('10962', 'ORANGEBURG, NY, USA'),
           2944: ('', 'HONOLULU, HI, USA')}

In [1802]:
filtered_2_rest_of_str_aft_road_or_unit = (filtered_2.Address[filtered_2.Address.apply(isEnglish)]
                                    .apply(rest_of_str_aft_road_or_unit))
filtered_2_rest_of_str_aft_road_or_unit

1085       S. FIGUEROA ., LOS ANGELES, CALIFORNIA, U.S.A.
1351                           WASHINGTON, D. C. 2042 USA
2263                      W PORT RICHEY, FLORIDA 3465 USA
2812    ORANGEBURG, NEW YORK 0962, UNITED STATES OF AM...
2944                                    HONOLULU, HI, USA
Name: Address, dtype: object

In [1803]:
def make_regex_stateAbbr(state_abbr):
    regex = state_abbr[0] + r"\.?\s*" + state_abbr[1] + r"\.?\s*"
    return regex


regex_state_abbr = make_regex_stateAbbr('DC')
filtered_2_rest_of_str_aft_road_or_unit.str.contains(regex_state_abbr)

1085    False
1351     True
2263    False
2812    False
2944    False
Name: Address, dtype: bool

In [1804]:
# city,\s+ (state | regex_state_abbr)
# if match found, return the reference value (not the matching string in the original value)
def make_df_regex_city_state_with_ref(cities,states, state_abbrs):
    city_state_ref = cities + ', ' + state_abbrs
    regex = (r"(?:" 
            + cities.str.upper() + '[\,\.]?\s+' 
            + states.str.upper() + r"|" 
            + cities.str.upper() + '[\,\.]?\s+' 
            + state_abbrs.apply(make_regex_stateAbbr) + r")")
    return pd.DataFrame({'ref':city_state_ref, 'regex': regex}).drop_duplicates().reset_index()

regex_city_state_with_ref = (make_df_regex_city_state_with_ref(zipcodes['Place Name'], zipcodes['State'], zipcodes['State_Abbr']))
print('Number of regex_city_state_with_ref created: {}'.format(regex_city_state_with_ref.shape[0]))
regex_city_state_with_ref[regex_city_state_with_ref.ref=='Los Angeles, CA']

Number of regex_city_state_with_ref created: 29545

,index,ref,regex
27111,36725,"Los Angeles, CA","(?:LOS ANGELES[\,\.]?\s+CALIFORNIA|LOS ANGELES..."

In [1805]:
def extract_match_of_a_pat(val, pat):
    # matchObject.group(0) to return match if found, None otherwise
    if re.search(str(pat),val):
        #return re.search(str(pat),val).group(0)
        return pat

def extract_match_from_a_patlist(val, patlist):
    if isinstance(patlist,(pd.core.series.Series,np.ndarray)):
        patlist = patlist.tolist()
    try:
        return [patlist.index(x) for x in patlist if extract_match_of_a_pat(val, x)][0]
    except IndexError:
    #if len(matching_pat_idx) == 0:
     #   return None
        return None

#### test of regex used in make_regex_city_state_with_ref ###
#regex_test = r"(?:" + 'LOS ANGELES' + '[\,\.]?\s+' + 'CALIFORNIA' + r"|" + 'LOS ANGELES' + '[\,\.]?\s+' + make_regex_stateAbbr('CA') + r")"
#regex_test2 = r"(?:WASHINGTON[\,\.]?\s+DISTRICT OF COLUMBIA|WASHINGTON[\,\.]?\s+D\.?\s*C\.?\s*)"
#print(regex_city_state_with_ref[0])
#print(regex_test)
#re.search(regex_test, filtered_2_rest_of_str_aft_road_or_unit.loc[1351])


#### test of extract_match_of_a_pat and regex ###
# extract_match_of_a_pat(regex_test,filtered_2_rest_of_str_aft_road_or_unit.loc[1351])
#val = filtered_2_rest_of_str_aft_road_or_unit.loc[1085]
#patlist = [regex_test2, regex_test]
#extract_match_from_a_patlist(val, patlist)

In [1806]:
def extract_match_from_a_pat_df(val, pat_df, ref_col_in_pat_df, pat_col_in_pat_df):
    ls = pat_df[pat_col_in_pat_df].tolist()
    try:
        idx = [ls.index(x) for x in ls if extract_match_of_a_pat(val, x)][0]
    except IndexError:
    #if no match extracted then no idx
        return np.NaN
    return pat_df[ref_col_in_pat_df][idx]

In [1807]:
# test
extract_match_from_a_pat_df('LOS ANGELES, CALIFORNIA', regex_city_state_with_ref, 'ref', 'regex')

'Los Angeles, CA'

In [1808]:
result = filtered_2_rest_of_str_aft_road_or_unit.apply(extract_match_from_a_pat_df, 
                                                args=(regex_city_state_with_ref,'ref', 'regex'))

In [1809]:
'''save the extracted cities to `US_addresses '''
US_addresses.loc[result.index,'City']=result
US_addresses.loc[result.index]

,ClientID,Address,Zip,Country,City
1085,US000161,"INTERNATIONAL TOWER, SUITE 1760 S. FIGUEROA .,...",NaN,USA,"Los Angeles, CA"
1351,US000436,"810 VERMONT AVENUE N. W., WASHINGTON, D. C. 20...",NaN,USA,"Washington, DC"
2263,US001360,"2227 WELBILT BOULEVARD, NEW PORT RICHEY, FLORI...",NaN,USA,"Port Richey, FL"
2812,US001922,"330 BLAISDELL ROAD ORANGEBURG, NEW YORK 0962, ...",NaN,USA,"Orangeburg, NY"
2944,US002057,OFFICE OF TECHNOLOGY TRANSFER & ECONOMIC DEVEL...,NaN,USA,"Honolulu, HI"

In [1810]:
US_addresses.loc[2263,'Zip'] = '34655'

### Filter 3 - those with more than 1 match require further cleaning

In [1811]:
filtered3 = extracted_Zip_from_address[~match_1_only]
print(filtered3.info())
filtered3.sample(20)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 502 entries, 23 to 3636
Data columns (total 5 columns):
Zip1       502 non-null object
Zip2       502 non-null object
Zip3       31 non-null object
Zip4       1 non-null object
Address    502 non-null object
dtypes: object(5)
memory usage: 23.5+ KB
None

,Zip1,Zip2,Zip3,Zip4,Address
929,2200,55402,NaN,NaN,"150 SOUTH FIFTH STREET SUITE 2200 MINNEAPOLIS,..."
351,2160,90067,NaN,NaN,"1801 CENTURY PARK EAST, SUITE 2160 LOS ANGELES..."
2945,1800,28202-5013,NaN,NaN,FIRST CITIZENS BANK PLAZA 128 SOUTH TRYON STRE...
3173,1106,76101,NaN,NaN,"LEGAL DEPARTMENT, MAIL STOP 1106 POST OFFICE B..."
737,2800,60661,NaN,NaN,"500 WEST MADISON STREET, SUITE 2800 CHICAGO, I..."
413,4505,90274,NaN,NaN,"P.O. BOX 4505 PALOS VERDES PENINSULA, CALIFORN..."
2656,1100,63105,NaN,NaN,"7700 FORSYTH BOULEVARD, SUITE 1100, ST. LOUIS,..."
2833,5600,77002-1001,NaN,NaN,"600 TRAVIS SUITE 5600, HOUSTON TEXAS 77002-100..."
782,1007,1596,19899,NaN,"NEMOURS BUILDING, 1007 ORANGE STREET, SUITE 20..."
1512,1100,20006,NaN,NaN,"1625 K STREET, N.W. - SUITE 1100 WASHINGTON, D..."
1552,7660,20892-7660,NaN,NaN,"6011 EXECUTIVE BOULEVARD, SUITE 325, MSC 7660,..."
1760,142950,32614-2950,NaN,NaN,"P.O. BOX 142950, GAINESVILLE, FL 32614-2950 USA"
3437,1400,4208,27609,NaN,"SUITE 1400 4208 SIX FORKS ROAD RALEIGH, NC 276..."
1816,1171,91722,NaN,NaN,"SUITE F, 1171 WEST SAN BERNARDINO ROAD, COVINA..."
3285,1881,80302,NaN,NaN,"CANYON CENTER, 1881 9TH STREET, SUITE 335 BOUL..."
957,1000,77002,NaN,NaN,2000 WELLS FARGO PLAZA 1000 LOUISIANA STREET H...
2116,1010,30309,NaN,NaN,"1720 PEACHTREE STREET, NW SUITE 1010, ATLANTA,..."
2512,1700,84604,NaN,NaN,"34 EAST 1700 SOUTH A-141 PROVO, UTAH 84604 UNI..."
2485,2230,84604,NaN,NaN,"275 WEST 2230 NORTH PROVO, UTAH 84604 USA"
3440,1300,61822,NaN,NaN,"495 COUNTY ROAD 1300 NORTH CHAMPAIGN, ILLINOIS..."

#### Those found with digits in this format '12345-1234' are highly possible to be zips

In [1812]:
for label, col in filtered3[['Zip1', 'Zip2', 'Zip3', 'Zip4']].items():
     filtered3[str(label)+"match"] = col.str.extract(r"(\d{5}-\d{3,})")

filtered3.head()

/Users/catelinn/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Zip1,Zip2,Zip3,Zip4,Address,Zip1match,Zip2match,Zip3match,Zip4match
23,358880,32635-8880,NaN,NaN,"P.O. BOX 358880 GAINESVILLE, FL 32635-8880 USA",NaN,32635-8880,NaN,NaN
35,1926,29304,NaN,NaN,LEGAL DEPARTMENT (M-495) P.O. BOX 1926 SPARTAN...,NaN,NaN,NaN,NaN
45,2100,44114,NaN,NaN,"600 SUPERIOR AVENUE SUITE 2100 CLEVELAND, OH 4...",NaN,NaN,NaN,NaN
58,1500,55402,NaN,NaN,"50 SOUTH SIXTH STREET, SUITE 1500 MINNEAPOLIS,...",NaN,NaN,NaN,NaN
60,2100,75251,NaN,NaN,"12700 PARK CENTRAL DRIVE, #2100 DALLAS, TX 752...",NaN,NaN,NaN,NaN

In [1813]:
cols = ['Zip1match','Zip2match','Zip3match', 'Zip4match']
filtered3_zip_OK = filtered3[filtered3[cols].any(axis=1)]
for col in cols:
    print(col+" {}".format((~filtered3_zip_OK[col].isnull()).sum()))
print("Total: {}".format(filtered3_zip_OK.shape[0]))
filtered3_zip_OK.head()

Zip1match 0
Zip2match 136
Zip3match 12
Zip4match 0
Total: 148

,Zip1,Zip2,Zip3,Zip4,Address,Zip1match,Zip2match,Zip3match,Zip4match
23,358880,32635-8880,NaN,NaN,"P.O. BOX 358880 GAINESVILLE, FL 32635-8880 USA",NaN,32635-8880,NaN,NaN
119,8210,27695-8210,NaN,NaN,"CAMPUS BOX 8210 RALEIGH, NORTH CAROLINA 27695-...",NaN,27695-8210,NaN,NaN
136,3200,19102-2555,NaN,NaN,"TWO LIBERTY PLACE 50 S. 16TH STREET, SUITE 320...",NaN,19102-2555,NaN,NaN
231,3500,60602-4424,NaN,NaN,"70 WEST MADISON – SUITE 3500 CHICAGO, ILLINOIS...",NaN,60602-4424,NaN,NaN
247,4000,55402-1425,NaN,NaN,"200 SOUTH SIXTH STREET, SUITE 4000 MINNEAPOLIS...",NaN,55402-1425,NaN,NaN

In [1814]:
Zip1match_dict = filtered3_zip_OK.loc[filtered3_zip_OK.Zip1match.notna(),'Zip1match'].to_dict()
Zip2match_dict = filtered3_zip_OK.loc[filtered3_zip_OK.Zip2match.notna(),'Zip2match'].to_dict()
Zip3match_dict = filtered3_zip_OK.loc[filtered3_zip_OK.Zip3match.notna(),'Zip3match'].to_dict()
zipMatch_dict = {**Zip1match_dict, **Zip2match_dict, **Zip3match_dict}
zipMatch = pd.Series(zipMatch)
zipMatch.sort_index().head()

23     32635-8880
119    27695-8210
136    19102-2555
231    60602-4424
247    55402-1425
dtype: object

In [1815]:
'''Save the extracted zips from filtered3_zip_OK to US_addresses'''
US_addresses.loc[zipMatch.index,'Zip'] = zipMatch
print(US_addresses.loc[zipMatch.index].shape[0])
US_addresses.loc[zipMatch.index].sort_index().head()

149

,ClientID,Address,Zip,Country,City
23,US002581,"P.O. BOX 358880 GAINESVILLE, FL 32635-8880 USA",32635-8880,USA,NaN
119,US003537,"CAMPUS BOX 8210 RALEIGH, NORTH CAROLINA 27695-...",27695-8210,USA,NaN
136,US002719,"TWO LIBERTY PLACE 50 S. 16TH STREET, SUITE 320...",19102-2555,USA,NaN
231,US002802,"70 WEST MADISON – SUITE 3500 CHICAGO, ILLINOIS...",60602-4424,USA,NaN
247,US002826,"200 SOUTH SIXTH STREET, SUITE 4000 MINNEAPOLIS...",55402-1425,USA,NaN

#### Continue to work on the address with more than 1 zip matches and don't meet zip 10digits format requirement

In [1816]:
filtered3_zip_not_OK = filtered3[~filtered3.index.isin(filtered3_zip_OK.index)]
print(filtered3_zip_not_OK.shape[0])
filtered3_zip_not_OK.head()

354

,Zip1,Zip2,Zip3,Zip4,Address,Zip1match,Zip2match,Zip3match,Zip4match
35,1926,29304,NaN,NaN,LEGAL DEPARTMENT (M-495) P.O. BOX 1926 SPARTAN...,NaN,NaN,NaN,NaN
45,2100,44114,NaN,NaN,"600 SUPERIOR AVENUE SUITE 2100 CLEVELAND, OH 4...",NaN,NaN,NaN,NaN
58,1500,55402,NaN,NaN,"50 SOUTH SIXTH STREET, SUITE 1500 MINNEAPOLIS,...",NaN,NaN,NaN,NaN
60,2100,75251,NaN,NaN,"12700 PARK CENTRAL DRIVE, #2100 DALLAS, TX 752...",NaN,NaN,NaN,NaN
85,1600,77046,NaN,NaN,"24 GREENWAY PLAZA, SUITE 1600, HOUSTON, TX 770...",NaN,NaN,NaN,NaN

In [1817]:
'''regex to capture zip and country(US) in the following order'''
regex = regex_zip + r"\W*" + r"(?P<Country>" + regex_country_EN + r")?" + r"\W*$"

# extract the zip and country that match the above regex
#filtered3_zip_not_OK = filtered3_zip_not_OK.str.extractall(regex)
#print(filtered3_zip_not_OK.info())
#filtered3_zip_not_OK.head()

filtered3_zip_not_OK_extracted = filtered3_zip_not_OK.Address.str.extractall(regex).unstack()
print(filtered3_zip_not_OK_extracted.shape[0])
filtered3_zip_not_OK_extracted.head()

351

         Zip                   Country
match      0                         0
35     29304                       USA
45     44114                       USA
58     55402  UNITED STATES OF AMERICA
60     75251                       USA
85     77046                       USA

In [1818]:
filtered3_zip_not_OK_extracted.columns = ['Zip', 'Country']
filtered3_zip_not_OK_extracted.head()

      Zip                   Country
35  29304                       USA
45  44114                       USA
58  55402  UNITED STATES OF AMERICA
60  75251                       USA
85  77046                       USA

In [1819]:
# verify if country captured is correct
filtered3_zip_not_OK_extracted.loc[filtered3_zip_not_OK_extracted.Country.notna(), 'Country'].value_counts()

USA                         271
UNITED STATES OF AMERICA     33
U.S.A                        28
US                            3
UNITED STATES                 2
UNITED STATES OF AMRICA       1
Name: Country, dtype: int64

In [1820]:
'''assume those with matching country(US) found following zip are done, save to US_addresses (review later)'''
more_than_1match_zip_followed_by_country_idx = filtered3_zip_not_OK_extracted[filtered3_zip_not_OK_extracted.Country.notna()].index
US_addresses.loc[more_than_1match_zip_followed_by_country_idx,'Zip'] = (
clean_zip_cols(filtered3_zip_not_OK_extracted.loc[more_than_1match_zip_followed_by_country_idx,'Zip']))

print(US_addresses.loc[more_than_1match_zip_followed_by_country_idx.shape[0]])
US_addresses.loc[more_than_1match_zip_followed_by_country_idx].head()

ClientID                                   US002964
Address     ROCKWALL TEXAS UNITED STATES OF AMERICA
Zip                                             NaN
Country                                         USA
City                                 ROCKWALL TEXAS
Name: 338, dtype: object

,ClientID,Address,Zip,Country,City
35,US002678,LEGAL DEPARTMENT (M-495) P.O. BOX 1926 SPARTAN...,29304,USA,NaN
45,US003426,"600 SUPERIOR AVENUE SUITE 2100 CLEVELAND, OH 4...",44114,USA,NaN
58,US002905,"50 SOUTH SIXTH STREET, SUITE 1500 MINNEAPOLIS,...",55402,USA,NaN
60,US002907,"12700 PARK CENTRAL DRIVE, #2100 DALLAS, TX 752...",75251,USA,NaN
85,US003459,"24 GREENWAY PLAZA, SUITE 1600, HOUSTON, TX 770...",77046,USA,NaN

In [1821]:
''' Review those without matching country(US) '''
#more_than_1match_zip_followed_by_NO_country = US_addresses[filtered3_zip_not_OK_extracted.Country.isnull()]
#more_than_1match_zip_followed_by_NO_country

more_than_1match_zip_followed_by_NO_country_idx = (
    filtered3_zip_not_OK_extracted[filtered3_zip_not_OK_extracted.Country.isnull()].index)

US_addresses.loc[more_than_1match_zip_followed_by_NO_country_idx,'Address'].tolist()

['150 N MICHIGAN AVE | SUITE 2700 | CHICAGO, ILLINOIS 60601',
 '600 BANNER PLACE TOWER 12770 COIT ROAD DALLAS, TEXAS 75251',
 '10250 CONSTELLATION BLVD. SUITE 1700 LOS ANGELES, CA 90067',
 '2603 AUGUSTA DRIVE SUITE 1270 HOUSTON, TX 77057',
 '100 EAST WISCONSIN AVENUE, SUITE 1100 MILWAUKEE, WI 53202',
 '6400 SOUTH FIDDLERS GREEN CIRCLE SUITE 1610 GREENWOOD VILLAGE,CO 80111',
 'THREE EMBARCADERO CENTER,SUITE 1350 SAN FRANCISCO, CA 94111',
 '222 SOUTH MAIN STREET, SUITE 2200 SALT LAKE CITY, UTAH 84101',
 '1875 EYE STREET NW, SUITE 1200 WASHINGTON, DC 20006',
 '4 PENN CENTER, 1600 JFK BLVD., 2ND FLOOR, PHILADELPHIA, PA 19103',
 '1170 PEACHTREE STREET NE, SUITE 1200, ATLANTA, GEORGIA, USA, 300309',
 '999 PEACHTREE STREET NE SUITE 1300 ATLANTA, GEORGIA 30309',
 '701 FIFTH AVENUE, SUITE 4800-SEATTLE, WASHINGTON 98104']

In [1822]:
filtered3_zip_not_OK_extracted.loc[more_than_1match_zip_followed_by_NO_country_idx,'Zip']

162      60601
221      75251
234      90067
421      77057
429      53202
560      80111
576      94111
595      84101
757      20006
867      19103
2604    300309
3441     30309
3636     98104
Name: Zip, dtype: object

In [1823]:
filtered3_zip_not_OK_extracted.loc[2604, 'Zip']='30309'
filtered3_zip_not_OK_extracted.loc[more_than_1match_zip_followed_by_NO_country_idx,'Zip']

162     60601
221     75251
234     90067
421     77057
429     53202
560     80111
576     94111
595     84101
757     20006
867     19103
2604    30309
3441    30309
3636    98104
Name: Zip, dtype: object

In [1824]:
# Save the above extracted zips to US_addresses
US_addresses.loc[more_than_1match_zip_followed_by_NO_country_idx,'Zip'] = (
    filtered3_zip_not_OK_extracted.loc[more_than_1match_zip_followed_by_NO_country_idx,'Zip'])
US_addresses.loc[more_than_1match_zip_followed_by_NO_country_idx]

,ClientID,Address,Zip,Country,City
162,US002755,"150 N MICHIGAN AVE | SUITE 2700 | CHICAGO, ILL...",60601,USA,NaN
221,US002801,"600 BANNER PLACE TOWER 12770 COIT ROAD DALLAS,...",75251,USA,NaN
234,US002807,10250 CONSTELLATION BLVD. SUITE 1700 LOS ANGEL...,90067,USA,NaN
421,US003601,"2603 AUGUSTA DRIVE SUITE 1270 HOUSTON, TX 77057",77057,USA,NaN
429,US003614,"100 EAST WISCONSIN AVENUE, SUITE 1100 MILWAUKE...",53202,USA,NaN
560,US002944,6400 SOUTH FIDDLERS GREEN CIRCLE SUITE 1610 GR...,80111,USA,NaN
576,US002937,"THREE EMBARCADERO CENTER,SUITE 1350 SAN FRANCI...",94111,USA,NaN
595,US003491,"222 SOUTH MAIN STREET, SUITE 2200 SALT LAKE CI...",84101,USA,NaN
757,US002758,"1875 EYE STREET NW, SUITE 1200 WASHINGTON, DC ...",20006,USA,NaN
867,US002875,"4 PENN CENTER, 1600 JFK BLVD., 2ND FLOOR, PHIL...",19103,USA,NaN
2604,US001706,"1170 PEACHTREE STREET NE, SUITE 1200, ATLANTA,...",30309,USA,NaN
3441,US003580,"999 PEACHTREE STREET NE SUITE 1300 ATLANTA, GE...",30309,USA,NaN
3636,US003560,"701 FIFTH AVENUE, SUITE 4800-SEATTLE, WASHINGT...",98104,USA,NaN

### Review those without matching zip and city info

In [1825]:
 US_addresses[US_addresses.Zip.isnull() & US_addresses.City.isnull()]

,ClientID,Address,Zip,Country,City
664,US003161,"US 08648 NJ LAWRENCEVILLE, 1009 LENOX DRIVE, S...",NaN,USA,NaN
3454,US003324,"9701 SE JOHNSON CREEK BOULEVARD, APT. 1306 970...",NaN,USA,NaN

In [1826]:
US_addresses[US_addresses.Zip.isnull() & US_addresses.City.isnull()].Address.tolist()

['US 08648 NJ LAWRENCEVILLE, 1009 LENOX DRIVE, SUITE 106 PRINCETON PIKE CORPORATE CENTER USA',
 '9701 SE JOHNSON CREEK BOULEVARD, APT. 1306 97086 HAPPYVALLEY OREGON UNITED STATES OF AMERICA']

In [1827]:
US_addresses.loc[[664, 2316, 2374, 3454], 'Zip'] = ['08648', '95124-3400', '20814','97086']
US_addresses[US_addresses.Zip.isnull() & US_addresses.City.isnull()]

Empty DataFrame
Columns: [ClientID, Address, Zip, Country, City]
Index: []

## Review of `US_addresses`

In [1828]:
'''Examine the dataframe'''
US_addresses.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3622 entries, 0 to 3639
Data columns (total 5 columns):
ClientID    3622 non-null object
Address     3622 non-null object
Zip         3574 non-null object
Country     3622 non-null object
City        50 non-null object
dtypes: object(5)
memory usage: 329.8+ KB

In [1829]:
print("Number of addresses without zip: {}".format(US_addresses.loc[US_addresses.Zip.isna()].shape[0]))
US_addresses.loc[US_addresses.Zip.isna()].head()

Number of addresses without zip: 48

,ClientID,Address,Zip,Country,City
72,US002913,"333 CENTENNIAL PARKWAY SUITE B LOUISVILLE, CO USA",NaN,USA,"LOUISVILLE, CO"
168,US002740,"1909 K STREET NW, SUITE 900, USA",NaN,USA,
238,US002809,"LAGUNA NIGUEL, CA USA",NaN,USA,"LAGUNA NIGUEL, CA"
239,US002810,"LAGUNA HILLS, CA USA",NaN,USA,"LAGUNA HILLS, CA"
283,US003046,DELAWARE USA,NaN,USA,DELAWARE

In [1830]:
print("Number of addresses with City: {}".format(US_addresses.loc[US_addresses.City.notna()].shape[0]))
US_addresses.loc[US_addresses.City.notna()].head()

Number of addresses with City: 50

,ClientID,Address,Zip,Country,City
72,US002913,"333 CENTENNIAL PARKWAY SUITE B LOUISVILLE, CO USA",NaN,USA,"LOUISVILLE, CO"
168,US002740,"1909 K STREET NW, SUITE 900, USA",NaN,USA,
238,US002809,"LAGUNA NIGUEL, CA USA",NaN,USA,"LAGUNA NIGUEL, CA"
239,US002810,"LAGUNA HILLS, CA USA",NaN,USA,"LAGUNA HILLS, CA"
283,US003046,DELAWARE USA,NaN,USA,DELAWARE

In [1831]:
print("Number of addresses without city: {}".format(US_addresses.loc[US_addresses.City.isna()].shape[0]))
US_addresses.loc[US_addresses.City.isna()].head()

Number of addresses without city: 3572

,ClientID,Address,Zip,Country,City
0,US002562,"ONE BLOSSOM ROAD, ROCHESTER, NY 14610 USA",14610,USA,NaN
1,US002565,"600 NORTH BRAND BLVD., SUITE 230 GLENDALE, CA ...",91203,USA,NaN
2,US002566,C/O R.R. DONNELLEY & SONS COMPANY 111 SOUTH WA...,60606,USA,NaN
3,US002567,"430 CARMEL COURT CANTON, GEORGIA 30114 USA",30114,USA,NaN
4,US002568,"200 SIDNEY STREET SUITE 310 CAMBRIDGE, MASSACH...",02139,USA,NaN

In [1832]:
'''Fix the pending issues with city data''' 

US_addresses.loc[US_addresses.City.notna(),'City'].value_counts()

DELAWARE                                              3
ROCKWALL TEXAS                                        2
CAMARILLO, CALIFORNIA                                 2
NEW PORT, CA                                          2
LAGUNA HILLS, CA                                      1
PRINCETON, NJ                                         1
W JERSEY                                              1
LAGUNA NIGUEL, CA                                     1
IN                                                    1
PORT WASHINGTON,NY                                    1
CAMBRIDGE, MASSACHUSETTS                              1
TROY, MICHIGAN                                        1
NORWALK, CONNECTICUT                                  1
WASHINGTON, DISTRICT OF COLUMBIA                      1
LOS ANGELES, CALIFORNIA                               1
NORTH CAROLINA                                        1
CIRCLE PINES, MN                                      1
MIAMI                                                 1
LOUISVILLE, CO                                        1
BURNSVILLE, MN                                        1
Honolulu, HI                                          1
BOSTON, MA                                            1
AUSTIN TEXAS                                          1
Orangeburg, NY                                        1
TEXAS                                                 1
PLYMOUTH, MN                                          1
SOUTHLAKE, TX                                         1
Port Richey, FL                                       1
Washington, DC                                        1
SCHAUMBURG, ILLINOIS                                  1
DANVILLE                                              1
CITY OF WILMINGTON, COUNTY OF NEW CASTLE, DELAWARE    1
CHASKA, MINNESOTA                                     1
WILMINGTON, DELAWARE                                  1
CALIFORNIA                                            1
RALEIGH, NORTH CAROLINA                               1
SPRINGFIELD, ILLINOIS                                 1
Los Angeles, CA                                       1
SAN DIEGO                                             1
PACIFIC PALISADES, CALIFORNIA                         1
BEAVERTON, OREGON                                     1
FREMONT, CA                                           1
VIRGINIA BEACH, VA                                    1
SALINE, MICHIGAN                                      1
                                                      1
Name: City, dtype: int64

In [1833]:
# Fix the one containing county
check = US_addresses.loc[US_addresses.City.notna(), 'City'].str.upper().str.contains('COUNTY')
US_addresses.loc[US_addresses.City.notna() & check, 'City'].tolist()

['CITY OF WILMINGTON, COUNTY OF NEW CASTLE, DELAWARE']

In [1834]:
US_addresses.loc[US_addresses.City.notna() & check, 'City'] = 'WILMINGTON, DE'
US_addresses.loc[US_addresses.City.notna() & check, 'City']

2224    WILMINGTON, DE
Name: City, dtype: object

In [1835]:
US_addresses.loc[168,'City'] = 'Washington, DC'
US_addresses.loc[168,'Zip'] = '20006'

In [1836]:
'''replace all full state name to state abbrv'''

states_in_city = US_addresses.loc[US_addresses.City.notna(),'City'].str.extract(r'\b(\w+)$')
cities_to_fix = US_addresses.loc[states_in_city[states_in_city[0].str.len()>2].index,'City']
cities_to_fix

283                             DELAWARE
336                       NORTH CAROLINA
337                       ROCKWALL TEXAS
338                       ROCKWALL TEXAS
396              RALEIGH, NORTH CAROLINA
399                       TROY, MICHIGAN
474                CAMARILLO, CALIFORNIA
520                            SAN DIEGO
613                                TEXAS
763                 WILMINGTON, DELAWARE
892                CAMARILLO, CALIFORNIA
974                             DANVILLE
1288                            DELAWARE
1895                NORWALK, CONNECTICUT
2234    WASHINGTON, DISTRICT OF COLUMBIA
2306                    SALINE, MICHIGAN
2447               SPRINGFIELD, ILLINOIS
2709            CAMBRIDGE, MASSACHUSETTS
2887                   BEAVERTON, OREGON
2888                SCHAUMBURG, ILLINOIS
2981                               MIAMI
2993                            DELAWARE
3179                        AUSTIN TEXAS
3368                            W JERSEY
3411                   CHASKA, MINNESOTA
3448                          CALIFORNIA
3515       PACIFIC PALISADES, CALIFORNIA
3516             LOS ANGELES, CALIFORNIA
Name: City, dtype: object

In [1837]:
# re.compile the regex to store as a dictionary key
# https://stackoverflow.com/questions/33343680/can-a-regular-expression-be-used-as-a-key-in-a-dictionary
compiled_regex_city = [re.compile(str(x)) for x in regex_city_state_with_ref.regex]
regex_city_dict = dict(zip(compiled_regex_city, regex_city_state_with_ref.ref.str.upper()))
regex_city_dict

{re.compile(r'(?:HOLTSVILLE[\,\.]?\s+NEW YORK|HOLTSVILLE[\,\.]?\s+N\.?\s*Y\.?\s*)',
 re.UNICODE): 'HOLTSVILLE, NY',
 re.compile(r'(?:AGAWAM[\,\.]?\s+MASSACHUSETTS|AGAWAM[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'AGAWAM, MA',
 re.compile(r'(?:AMHERST[\,\.]?\s+MASSACHUSETTS|AMHERST[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'AMHERST, MA',
 re.compile(r'(?:BARRE[\,\.]?\s+MASSACHUSETTS|BARRE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BARRE, MA',
 re.compile(r'(?:BELCHERTOWN[\,\.]?\s+MASSACHUSETTS|BELCHERTOWN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BELCHERTOWN, MA',
 re.compile(r'(?:BLANDFORD[\,\.]?\s+MASSACHUSETTS|BLANDFORD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BLANDFORD, MA',
 re.compile(r'(?:BONDSVILLE[\,\.]?\s+MASSACHUSETTS|BONDSVILLE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BONDSVILLE, MA',
 re.compile(r'(?:BRIMFIELD[\,\.]?\s+MASSACHUSETTS|BRIMFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BRIMFIELD, MA',
 re.compile(r'(?:CHESTER[\,\.]?\s+MASSACHUSETTS|CHESTER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CHESTER, MA',
 re.compile(r'(?:CHESTERFIELD[\,\.]?\s+MASSACHUSETTS|CHESTERFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CHESTERFIELD, MA',
 re.compile(r'(?:CHICOPEE[\,\.]?\s+MASSACHUSETTS|CHICOPEE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CHICOPEE, MA',
 re.compile(r'(?:CUMMINGTON[\,\.]?\s+MASSACHUSETTS|CUMMINGTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CUMMINGTON, MA',
 re.compile(r'(?:EASTHAMPTON[\,\.]?\s+MASSACHUSETTS|EASTHAMPTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'EASTHAMPTON, MA',
 re.compile(r'(?:EAST LONGMEADOW[\,\.]?\s+MASSACHUSETTS|EAST LONGMEADOW[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'EAST LONGMEADOW, MA',
 re.compile(r'(?:EAST OTIS[\,\.]?\s+MASSACHUSETTS|EAST OTIS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'EAST OTIS, MA',
 re.compile(r'(?:FEEDING HILLS[\,\.]?\s+MASSACHUSETTS|FEEDING HILLS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'FEEDING HILLS, MA',
 re.compile(r'(?:GILBERTVILLE[\,\.]?\s+MASSACHUSETTS|GILBERTVILLE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GILBERTVILLE, MA',
 re.compile(r'(?:GOSHEN[\,\.]?\s+MASSACHUSETTS|GOSHEN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GOSHEN, MA',
 re.compile(r'(?:GRANBY[\,\.]?\s+MASSACHUSETTS|GRANBY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GRANBY, MA',
 re.compile(r'(?:GRANVILLE[\,\.]?\s+MASSACHUSETTS|GRANVILLE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GRANVILLE, MA',
 re.compile(r'(?:HADLEY[\,\.]?\s+MASSACHUSETTS|HADLEY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HADLEY, MA',
 re.compile(r'(?:HAMPDEN[\,\.]?\s+MASSACHUSETTS|HAMPDEN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HAMPDEN, MA',
 re.compile(r'(?:HARDWICK[\,\.]?\s+MASSACHUSETTS|HARDWICK[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HARDWICK, MA',
 re.compile(r'(?:HATFIELD[\,\.]?\s+MASSACHUSETTS|HATFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HATFIELD, MA',
 re.compile(r'(?:HAYDENVILLE[\,\.]?\s+MASSACHUSETTS|HAYDENVILLE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HAYDENVILLE, MA',
 re.compile(r'(?:HOLYOKE[\,\.]?\s+MASSACHUSETTS|HOLYOKE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HOLYOKE, MA',
 re.compile(r'(?:HUNTINGTON[\,\.]?\s+MASSACHUSETTS|HUNTINGTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HUNTINGTON, MA',
 re.compile(r'(?:LEEDS[\,\.]?\s+MASSACHUSETTS|LEEDS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LEEDS, MA',
 re.compile(r'(?:LEVERETT[\,\.]?\s+MASSACHUSETTS|LEVERETT[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LEVERETT, MA',
 re.compile(r'(?:LUDLOW[\,\.]?\s+MASSACHUSETTS|LUDLOW[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LUDLOW, MA',
 re.compile(r'(?:MONSON[\,\.]?\s+MASSACHUSETTS|MONSON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'MONSON, MA',
 re.compile(r'(?:NORTH AMHERST[\,\.]?\s+MASSACHUSETTS|NORTH AMHERST[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'NORTH AMHERST, MA',
 re.compile(r'(?:NORTHAMPTON[\,\.]?\s+MASSACHUSETTS|NORTHAMPTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'NORTHAMPTON, MA',
 re.compile(r'(?:FLORENCE[\,\.]?\s+MASSACHUSETTS|FLORENCE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'FLORENCE, MA',
 re.compile(r'(?:NORTH HATFIELD[\,\.]?\s+MASSACHUSETTS|NORTH HATFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'NORTH HATFIELD, MA',
 re.compile(r'(?:OAKHAM[\,\.]?\s+MASSACHUSETTS|OAKHAM[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'OAKHAM, MA',
 re.compile(r'(?:PALMER[\,\.]?\s+MASSACHUSETTS|PALMER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'PALMER, MA',
 re.compile(r'(?:PLAINFIELD[\,\.]?\s+MASSACHUSETTS|PLAINFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'PLAINFIELD, MA',
 re.compile(r'(?:RUSSELL[\,\.]?\s+MASSACHUSETTS|RUSSELL[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'RUSSELL, MA',
 re.compile(r'(?:SHUTESBURY[\,\.]?\s+MASSACHUSETTS|SHUTESBURY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SHUTESBURY, MA',
 re.compile(r'(?:SOUTHAMPTON[\,\.]?\s+MASSACHUSETTS|SOUTHAMPTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SOUTHAMPTON, MA',
 re.compile(r'(?:SOUTH BARRE[\,\.]?\s+MASSACHUSETTS|SOUTH BARRE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SOUTH BARRE, MA',
 re.compile(r'(?:SOUTH HADLEY[\,\.]?\s+MASSACHUSETTS|SOUTH HADLEY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SOUTH HADLEY, MA',
 re.compile(r'(?:SOUTHWICK[\,\.]?\s+MASSACHUSETTS|SOUTHWICK[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SOUTHWICK, MA',
 re.compile(r'(?:THORNDIKE[\,\.]?\s+MASSACHUSETTS|THORNDIKE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'THORNDIKE, MA',
 re.compile(r'(?:THREE RIVERS[\,\.]?\s+MASSACHUSETTS|THREE RIVERS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'THREE RIVERS, MA',
 re.compile(r'(?:WALES[\,\.]?\s+MASSACHUSETTS|WALES[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WALES, MA',
 re.compile(r'(?:WARE[\,\.]?\s+MASSACHUSETTS|WARE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WARE, MA',
 re.compile(r'(?:WARREN[\,\.]?\s+MASSACHUSETTS|WARREN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WARREN, MA',
 re.compile(r'(?:WEST CHESTERFIELD[\,\.]?\s+MASSACHUSETTS|WEST CHESTERFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WEST CHESTERFIELD, MA',
 re.compile(r'(?:WESTFIELD[\,\.]?\s+MASSACHUSETTS|WESTFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WESTFIELD, MA',
 re.compile(r'(?:WEST HATFIELD[\,\.]?\s+MASSACHUSETTS|WEST HATFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WEST HATFIELD, MA',
 re.compile(r'(?:WEST SPRINGFIELD[\,\.]?\s+MASSACHUSETTS|WEST SPRINGFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WEST SPRINGFIELD, MA',
 re.compile(r'(?:WEST WARREN[\,\.]?\s+MASSACHUSETTS|WEST WARREN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WEST WARREN, MA',
 re.compile(r'(?:WHATELY[\,\.]?\s+MASSACHUSETTS|WHATELY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WHATELY, MA',
 re.compile(r'(?:WHEELWRIGHT[\,\.]?\s+MASSACHUSETTS|WHEELWRIGHT[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WHEELWRIGHT, MA',
 re.compile(r'(?:WILBRAHAM[\,\.]?\s+MASSACHUSETTS|WILBRAHAM[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WILBRAHAM, MA',
 re.compile(r'(?:WILLIAMSBURG[\,\.]?\s+MASSACHUSETTS|WILLIAMSBURG[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WILLIAMSBURG, MA',
 re.compile(r'(?:WORONOCO[\,\.]?\s+MASSACHUSETTS|WORONOCO[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WORONOCO, MA',
 re.compile(r'(?:WORTHINGTON[\,\.]?\s+MASSACHUSETTS|WORTHINGTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WORTHINGTON, MA',
 re.compile(r'(?:SPRINGFIELD[\,\.]?\s+MASSACHUSETTS|SPRINGFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SPRINGFIELD, MA',
 re.compile(r'(?:LONGMEADOW[\,\.]?\s+MASSACHUSETTS|LONGMEADOW[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LONGMEADOW, MA',
 re.compile(r'(?:INDIAN ORCHARD[\,\.]?\s+MASSACHUSETTS|INDIAN ORCHARD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'INDIAN ORCHARD, MA',
 re.compile(r'(?:PITTSFIELD[\,\.]?\s+MASSACHUSETTS|PITTSFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'PITTSFIELD, MA',
 re.compile(r'(?:ADAMS[\,\.]?\s+MASSACHUSETTS|ADAMS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ADAMS, MA',
 re.compile(r'(?:ASHLEY FALLS[\,\.]?\s+MASSACHUSETTS|ASHLEY FALLS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ASHLEY FALLS, MA',
 re.compile(r'(?:BECKET[\,\.]?\s+MASSACHUSETTS|BECKET[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BECKET, MA',
 re.compile(r'(?:BERKSHIRE[\,\.]?\s+MASSACHUSETTS|BERKSHIRE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BERKSHIRE, MA',
 re.compile(r'(?:CHESHIRE[\,\.]?\s+MASSACHUSETTS|CHESHIRE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CHESHIRE, MA',
 re.compile(r'(?:DALTON[\,\.]?\s+MASSACHUSETTS|DALTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'DALTON, MA',
 re.compile(r'(?:GLENDALE[\,\.]?\s+MASSACHUSETTS|GLENDALE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GLENDALE, MA',
 re.compile(r'(?:GREAT BARRINGTON[\,\.]?\s+MASSACHUSETTS|GREAT BARRINGTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GREAT BARRINGTON, MA',
 re.compile(r'(?:HINSDALE[\,\.]?\s+MASSACHUSETTS|HINSDALE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HINSDALE, MA',
 re.compile(r'(?:HOUSATONIC[\,\.]?\s+MASSACHUSETTS|HOUSATONIC[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HOUSATONIC, MA',
 re.compile(r'(?:LANESBOROUGH[\,\.]?\s+MASSACHUSETTS|LANESBOROUGH[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LANESBOROUGH, MA',
 re.compile(r'(?:LEE[\,\.]?\s+MASSACHUSETTS|LEE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LEE, MA',
 re.compile(r'(?:LENOX[\,\.]?\s+MASSACHUSETTS|LENOX[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LENOX, MA',
 re.compile(r'(?:LENOX DALE[\,\.]?\s+MASSACHUSETTS|LENOX DALE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LENOX DALE, MA',
 re.compile(r'(?:MIDDLEFIELD[\,\.]?\s+MASSACHUSETTS|MIDDLEFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'MIDDLEFIELD, MA',
 re.compile(r'(?:MILL RIVER[\,\.]?\s+MASSACHUSETTS|MILL RIVER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'MILL RIVER, MA',
 re.compile(r'(?:MONTEREY[\,\.]?\s+MASSACHUSETTS|MONTEREY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'MONTEREY, MA',
 re.compile(r'(?:NORTH ADAMS[\,\.]?\s+MASSACHUSETTS|NORTH ADAMS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'NORTH ADAMS, MA',
 re.compile(r'(?:NORTH EGREMONT[\,\.]?\s+MASSACHUSETTS|NORTH EGREMONT[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'NORTH EGREMONT, MA',
 re.compile(r'(?:OTIS[\,\.]?\s+MASSACHUSETTS|OTIS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'OTIS, MA',
 re.compile(r'(?:RICHMOND[\,\.]?\s+MASSACHUSETTS|RICHMOND[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'RICHMOND, MA',
 re.compile(r'(?:SANDISFIELD[\,\.]?\s+MASSACHUSETTS|SANDISFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SANDISFIELD, MA',
 re.compile(r'(?:SAVOY[\,\.]?\s+MASSACHUSETTS|SAVOY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SAVOY, MA',
 re.compile(r'(?:SHEFFIELD[\,\.]?\s+MASSACHUSETTS|SHEFFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SHEFFIELD, MA',
 re.compile(r'(?:SOUTH EGREMONT[\,\.]?\s+MASSACHUSETTS|SOUTH EGREMONT[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SOUTH EGREMONT, MA',
 re.compile(r'(?:SOUTHFIELD[\,\.]?\s+MASSACHUSETTS|SOUTHFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SOUTHFIELD, MA',
 re.compile(r'(?:SOUTH LEE[\,\.]?\s+MASSACHUSETTS|SOUTH LEE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SOUTH LEE, MA',
 re.compile(r'(?:STOCKBRIDGE[\,\.]?\s+MASSACHUSETTS|STOCKBRIDGE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'STOCKBRIDGE, MA',
 re.compile(r'(?:TYRINGHAM[\,\.]?\s+MASSACHUSETTS|TYRINGHAM[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'TYRINGHAM, MA',
 re.compile(r'(?:WEST STOCKBRIDGE[\,\.]?\s+MASSACHUSETTS|WEST STOCKBRIDGE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WEST STOCKBRIDGE, MA',
 re.compile(r'(?:WILLIAMSTOWN[\,\.]?\s+MASSACHUSETTS|WILLIAMSTOWN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WILLIAMSTOWN, MA',
 re.compile(r'(?:WINDSOR[\,\.]?\s+MASSACHUSETTS|WINDSOR[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WINDSOR, MA',
 re.compile(r'(?:GREENFIELD[\,\.]?\s+MASSACHUSETTS|GREENFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GREENFIELD, MA',
 re.compile(r'(?:ASHFIELD[\,\.]?\s+MASSACHUSETTS|ASHFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ASHFIELD, MA',
 re.compile(r'(?:ATHOL[\,\.]?\s+MASSACHUSETTS|ATHOL[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ATHOL, MA',
 re.compile(r'(?:BERNARDSTON[\,\.]?\s+MASSACHUSETTS|BERNARDSTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BERNARDSTON, MA',
 re.compile(r'(?:BUCKLAND[\,\.]?\s+MASSACHUSETTS|BUCKLAND[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BUCKLAND, MA',
 re.compile(r'(?:CHARLEMONT[\,\.]?\s+MASSACHUSETTS|CHARLEMONT[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CHARLEMONT, MA',
 re.compile(r'(?:COLRAIN[\,\.]?\s+MASSACHUSETTS|COLRAIN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'COLRAIN, MA',
 re.compile(r'(?:CONWAY[\,\.]?\s+MASSACHUSETTS|CONWAY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CONWAY, MA',
 re.compile(r'(?:DEERFIELD[\,\.]?\s+MASSACHUSETTS|DEERFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'DEERFIELD, MA',
 re.compile(r'(?:DRURY[\,\.]?\s+MASSACHUSETTS|DRURY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'DRURY, MA',
 re.compile(r'(?:ERVING[\,\.]?\s+MASSACHUSETTS|ERVING[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ERVING, MA',
 re.compile(r'(?:HEATH[\,\.]?\s+MASSACHUSETTS|HEATH[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HEATH, MA',
 re.compile(r'(?:LAKE PLEASANT[\,\.]?\s+MASSACHUSETTS|LAKE PLEASANT[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LAKE PLEASANT, MA',
 re.compile(r'(?:MILLERS FALLS[\,\.]?\s+MASSACHUSETTS|MILLERS FALLS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'MILLERS FALLS, MA',
 re.compile(r'(?:MONROE BRIDGE[\,\.]?\s+MASSACHUSETTS|MONROE BRIDGE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'MONROE BRIDGE, MA',
 re.compile(r'(?:MONTAGUE[\,\.]?\s+MASSACHUSETTS|MONTAGUE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'MONTAGUE, MA',
 re.compile(r'(?:GILL[\,\.]?\s+MASSACHUSETTS|GILL[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GILL, MA',
 re.compile(r'(?:NEW SALEM[\,\.]?\s+MASSACHUSETTS|NEW SALEM[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'NEW SALEM, MA',
 re.compile(r'(?:NORTHFIELD[\,\.]?\s+MASSACHUSETTS|NORTHFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'NORTHFIELD, MA',
 re.compile(r'(?:ORANGE[\,\.]?\s+MASSACHUSETTS|ORANGE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ORANGE, MA',
 re.compile(r'(?:PETERSHAM[\,\.]?\s+MASSACHUSETTS|PETERSHAM[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'PETERSHAM, MA',
 re.compile(r'(?:ROWE[\,\.]?\s+MASSACHUSETTS|ROWE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ROWE, MA',
 re.compile(r'(?:ROYALSTON[\,\.]?\s+MASSACHUSETTS|ROYALSTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ROYALSTON, MA',
 re.compile(r'(?:SHELBURNE FALLS[\,\.]?\s+MASSACHUSETTS|SHELBURNE FALLS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SHELBURNE FALLS, MA',
 re.compile(r'(?:SOUTH DEERFIELD[\,\.]?\s+MASSACHUSETTS|SOUTH DEERFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SOUTH DEERFIELD, MA',
 re.compile(r'(?:SUNDERLAND[\,\.]?\s+MASSACHUSETTS|SUNDERLAND[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SUNDERLAND, MA',
 re.compile(r'(?:TURNERS FALLS[\,\.]?\s+MASSACHUSETTS|TURNERS FALLS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'TURNERS FALLS, MA',
 re.compile(r'(?:WARWICK[\,\.]?\s+MASSACHUSETTS|WARWICK[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WARWICK, MA',
 re.compile(r'(?:WENDELL[\,\.]?\s+MASSACHUSETTS|WENDELL[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WENDELL, MA',
 re.compile(r'(?:WENDELL DEPOT[\,\.]?\s+MASSACHUSETTS|WENDELL DEPOT[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WENDELL DEPOT, MA',
 re.compile(r'(?:FITCHBURG[\,\.]?\s+MASSACHUSETTS|FITCHBURG[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'FITCHBURG, MA',
 re.compile(r'(?:ASHBURNHAM[\,\.]?\s+MASSACHUSETTS|ASHBURNHAM[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ASHBURNHAM, MA',
 re.compile(r'(?:ASHBY[\,\.]?\s+MASSACHUSETTS|ASHBY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'ASHBY, MA',
 re.compile(r'(?:AYER[\,\.]?\s+MASSACHUSETTS|AYER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'AYER, MA',
 re.compile(r'(?:DEVENS[\,\.]?\s+MASSACHUSETTS|DEVENS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'DEVENS, MA',
 re.compile(r'(?:BALDWINVILLE[\,\.]?\s+MASSACHUSETTS|BALDWINVILLE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BALDWINVILLE, MA',
 re.compile(r'(?:EAST TEMPLETON[\,\.]?\s+MASSACHUSETTS|EAST TEMPLETON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'EAST TEMPLETON, MA',
 re.compile(r'(?:GARDNER[\,\.]?\s+MASSACHUSETTS|GARDNER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GARDNER, MA',
 re.compile(r'(?:WESTMINSTER[\,\.]?\s+MASSACHUSETTS|WESTMINSTER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WESTMINSTER, MA',
 re.compile(r'(?:GROTON[\,\.]?\s+MASSACHUSETTS|GROTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GROTON, MA',
 re.compile(r'(?:HARVARD[\,\.]?\s+MASSACHUSETTS|HARVARD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HARVARD, MA',
 re.compile(r'(?:HUBBARDSTON[\,\.]?\s+MASSACHUSETTS|HUBBARDSTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HUBBARDSTON, MA',
 re.compile(r'(?:LEOMINSTER[\,\.]?\s+MASSACHUSETTS|LEOMINSTER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LEOMINSTER, MA',
 re.compile(r'(?:LITTLETON[\,\.]?\s+MASSACHUSETTS|LITTLETON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LITTLETON, MA',
 re.compile(r'(?:LUNENBURG[\,\.]?\s+MASSACHUSETTS|LUNENBURG[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LUNENBURG, MA',
 re.compile(r'(?:PEPPERELL[\,\.]?\s+MASSACHUSETTS|PEPPERELL[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'PEPPERELL, MA',
 re.compile(r'(?:SHIRLEY[\,\.]?\s+MASSACHUSETTS|SHIRLEY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'SHIRLEY, MA',
 re.compile(r'(?:STILL RIVER[\,\.]?\s+MASSACHUSETTS|STILL RIVER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'STILL RIVER, MA',
 re.compile(r'(?:TEMPLETON[\,\.]?\s+MASSACHUSETTS|TEMPLETON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'TEMPLETON, MA',
 re.compile(r'(?:TOWNSEND[\,\.]?\s+MASSACHUSETTS|TOWNSEND[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'TOWNSEND, MA',
 re.compile(r'(?:WEST GROTON[\,\.]?\s+MASSACHUSETTS|WEST GROTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WEST GROTON, MA',
 re.compile(r'(?:WEST TOWNSEND[\,\.]?\s+MASSACHUSETTS|WEST TOWNSEND[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WEST TOWNSEND, MA',
 re.compile(r'(?:WINCHENDON[\,\.]?\s+MASSACHUSETTS|WINCHENDON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'WINCHENDON, MA',
 re.compile(r'(?:AUBURN[\,\.]?\s+MASSACHUSETTS|AUBURN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'AUBURN, MA',
 re.compile(r'(?:BERLIN[\,\.]?\s+MASSACHUSETTS|BERLIN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BERLIN, MA',
 re.compile(r'(?:BLACKSTONE[\,\.]?\s+MASSACHUSETTS|BLACKSTONE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BLACKSTONE, MA',
 re.compile(r'(?:BOYLSTON[\,\.]?\s+MASSACHUSETTS|BOYLSTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BOYLSTON, MA',
 re.compile(r'(?:BROOKFIELD[\,\.]?\s+MASSACHUSETTS|BROOKFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'BROOKFIELD, MA',
 re.compile(r'(?:CHARLTON[\,\.]?\s+MASSACHUSETTS|CHARLTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CHARLTON, MA',
 re.compile(r'(?:CHARLTON CITY[\,\.]?\s+MASSACHUSETTS|CHARLTON CITY[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CHARLTON CITY, MA',
 re.compile(r'(?:CHARLTON DEPOT[\,\.]?\s+MASSACHUSETTS|CHARLTON DEPOT[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CHARLTON DEPOT, MA',
 re.compile(r'(?:CLINTON[\,\.]?\s+MASSACHUSETTS|CLINTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'CLINTON, MA',
 re.compile(r'(?:EAST BROOKFIELD[\,\.]?\s+MASSACHUSETTS|EAST BROOKFIELD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'EAST BROOKFIELD, MA',
 re.compile(r'(?:DOUGLAS[\,\.]?\s+MASSACHUSETTS|DOUGLAS[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'DOUGLAS, MA',
 re.compile(r'(?:FISKDALE[\,\.]?\s+MASSACHUSETTS|FISKDALE[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'FISKDALE, MA',
 re.compile(r'(?:GRAFTON[\,\.]?\s+MASSACHUSETTS|GRAFTON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'GRAFTON, MA',
 re.compile(r'(?:HOLDEN[\,\.]?\s+MASSACHUSETTS|HOLDEN[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HOLDEN, MA',
 re.compile(r'(?:HOLLAND[\,\.]?\s+MASSACHUSETTS|HOLLAND[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'HOLLAND, MA',
 re.compile(r'(?:JEFFERSON[\,\.]?\s+MASSACHUSETTS|JEFFERSON[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'JEFFERSON, MA',
 re.compile(r'(?:LANCASTER[\,\.]?\s+MASSACHUSETTS|LANCASTER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LANCASTER, MA',
 re.compile(r'(?:LEICESTER[\,\.]?\s+MASSACHUSETTS|LEICESTER[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LEICESTER, MA',
 re.compile(r'(?:LINWOOD[\,\.]?\s+MASSACHUSETTS|LINWOOD[\,\.]?\s+M\.?\s*A\.?\s*)',
 re.UNICODE): 'LINWOOD, MA',
 re.compile(r'(?:MANCHAUG[\,\.]?\s+MASSACHUSETTS|MANCHAUG[\,\.]?\s+M\.?\s*A\.?\s*)',

In [1838]:
# Replace cities with standard 'City, State_abbr' format using the 'regex_city_dict'
cities_to_fix.replace(regex_city_dict, inplace=True)
cities_to_fix

283                  DELAWARE
336            NORTH CAROLINA
337              ROCKWALL, TX
338              ROCKWALL, TX
396               RALEIGH, NC
399                  TROY, MI
474             CAMARILLO, CA
520                 SAN DIEGO
613                     TEXAS
763            WILMINGTON, DE
892             CAMARILLO, CA
974                  DANVILLE
1288                 DELAWARE
1895              NORWALK, CT
2234           WASHINGTON, DC
2306               SALINE, MI
2447          SPRINGFIELD, IL
2709            CAMBRIDGE, MA
2887            BEAVERTON, OR
2888           SCHAUMBURG, IL
2981                    MIAMI
2993                 DELAWARE
3179               AUSTIN, TX
3368                 W JERSEY
3411               CHASKA, MN
3448               CALIFORNIA
3515    PACIFIC PALISADES, CA
3516          LOS ANGELES, CA
Name: City, dtype: object

In [1839]:
# fix those still cannot meet the standard formats
cities_to_fix_manual_search = cities_to_fix[cities_to_fix.str.split(',').str.len()<2]
cities_to_fix_manual_search

283           DELAWARE
336     NORTH CAROLINA
520          SAN DIEGO
613              TEXAS
974           DANVILLE
1288          DELAWARE
2981             MIAMI
2993          DELAWARE
3368          W JERSEY
3448        CALIFORNIA
Name: City, dtype: object

In [1840]:
values = {283:'DE', 
          336:'NC', 
          520:'SAN DIEGO, CA', 
          613:'TX', 
          974:'DANVILLE CA',
          1288:'DE', 
          2981:'MIAMI, FL',
          2993:'DE', 
          3368:'ALLENDALE, NJ',
          3448:'Van Nuys, CA'.upper()}

cities_to_fix_manual_search = pd.Series(values)
cities_to_fix[cities_to_fix_manual_search.index]=cities_to_fix_manual_search
cities_to_fix

283                        DE
336                        NC
337              ROCKWALL, TX
338              ROCKWALL, TX
396               RALEIGH, NC
399                  TROY, MI
474             CAMARILLO, CA
520             SAN DIEGO, CA
613                        TX
763            WILMINGTON, DE
892             CAMARILLO, CA
974               DANVILLE CA
1288                       DE
1895              NORWALK, CT
2234           WASHINGTON, DC
2306               SALINE, MI
2447          SPRINGFIELD, IL
2709            CAMBRIDGE, MA
2887            BEAVERTON, OR
2888           SCHAUMBURG, IL
2981                MIAMI, FL
2993                       DE
3179               AUSTIN, TX
3368            ALLENDALE, NJ
3411               CHASKA, MN
3448             VAN NUYS, CA
3515    PACIFIC PALISADES, CA
3516          LOS ANGELES, CA
Name: City, dtype: object

In [1841]:
# save the updated info to US_addresses
US_addresses.loc[cities_to_fix.index,'City']=cities_to_fix
US_addresses.loc[cities_to_fix.index]

,ClientID,Address,Zip,Country,City
283,US003046,DELAWARE USA,NaN,USA,DE
336,US002977,"NORTH CAROLINA, USA",NaN,USA,NC
337,US002963,ROCKWALL TEXAS UNITED STATES OF AMERICA,NaN,USA,"ROCKWALL, TX"
338,US002964,ROCKWALL TEXAS UNITED STATES OF AMERICA,NaN,USA,"ROCKWALL, TX"
396,US003542,"1613 PINEVIEW DRIVE RALEIGH, NORTH CAROLINA UN...",NaN,USA,"RALEIGH, NC"
399,US003544,"1401 CROOKS ROAD, TROY, MICHIGAN USA",NaN,USA,"TROY, MI"
474,US003072,"941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA",NaN,USA,"CAMARILLO, CA"
520,US002961,SAN DIEGO USA,NaN,USA,"SAN DIEGO, CA"
613,US003269,TEXAS USA,NaN,USA,TX
763,US002527,"3411 SILVERSIDE RD., RODNEY BLDG. SUITE 104, W...",NaN,USA,"WILMINGTON, DE"
892,US003394,"941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA",NaN,USA,"CAMARILLO, CA"
974,US000050,"9000 CROW CANYON ROAD, SUITE S393, DANVILLE, C...",NaN,USA,DANVILLE CA
1288,US000373,"DELAWARE, U.S.A.",NaN,USA,DE
1895,US000982,"301 MERRITT 7, NORWALK, CONNECTICUT UNITED STA...",NaN,USA,"NORWALK, CT"
2234,US001330,"WASHINGTON, DISTRICT OF COLUMBIA USA",NaN,USA,"WASHINGTON, DC"
2306,US001403,"225 INDUSTRIAL DRIVE SALINE, MICHIGAN UNITED S...",NaN,USA,"SALINE, MI"
2447,US001545,"6444 SOUTH 6TH STREET ROAD SPRINGFIELD, ILLINO...",NaN,USA,"SPRINGFIELD, IL"
2709,US001815,"2 WARE STREET, APT. 507, CAMBRIDGE, MASSACHUSE...",NaN,USA,"CAMBRIDGE, MA"
2887,US002000,"15025 SW KOLL PARKWAY BEAVERTON, OREGON UNITED...",NaN,USA,"BEAVERTON, OR"
2888,US002001,"150 NORTH MARTINGALE ROAD, SCHAUMBURG, ILLINOI...",NaN,USA,"SCHAUMBURG, IL"
2981,US002094,"8905 S.W. 87TH AVENUE, MIAMI, USA",NaN,USA,"MIAMI, FL"
2993,US002106,DELAWARE USA,NaN,USA,DE
3179,US002297,AUSTIN TEXAS USA,NaN,USA,"AUSTIN, TX"
3368,US002489,5 PEARL COURT ALLENDALE PARK NEW JERSEY USA,NaN,USA,"ALLENDALE, NJ"
3411,US003480,"101 PEAVEY ROAD CHASKA, MINNESOTA US",NaN,USA,"CHASKA, MN"
3448,US002712,"CALIFORNIA, USA",NaN,USA,"VAN NUYS, CA"
3515,US003080,"PACIFIC PALISADES, CALIFORNIA USA",NaN,USA,"PACIFIC PALISADES, CA"
3516,US003081,"LOS ANGELES, CALIFORNIA USA",NaN,USA,"LOS ANGELES, CA"

### Look up city information by `Zip` in `US_addresses`

In [1842]:
no_city = US_addresses[US_addresses.City.isna()]
print(no_city.shape[0])
no_city.head()

3572

,ClientID,Address,Zip,Country,City
0,US002562,"ONE BLOSSOM ROAD, ROCHESTER, NY 14610 USA",14610,USA,NaN
1,US002565,"600 NORTH BRAND BLVD., SUITE 230 GLENDALE, CA ...",91203,USA,NaN
2,US002566,C/O R.R. DONNELLEY & SONS COMPANY 111 SOUTH WA...,60606,USA,NaN
3,US002567,"430 CARMEL COURT CANTON, GEORGIA 30114 USA",30114,USA,NaN
4,US002568,"200 SIDNEY STREET SUITE 310 CAMBRIDGE, MASSACH...",02139,USA,NaN

In [1843]:
US_addresses.loc[US_addresses.City.isna() | US_addresses.Zip.notna()].shape[0]

3575

In [1844]:
US_addresses.loc[US_addresses.City.notna() & US_addresses.Zip.notna()]

,ClientID,Address,Zip,Country,City
168,US002740,"1909 K STREET NW, SUITE 900, USA",20006,USA,"Washington, DC"
2263,US001360,"2227 WELBILT BOULEVARD, NEW PORT RICHEY, FLORI...",34655,USA,"Port Richey, FL"
2316,US001413,加州95124-3400圣荷西罗吉克路2100号,95124-3400,USA,"FREMONT, CA"

In [1845]:
zip_city_dict = dict(zip(zipcodes['Zip Code'],zipcodes['Place Name']+', '+zipcodes['State_Abbr']))
zip_city_dict

{'00501': 'Holtsville, NY',
 '00544': 'Holtsville, NY',
 '01001': 'Agawam, MA',
 '01002': 'Amherst, MA',
 '01003': 'Amherst, MA',
 '01004': 'Amherst, MA',
 '01005': 'Barre, MA',
 '01007': 'Belchertown, MA',
 '01008': 'Blandford, MA',
 '01009': 'Bondsville, MA',
 '01010': 'Brimfield, MA',
 '01011': 'Chester, MA',
 '01012': 'Chesterfield, MA',
 '01013': 'Chicopee, MA',
 '01014': 'Chicopee, MA',
 '01020': 'Chicopee, MA',
 '01021': 'Chicopee, MA',
 '01022': 'Chicopee, MA',
 '01026': 'Cummington, MA',
 '01027': 'Easthampton, MA',
 '01028': 'East Longmeadow, MA',
 '01029': 'East Otis, MA',
 '01030': 'Feeding Hills, MA',
 '01031': 'Gilbertville, MA',
 '01032': 'Goshen, MA',
 '01033': 'Granby, MA',
 '01034': 'Granville, MA',
 '01035': 'Hadley, MA',
 '01036': 'Hampden, MA',
 '01037': 'Hardwick, MA',
 '01038': 'Hatfield, MA',
 '01039': 'Haydenville, MA',
 '01040': 'Holyoke, MA',
 '01041': 'Holyoke, MA',
 '01050': 'Huntington, MA',
 '01053': 'Leeds, MA',
 '01054': 'Leverett, MA',
 '01056': 'Ludlow, MA',
 '01057': 'Monson, MA',
 '01059': 'North Amherst, MA',
 '01060': 'Northampton, MA',
 '01061': 'Northampton, MA',
 '01062': 'Florence, MA',
 '01063': 'Northampton, MA',
 '01066': 'North Hatfield, MA',
 '01068': 'Oakham, MA',
 '01069': 'Palmer, MA',
 '01070': 'Plainfield, MA',
 '01071': 'Russell, MA',
 '01072': 'Shutesbury, MA',
 '01073': 'Southampton, MA',
 '01074': 'South Barre, MA',
 '01075': 'South Hadley, MA',
 '01077': 'Southwick, MA',
 '01079': 'Thorndike, MA',
 '01080': 'Three Rivers, MA',
 '01081': 'Wales, MA',
 '01082': 'Ware, MA',
 '01083': 'Warren, MA',
 '01084': 'West Chesterfield, MA',
 '01085': 'Westfield, MA',
 '01086': 'Westfield, MA',
 '01088': 'West Hatfield, MA',
 '01089': 'West Springfield, MA',
 '01090': 'West Springfield, MA',
 '01092': 'West Warren, MA',
 '01093': 'Whately, MA',
 '01094': 'Wheelwright, MA',
 '01095': 'Wilbraham, MA',
 '01096': 'Williamsburg, MA',
 '01097': 'Woronoco, MA',
 '01098': 'Worthington, MA',
 '01101': 'Springfield, MA',
 '01102': 'Springfield, MA',
 '01103': 'Springfield, MA',
 '01104': 'Springfield, MA',
 '01105': 'Springfield, MA',
 '01106': 'Longmeadow, MA',
 '01107': 'Springfield, MA',
 '01108': 'Springfield, MA',
 '01109': 'Springfield, MA',
 '01111': 'Springfield, MA',
 '01115': 'Springfield, MA',
 '01116': 'Longmeadow, MA',
 '01118': 'Springfield, MA',
 '01119': 'Springfield, MA',
 '01128': 'Springfield, MA',
 '01129': 'Springfield, MA',
 '01138': 'Springfield, MA',
 '01139': 'Springfield, MA',
 '01144': 'Springfield, MA',
 '01151': 'Indian Orchard, MA',
 '01152': 'Springfield, MA',
 '01199': 'Springfield, MA',
 '01201': 'Pittsfield, MA',
 '01202': 'Pittsfield, MA',
 '01203': 'Pittsfield, MA',
 '01220': 'Adams, MA',
 '01222': 'Ashley Falls, MA',
 '01223': 'Becket, MA',
 '01224': 'Berkshire, MA',
 '01225': 'Cheshire, MA',
 '01226': 'Dalton, MA',
 '01227': 'Dalton, MA',
 '01229': 'Glendale, MA',
 '01230': 'Great Barrington, MA',
 '01235': 'Hinsdale, MA',
 '01236': 'Housatonic, MA',
 '01237': 'Lanesborough, MA',
 '01238': 'Lee, MA',
 '01240': 'Lenox, MA',
 '01242': 'Lenox Dale, MA',
 '01243': 'Middlefield, MA',
 '01244': 'Mill River, MA',
 '01245': 'Monterey, MA',
 '01247': 'North Adams, MA',
 '01252': 'North Egremont, MA',
 '01253': 'Otis, MA',
 '01254': 'Richmond, MA',
 '01255': 'Sandisfield, MA',
 '01256': 'Savoy, MA',
 '01257': 'Sheffield, MA',
 '01258': 'South Egremont, MA',
 '01259': 'Southfield, MA',
 '01260': 'South Lee, MA',
 '01262': 'Stockbridge, MA',
 '01263': 'Stockbridge, MA',
 '01264': 'Tyringham, MA',
 '01266': 'West Stockbridge, MA',
 '01267': 'Williamstown, MA',
 '01270': 'Windsor, MA',
 '01301': 'Greenfield, MA',
 '01302': 'Greenfield, MA',
 '01330': 'Ashfield, MA',
 '01331': 'Athol, MA',
 '01337': 'Bernardston, MA',
 '01338': 'Buckland, MA',
 '01339': 'Charlemont, MA',
 '01340': 'Colrain, MA',
 '01341': 'Conway, MA',
 '01342': 'Deerfield, MA',
 '01343': 'Drury, MA',
 '01344': 'Erving, MA',
 '01346': 'Heath, MA',
 '01347': 'Lake Pleasant, MA',
 '01349': 'Millers Falls, MA',
 '01350': 'Monroe Bridge, MA',
 '01351': 'Montague, MA',
 '01354': 'Gill, MA',
 '01355': 'New Salem, MA',
 '01360': 'Northfield, MA',
 '01364': 'Orange, MA',
 '01366': 'Petersham, MA',
 '01367': 'Rowe, MA',
 '01368': 'Royalston, MA',
 '01370': 'Shelburne Falls, MA',
 '01373': 'South Deerfield, MA',
 '01375': 'Sunderland, MA',
 '01376': 'Turners Falls, MA',
 '01378': 'Warwick, MA',
 '01379': 'Wendell, MA',
 '01380': 'Wendell Depot, MA',
 '01420': 'Fitchburg, MA',
 '01430': 'Ashburnham, MA',
 '01431': 'Ashby, MA',
 '01432': 'Ayer, MA',
 '01434': 'Devens, MA',
 '01436': 'Baldwinville, MA',
 '01438': 'East Templeton, MA',
 '01440': 'Gardner, MA',
 '01441': 'Westminster, MA',
 '01450': 'Groton, MA',
 '01451': 'Harvard, MA',
 '01452': 'Hubbardston, MA',
 '01453': 'Leominster, MA',
 '01460': 'Littleton, MA',
 '01462': 'Lunenburg, MA',
 '01463': 'Pepperell, MA',
 '01464': 'Shirley, MA',
 '01467': 'Still River, MA',
 '01468': 'Templeton, MA',
 '01469': 'Townsend, MA',
 '01470': 'Groton, MA',
 '01471': 'Groton, MA',
 '01472': 'West Groton, MA',
 '01473': 'Westminster, MA',
 '01474': 'West Townsend, MA',
 '01475': 'Winchendon, MA',
 '01501': 'Auburn, MA',
 '01503': 'Berlin, MA',
 '01504': 'Blackstone, MA',
 '01505': 'Boylston, MA',
 '01506': 'Brookfield, MA',
 '01507': 'Charlton, MA',
 '01508': 'Charlton City, MA',
 '01509': 'Charlton Depot, MA',
 '01510': 'Clinton, MA',
 '01515': 'East Brookfield, MA',
 '01516': 'Douglas, MA',
 '01518': 'Fiskdale, MA',
 '01519': 'Grafton, MA',
 '01520': 'Holden, MA',
 '01521': 'Holland, MA',
 '01522': 'Jefferson, MA',
 '01523': 'Lancaster, MA',
 '01524': 'Leicester, MA',
 '01525': 'Linwood, MA',
 '01526': 'Manchaug, MA',
 '01527': 'Millbury, MA',
 '01529': 'Millville, MA',
 '01531': 'New Braintree, MA',
 '01532': 'Northborough, MA',
 '01534': 'Northbridge, MA',
 '01535': 'North Brookfield, MA',
 '01536': 'North Grafton, MA',
 '01537': 'North Oxford, MA',
 '01538': 'North Uxbridge, MA',
 '01540': 'Oxford, MA',
 '01541': 'Princeton, MA',
 '01542': 'Rochdale, MA',
 '01543': 'Rutland, MA',
 '01545': 'Shrewsbury, MA',
 '01546': 'Shrewsbury, MA',
 '01550': 'Southbridge, MA',
 '01560': 'South Grafton, MA',
 '01561': 'South Lancaster, MA',
 '01562': 'Spencer, MA',
 '01564': 'Sterling, MA',
 '01566': 'Sturbridge, MA',
 '01568': 'Upton, MA',
 '01569': 'Uxbridge, MA',
 '01570': 'Webster, MA',
 '01571': 'Dudley, MA',
 '01581': 'Westborough, MA',
 '01583': 'West Boylston, MA',
 '01585': 'West Brookfield, MA',
 '01586': 'West Millbury, MA',
 '01588': 'Whitinsville, MA',
 '01590': 'Sutton, MA',
 '01601': 'Worcester, MA',
 '01602': 'Worcester, MA',
 '01603': 'Worcester, MA',
 '01604': 'Worcester, MA',
 '01605': 'Worcester, MA',
 '01606': 'Worcester, MA',
 '01607': 'Worcester, MA',
 '01608': 'Worcester, MA',
 '01609': 'Worcester, MA',
 '01610': 'Worcester, MA',
 '01611': 'Cherry Valley, MA',
 '01612': 'Paxton, MA',
 '01613': 'Worcester, MA',
 '01614': 'Worcester, MA',
 '01615': 'Worcester, MA',
 '01653': 'Worcester, MA',
 '01655': 'Worcester, MA',
 '01701': 'Framingham, MA',
 '01702': 'Framingham, MA',
 '01703': 'Framingham, MA',
 '01704': 'Framingham, MA',
 '01705': 'Framingham, MA',
 '01718': 'Acton, MA',
 '01719': 'Boxborough, MA',
 '01720': 'Acton, MA',
 '01721': 'Ashland, MA',
 '01730': 'Bedford, MA',
 '01731': 'Hanscom Afb, MA',
 '01740': 'Bolton, MA',
 '01741': 'Carlisle, MA',
 '01742': 'Concord, MA',
 '01745': 'Fayville, MA',
 '01746': 'Holliston, MA',
 '01747': 'Hopedale, MA',
 '01748': 'Hopkinton, MA',
 '01749': 'Hudson, MA',
 '01752': 'Marlborough, MA',
 '01754': 'Maynard, MA',
 '01756': 'Mendon, MA',
 '01757': 'Milford, MA',
 '01760': 'Natick, MA',
 '01770': 'Sherborn, MA',
 '01772': 'Southborough, MA',
 '01773': 'Lincoln, MA',
 '01775': 'Stow, MA',
 '01776': 'Sudbury, MA',
 '01778': 'Wayland, MA',
 '01784': 'Woodville, MA',
 '01801': 'Woburn, MA',
 '01803': 'Burlington, MA',
 '01805': 'Burlington, MA',
 '01810': 'Andover, MA',
 '01812': 'Andover, MA',
 '01813': 'Woburn, MA',
 '01815': 'Woburn, MA',
 '01821': 'Billerica, MA',
 '01822': 'Billerica, MA',
 '01824': 'Chelmsford, MA',
 '01826': 'Dracut, MA',
 '01827': 'Dunstable, MA',
 '01830': 'Haverhill, MA',
 '01831': 'Haverhill, MA',
 '01832': 'Haverhill, MA',
 '01833': 'Georgetown, MA',
 '01834': 'Groveland, MA',
 '01835': 'Haverhill, MA',
 '01840': 'Lawrence, MA',
 '01841': 'Lawrence, MA',
 '01842': 'Lawrence, MA',
 '01843': 'Lawrence, MA',
 '01844': 'Methuen, MA',
 '01845': 'North Andover, MA',
 '01850': 'Lowell, MA',
 '01851': 'Lowell, MA',
 '01852': 'Lowell, MA',
 '01853': 'Lowell, MA',
 '01854': 'Lowell, MA',
 '01860': 'Merrimac, MA',
 '01862': 'North Billerica, MA',
 '01863': 'North Chelmsford, MA',
 '01864': 'North Reading, MA',
 '01865': 'Nutting Lake, MA',
 '01866': 'Pinehurst, MA',
 '01867': 'Reading, MA',
 '01876': 'Tewksbury, MA',
 '01879': 'Tyngsboro, MA',
 '01880': 'Wakefield, MA',
 '01885': 'West Boxford, MA',
 '01886': 'Westford, MA',
 '01887': 'Wilmington, MA',
 '01888': 'Woburn, MA',
 '01889': 'North Reading, MA',
 '01890': 'Winchester, MA',
 '01899': 'Andover, MA',
 '01901': 'Lynn, MA',
 '01902': 'Lynn, MA',
 '01903': 'Lynn, MA',
 '01904': 'Lynn, MA',
 '01905': 'Lynn, MA',
 '01906': 'Saugus, MA',
 '01907': 'Swampscott, MA',
 '01908': 'Nahant, MA',
 '01910': 'Lynn, MA',
 '01913': 'Amesbury, MA',
 '01915': 'Beverly, MA',
 '01921': 'Boxford, MA',
 '01922': 'Byfield, MA',
 '01923': 'Danvers, MA',
 '01929': 'Essex, MA',
 '01930': 'Gloucester, MA',
 '01931': 'Gloucester, MA',
 '01936': 'Hamilton, MA',
 '01937': 'Hathorne, MA',
 '01938': 'Ipswich, MA',
 '01940': 'Lynnfield, MA',
 '01944': 'Manchester, MA',
 '01945': 'Marblehead, MA',
 '01949': 'Middleton, MA',
 '01950': 'Newburyport, MA',
 '01951': 'Newbury, MA',
 '01952': 'Salisbury, MA',
 '01960': 'Peabody, MA',
 '01961': 'Peabody, MA',
 '01965': 'Prides Crossing, MA',
 '01966': 'Rockport, MA',
 '01969': 'Rowley, MA',
 '01970': 'Salem, MA',
 '01971': 'Salem, MA',
 '01982': 'South Hamilton, MA',
 '01983': 'Topsfield, MA',
 '01984': 'Wenham, MA',
 '01985': 'West Newbury, MA',
 '02018': 'Accord, MA',
 '02019': 'Bellingham, MA',
 '02020': 'Brant Rock, MA',
 '02021': 'Canton, MA',
 '02025': 'Cohasset, MA',
 '02026': 'Dedham, MA',
 '02027': 'Dedham, MA',
 '02030': 'Dover, MA',
 '02032': 'East Walpole, MA',
 '02035': 'Foxboro, MA',
 '02038': 'Franklin, MA',
 '02040': 'Greenbush, MA',
 '02041': 'Green Harbor, MA',
 '02043': 'Hingham, MA',
 '02044': 'Hingham, MA',
 '02045': 'Hull, MA',
 '02047': 'Humarock, MA',
 '02048': 'Mansfield, MA',
 '02050': 'Marshfield, MA',
 '02051': 'Marshfield Hills, MA',
 '02052': 'Medfield, MA',
 '02053': 'Medway, MA',
 '02054': 'Millis, MA',
 '02055': 'Minot, MA',
 '02056': 'Norfolk, MA',
 '02059': 'North Marshfield, MA',
 '02060': 'North Scituate, MA',
 '02061': 'Norwell, MA',
 '02062': 'Norwood, MA',
 '02065': 'Ocean Bluff, MA',
 '02066': 'Scituate, MA',
 '02067': 'Sharon, MA',
 '02070': 'Sheldonville, MA',
 '02071': 'South Walpole, MA',
 '02072': 'Stoughton, MA',
 '02081': 'Walpole, MA',
 '02090': 'Westwood, MA',
 '02093': 'Wrentham, MA',
 '02108': 'Boston, MA',
 '02109': 'Boston, MA',
 '02110': 'Boston, MA',
 '02111': 'Boston, MA',
 '02112': 'Boston, MA',
 '02113': 'Boston, MA',
 '02114': 'Boston, MA',
 '02115': 'Boston, MA',
 '02116': 'Boston, MA',
 '02117': 'Boston, MA',
 '02118': 'Boston, MA',
 '02119': 'Roxbury, MA',
 '02120': 'Roxbury Crossing, MA',
 '02121': 'Dorchester, MA',
 '02122': 'Dorchester, MA',
 '02123': 'Boston, MA',
 '02124': 'Dorchester Center, MA',
 '02125': 'Dorchester, MA',
 '02126': 'Mattapan, MA',
 '02127': 'Boston, MA',
 '02128': 'Boston, MA',
 '02129': 'Charlestown, MA',
 '02130': 'Jamaica Plain, MA',
 '02131': 'Roslindale, MA',
 '02132': 'West Roxbury, MA',
 '02133': 'Boston, MA',
 '02134': 'Allston, MA',
 '02135': 'Brighton, MA',
 '02136': 'Hyde Park, MA',
 '02137': 'Readville, MA',
 '02138': 'Cambridge, MA',
 '02139': 'Cambridge, MA',
 '02140': 'Cambridge, MA',
 '02141': 'Cambridge, MA',
 '02142': 'Cambridge, MA',
 '02143': 'Somerville, MA',
 '02144': 'Somerville, MA',
 '02145': 'Somerville, MA',
 '02148': 'Malden, MA',
 '02149': 'Everett, MA',
 '02150': 'Chelsea, MA',
 '02151': 'Revere, MA',
 '02152': 'Winthrop, MA',
 '02153': 'Medford, MA',
 '02155': 'Medford, MA',
 '02156': 'West Medford, MA',
 '02163': 'Boston, MA',
 '02169': 'Quincy, MA',
 '02170': 'Quincy, MA',
 '02171': 'Quincy, MA',
 '02176': 'Melrose, MA',
 '02180': 'Stoneham, MA',
 '02184': 'Braintree, MA',
 '02185': 'Braintree, MA',
 '02186': 'Milton, MA',
 '02187': 'Milton Village, MA',
 '02188': 'Weymouth, MA',
 '02189': 'East Weymouth, MA',
 '02190': 'South Weymouth, MA',
 '02191': 'North Weymouth, MA',
 '02196': 'Boston, MA',
 '02199': 'Boston, MA',
 '02201': 'Boston, MA',
 '02203': 'Boston, MA',
 '02204': 'Boston, MA',
 '02205': 'Boston, MA',
 '02206': 'Boston, MA',
 '02210': 'Boston, MA',
 '02211': 'Boston, MA',
 '02212': 'Boston, MA',
 '02215': 'Boston, MA',
 '02217': 'Boston, MA',
 '02222': 'Boston, MA',
 '02238': 'Cambridge, MA',
 '02241': 'Boston, MA',
 '02266': 'Boston, MA',
 '02269': 'Quincy, MA',
 '02283': 'Boston, MA',
 '02284': 'Boston, MA',
 '02293': 'Boston, MA',
 '02297': 'Boston, MA',
 '02298': 'Boston, MA',
 '02301': 'Brockton, MA',
 '02302': 'Brockton, MA',
 '02303': 'Brockton, MA',
 '02304': 'Brockton, MA',
 '02305': 'Brockton, MA',
 '02322': 'Avon, MA',
 '02324': 'Bridgewater, MA',
 '02325': 'Bridgewater, MA',
 '02327': 'Bryantville, MA',
 '02330': 'Carver, MA',
 '02331': 'Duxbury, MA',
 '02332': 'Duxbury, MA',
 '02333': 'East Bridgewater, MA',
 '02334': 'Easton, MA',
 '02337': 'Elmwood, MA',
 '02338': 'Halifax, MA',
 '02339': 'Hanover, MA',
 '02340': 'Hanover, MA',
 '02341': 'Hanson, MA',
 '02343': 'Holbrook, MA',
 '02344': 'Middleboro, MA',
 '02345': 'Manomet, MA',
 '02346': 'Middleboro, MA',
 '02347': 'Lakeville, MA',
 '02348': 'Lakeville, MA',
 '02349': 'Middleboro, MA',
 '02350': 'Monponsett, MA',
 '02351': 'Abington, MA',
 '02355': 'North Carver, MA',
 '02356': 'North Easton, MA',
 '02357': 'North Easton, MA',
 '02358': 'North Pembroke, MA',
 '02359': 'Pembroke, MA',
 '02360': 'Plymouth, MA',
 '02361': 'Plymouth, MA',
 '02362': 'Plymouth, MA',
 '02364': 'Kingston, MA',
 '02366': 'South Carver, MA',
 '02367': 'Plympton, MA',
 '02368': 'Randolph, MA',
 '02370': 'Rockland, MA',
 '02375': 'South Easton, MA',
 '02379': 'West Bridgewater, MA',
 '02381': 'White Horse Beach, MA',
 '02382': 'Whitman, MA',
 '02420': 'Lexington, MA',
 '02421': 'Lexington, MA',
 '02445': 'Brookline, MA',
 '02446': 'Brookline, MA',
 '02447': 'Brookline Village, MA',
 '02451': 'Waltham, MA',
 '02452': 'Waltham, MA',
 '02453': 'Waltham, MA',
 '02454': 'Waltham, MA',
 '02455': 'North Waltham, MA',
 '02456': 'New Town, MA',
 '02457': 'Babson Park, MA',
 '02458': 'Newton, MA',
 '02459': 'Newton Center, MA',
 '02460': 'Newtonville, MA',
 '02461': 'Newton Highlands, MA',
 '02462': 'Newton Lower Falls, MA',
 '02464': 'Newton Upper Falls, MA',
 '02465': 'West Newton, MA',
 '02466': 'Auburndale, MA',
 '02467': 'Chestnut Hill, MA',
 '02468': 'Waban, MA',
 '02471': 'Watertown, MA',
 '02472': 'Watertown, MA',
 '02474': 'Arlington, MA',
 '02475': 'Arlington Heights, MA',
 '02476': 'Arlington, MA',
 '02477': 'Watertown, MA',
 '02478': 'Belmont, MA',
 '02479': 'Waverley, MA',
 '02481': 'Wellesley Hills, MA',
 '02482': 'Wellesley, MA',
 '02492': 'Needham, MA',
 '02493': 'Weston, MA',
 '02494': 'Needham Heights, MA',
 '02495': 'Nonantum, MA',
 '02532': 'Buzzards Bay, MA',
 '02534': 'Cataumet, MA',
 '02535': 'Chilmark, MA',
 '02536': 'East Falmouth, MA',
 '02537': 'East Sandwich, MA',
 '02538': 'East Wareham, MA',
 '02539': 'Edgartown, MA',
 '02540': 'Falmouth, MA',
 '02541': 'Falmouth, MA',
 '02542': 'Buzzards Bay, MA',
 '02543': 'Woods Hole, MA',
 '02552': 'Menemsha, MA',
 '02553': 'Monument Beach, MA',
 '02554': 'Nantucket, MA',
 '02556': 'North Falmouth, MA',
 '02557': 'Oak Bluffs, MA',
 '02558': 'Onset, MA',
 '02559': 'Pocasset, MA',
 '02561': 'Sagamore, MA',
 '02562': 'Sagamore Beach, MA',
 '02563': 'Sandwich, MA',
 '02564': 'Siasconset, MA',
 '02568': 'Vineyard Haven, MA',
 '02571': 'Wareham, MA',
 '02574': 'West Falmouth, MA',
 '02575': 'West Tisbury, MA',
 '02576': 'West Wareham, MA',
 '02584': 'Nantucket, MA',
 '02601': 'Hyannis, MA',
 '02630': 'Barnstable, MA',
 '02631': 'Brewster, MA',
 '02632': 'Centerville, MA',
 '02633': 'Chatham, MA',
 '02634': 'Centerville, MA',
 '02635': 'Cotuit, MA',
 '02637': 'Cummaquid, MA',
 '02638': 'Dennis, MA',
 '02639': 'Dennis Port, MA',
 '02641': 'East Dennis, MA',
 '02642': 'Eastham, MA',
 '02643': 'East Orleans, MA',
 '02644': 'Forestdale, MA',
 '02645': 'Harwich, MA',
 '02646': 'Harwich Port, MA',
 '02647': 'Hyannis Port, MA',
 '02648': 'Marstons Mills, MA',
 '02649': 'Mashpee, MA',
 '02650': 'North Chatham, MA',
 '02651': 'North Eastham, MA',
 '02652': 'North Truro, MA',
 '02653': 'Orleans, MA',
 '02655': 'Osterville, MA',
 '02657': 'Provincetown, MA',
 '02659': 'South Chatham, MA',
 '02660': 'South Dennis, MA',
 '02661': 'South Harwich, MA',
 '02662': 'South Orleans, MA',
 '02663': 'South Wellfleet, MA',
 '02664': 'South Yarmouth, MA',
 '02666': 'Truro, MA',
 '02667': 'Wellfleet, MA',
 '02668': 'West Barnstable, MA',
 '02669': 'West Chatham, MA',
 '02670': 'West Dennis, MA',
 '02671': 'West Harwich, MA',
 '02672': 'West Hyannisport, MA',
 '02673': 'West Yarmouth, MA',
 '02675': 'Yarmouth Port, MA',
 '02702': 'Assonet, MA',
 '02703': 'Attleboro, MA',
 '02712': 'Chartley, MA',
 '02713': 'Cuttyhunk, MA',
 '02714': 'Dartmouth, MA',
 '02715': 'Dighton, MA',
 '02717': 'East Freetown, MA',
 '02718': 'East Taunton, MA',
 '02719': 'Fairhaven, MA',
 '02720': 'Fall River, MA',
 '02721': 'Fall River, MA',
 '02722': 'Fall River, MA',
 '02723': 'Fall River, MA',
 '02724': 'Fall River, MA',
 '02725': 'Somerset, MA',
 '02726': 'Somerset, MA',
 '02738': 'Marion, MA',
 '02739': 'Mattapoisett, MA',
 '02740': 'New Bedford, MA',
 '02741': 'New Bedford, MA',
 '02742': 'New Bedford, MA',
 '02743': 'Acushnet, MA',
 '02744': 'New Bedford, MA',
 '02745': 'New Bedford, MA',
 '02746': 'New Bedford, MA',
 '02747': 'North Dartmouth, MA',
 '02748': 'South Dartmouth, MA',
 '02760': 'North Attleboro, MA',
 '02761': 'North Attleboro, MA',
 '02762': 'Plainville, MA',
 '02763': 'Attleboro Falls, MA',
 '02764': 'North Dighton, MA',
 '02766': 'Norton, MA',
 '02767': 'Raynham, MA',
 '02768': 'Raynham Center, MA',
 '02769': 'Rehoboth, MA',
 '02770': 'Rochester, MA',
 '02771': 'Seekonk, MA',
 '02777': 'Swansea, MA',
 '02779': 'Berkley, MA',
 '02780': 'Taunton, MA',
 '02783': 'Taunton, MA',
 '02790': 'Westport, MA',
 '02791': 'Westport Point, MA',
 '02801': 'Adamsville, RI',
 '02802': 'Albion, RI',
 '02804': 'Ashaway, RI',
 '02806': 'Barrington, RI',
 '02807': 'Block Island, RI',
 '02808': 'Bradford, RI',
 '02809': 'Bristol, RI',
 '02812': 'Carolina, RI',
 '02813': 'Charlestown, RI',
 '02814': 'Chepachet, RI',
 '02815': 'Clayville, RI',
 '02816': 'Coventry, RI',
 '02817': 'West Greenwich, RI',
 '02818': 'East Greenwich, RI',
 '02822': 'Exeter, RI',
 '02823': 'Fiskeville, RI',
 '02824': 'Forestdale, RI',
 '02825': 'Foster, RI',
 '02826': 'Glendale, RI',
 '02827': 'Greene, RI',
 '02828': 'Greenville, RI',
 '02829': 'Harmony, RI',
 '02830': 'Harrisville, RI',
 '02831': 'Hope, RI',
 '02832': 'Hope Valley, RI',
 '02833': 'Hopkinton, RI',
 '02835': 'Jamestown, RI',
 '02836': 'Kenyon, RI',
 '02837': 'Little Compton, RI',
 '02838': 'Manville, RI',
 '02839': 'Mapleville, RI',
 '02840': 'Newport, RI',
 '02841': 'Newport, RI',
 '02842': 'Middletown, RI',
 '02852': 'North Kingstown, RI',
 '02857': 'North Scituate, RI',
 '02858': 'Oakland, RI',
 '02859': 'Pascoag, RI',
 '02860': 'Pawtucket, RI',
 '02861': 'Pawtucket, RI',
 '02862': 'Pawtucket, RI',
 '02863': 'Central Falls, RI',
 '02864': 'Cumberland, RI',
 '02865': 'Lincoln, RI',
 '02871': 'Portsmouth, RI',
 '02872': 'Prudence Island, RI',
 '02873': 'Rockville, RI',
 '02874': 'Saunderstown, RI',
 '02875': 'Shannock, RI',
 '02876': 'Slatersville, RI',
 '02877': 'Slocum, RI',
 '02878': 'Tiverton, RI',

In [1846]:
def lookup_values_by_keys(data_dict, df, key_col, value_col, key_start=0, key_end=5):
    for i,k in df[key_col].iteritems():
        try:
            df.loc[i][value_col]=(data_dict[k[key_start:key_end]])
        except KeyError:
            df.loc[i][value_col]='Key Error'
    return df

def lookup_values_by_keys2(data_dict, df, key_col, keylen=True, key_start=0, key_end=5):
    idx = df.index
    values = []  
    for k in df[key_col]:
        if keylen is False:
            key_end=len(k)
        try:
            values.append(data_dict[k[key_start:key_end]])
        except KeyError:
            values.append(np.nan)
    return pd.Series(values,idx)

cities_found = lookup_values_by_keys2(zip_city_dict, no_city, 'Zip')
US_addresses.loc[cities_found.index,'City']=cities_found
US_addresses.sample(20)

,ClientID,Address,Zip,Country,City
618,US003281,"484 OAKMEAD PARKWAY SUNNYVALE, CA 94085, USA",94085,USA,"Sunnyvale, CA"
2269,US001366,"ONE LOGAN SQUARE, STE. 2000 PHILADELPHIA, PA 1...",19103-6996,USA,"Philadelphia, PA"
1141,US000217,"7229 S. ALTON WAY, CENTENNIAL WAY, COLORADO 80...",80112,USA,"Englewood, CO"
2955,US002068,"10 PALMER AVENUE CROTON ON HUDSON, NY 10520 U....",10520,USA,"Croton On Hudson, NY"
133,US002703,"375 WEST STREET WEST BRIDGEWATER, MASSACHUSETT...",02379,USA,"West Bridgewater, MA"
3318,US002439,"535 MIDDLEFIELD ROAD, STE 280 MENLO PARK, CALI...",94025,USA,"Menlo Park, CA"
1085,US000161,"INTERNATIONAL TOWER, SUITE 1760 S. FIGUEROA .,...",NaN,USA,"Los Angeles, CA"
929,US000005,"150 SOUTH FIFTH STREET SUITE 2200 MINNEAPOLIS,...",55402,USA,"Minneapolis, MN"
3205,US002324,"7070 WINCHESTER CIRCLE BOULDER, COLORADO, 8030...",80301,USA,"Boulder, CO"
1342,US000427,"2006-A WINDY TERRACE, CEDAR PARK, TEXAS, 78613...",78613,USA,"Cedar Park, TX"
462,US003063,"1901 S. BASCOM AVE., SUITE 600 CAMPBELL, CA 95...",95008,USA,"Campbell, CA"
3256,US002375,"6501 WILLIAM CANNON DRIVE WEST, AUSTIN, TX 787...",78735,USA,"Austin, TX"
2726,US001832,"SUITE 300 520 SW. YAMHILL STREET PORTLAND, ORE...",97204,USA,"Portland, OR"
2222,US001317,"4901 KESSLERSVILLE ROAD, EASTON, PENNSYLVANIA,...",18040,USA,"Easton, PA"
1884,US000971,"2463 SOUTH 3850 WEST, SUITE A SALT LAKE CITY, ...",84120,USA,"West Valley City, UT"
3359,US002480,"SUITE 200, MAPLE ISLAND BUILDING 221 MAIN STRE...",55082,USA,"Stillwater, MN"
3600,US002670,"19 BRITISH AMERICAN BLVD. LATHAM, NY 12110, USA",12110,USA,"Latham, NY"
3636,US003560,"701 FIFTH AVENUE, SUITE 4800-SEATTLE, WASHINGT...",98104,USA,"Seattle, WA"
784,US002554,"1 ECOLAB PLACE SAINT PAUL, MINNESOTA 55102 USA",55102,USA,"Saint Paul, MN"
298,US003476,"2725 SAND HILL ROAD SUITE 120 MENLO PARK, CALI...",94025,USA,"Menlo Park, CA"

In [1847]:
'''Finally, check on those cannot find cities'''
no_cities_aft_lookup_by_zip = US_addresses.loc[US_addresses.City.isnull()]
no_cities_aft_lookup_by_zip

,ClientID,Address,Zip,Country,City
178,US002770,"2946 SOUTH WAUKESHA ROAD, WEST ALLIS,WI 53117 USA",53117,USA,NaN
296,US003471,"5 THIRD STREET, SUITE 732 SAN FRANCISCO, CA 94...",94193,USA,NaN
671,US003171,"P.O. BOX 194344 SAN JUAN, PR 00919 USA",00919,USA,NaN
922,US002773,"50 TANNERY ROAD, BRANCHBURG, NJ 08878, USA",08878,USA,NaN
1174,US000252,"BATTLE RUN ROAD, TRIADELPHIA, WEST VIRGINIA 26...",26603,USA,NaN
1385,US000471,"180 DEXTER AVENUE, P.O. BOX 9143, WATERTOWN, M...",02272,USA,NaN
1456,US000542,"1009 WESLEY ROAD, OCEAN CITY, NEW JERSY 07115 USA",07115,USA,NaN
1899,US000986,"304 OLD MAIN STREET, UNIVERSITY PARK, PENNSYLV...",70000,USA,NaN
2039,US001133,"132 N. EL CAMINO REAL #287, ENCINITAS, CALIFOR...",92924,USA,NaN
3376,US002499,"420 CHESTNUT LANE, WESTON, FL 33226 USA",33226,USA,NaN
3575,US003133,"256 ELEANOR ROOSEVELT ST. SAN JUAN, PUERTO RIC...",00918,USA,NaN

In [1848]:
# update manual

no_cities_aft_lookup_by_zip.Address.tolist()

['2946 SOUTH WAUKESHA ROAD, WEST ALLIS,WI 53117 USA',
 '5 THIRD STREET, SUITE 732 SAN FRANCISCO, CA 94193, USA',
 'P.O. BOX 194344 SAN JUAN, PR 00919 USA',
 '50 TANNERY ROAD, BRANCHBURG, NJ 08878, USA',
 'BATTLE RUN ROAD, TRIADELPHIA, WEST VIRGINIA 26603, USA',
 '180 DEXTER AVENUE, P.O. BOX 9143, WATERTOWN, MA 02272, US',
 '1009 WESLEY ROAD, OCEAN CITY, NEW JERSY 07115 USA',
 '304 OLD MAIN STREET, UNIVERSITY PARK, PENNSYLVANIA 16802-70000 USA',
 '132 N. EL CAMINO REAL #287, ENCINITAS, CALIFORNIA 92924 USA',
 '420 CHESTNUT LANE, WESTON, FL 33226 USA',
 '256 ELEANOR ROOSEVELT ST. SAN JUAN, PUERTO RICO 00918 USA']

In [1849]:
#no_cities_aft_lookup_by_zip.Address.str.extract(r"("+regex_country_EN+r")")
no_cities_aft_lookup_by_zip_extracted_city = no_cities_aft_lookup_by_zip.Address.apply(rest_of_str_aft_road_or_unit)
no_cities_aft_lookup_by_zip_extracted_city

178                   WEST ALLIS,WI 53117 USA
296              SAN FRANCISCO, CA 94193, USA
671                    SAN JUAN, PR 00919 USA
922                 BRANCHBURG, NJ 08878, USA
1174    TRIADELPHIA, WEST VIRGINIA 26603, USA
1385                  WATERTOWN, MA 02272, US
1456          OCEAN CITY, NEW JERSY 07115 USA
1899             PENNSYLVANIA 16802-70000 USA
2039          ENCINITAS, CALIFORNIA 92924 USA
3376                                      USA
3575          SAN JUAN, PUERTO RICO 00918 USA
Name: Address, dtype: object

In [1850]:
no_cities_aft_lookup_by_zip_extracted_city = (no_cities_aft_lookup_by_zip_extracted_city
                                              .str.strip()
                                              .str.replace(r"\d+?\W?\d+\,?\s*USA?", '')
                                              .replace(regex_city_dict))

no_cities_aft_lookup_by_zip_extracted_city

178             WEST ALLIS,WI
296          SAN FRANCISCO, CA
671              SAN JUAN, PR
922            BRANCHBURG, NJ
1174          TRIADELPHIA, WV
1385             WATERTOWN, MA
1456    OCEAN CITY, NEW JERSY
1899             PENNSYLVANIA
2039            ENCINITAS, CA
3376                       USA
3575    SAN JUAN, PUERTO RICO
Name: Address, dtype: object

In [1851]:
no_cities_aft_lookup_by_zip.Address.tolist()

['2946 SOUTH WAUKESHA ROAD, WEST ALLIS,WI 53117 USA',
 '5 THIRD STREET, SUITE 732 SAN FRANCISCO, CA 94193, USA',
 'P.O. BOX 194344 SAN JUAN, PR 00919 USA',
 '50 TANNERY ROAD, BRANCHBURG, NJ 08878, USA',
 'BATTLE RUN ROAD, TRIADELPHIA, WEST VIRGINIA 26603, USA',
 '180 DEXTER AVENUE, P.O. BOX 9143, WATERTOWN, MA 02272, US',
 '1009 WESLEY ROAD, OCEAN CITY, NEW JERSY 07115 USA',
 '304 OLD MAIN STREET, UNIVERSITY PARK, PENNSYLVANIA 16802-70000 USA',
 '132 N. EL CAMINO REAL #287, ENCINITAS, CALIFORNIA 92924 USA',
 '420 CHESTNUT LANE, WESTON, FL 33226 USA',
 '256 ELEANOR ROOSEVELT ST. SAN JUAN, PUERTO RICO 00918 USA']

In [1852]:
'''Save to US_addresses'''
US_addresses.loc[no_cities_aft_lookup_by_zip.index,'City']=no_cities_aft_lookup_by_zip_extracted_city
US_addresses.loc[3376,'City']='Weston, FL'
US_addresses.loc[3376,'Zip']='33326'

In [1853]:
US_addresses.loc[US_addresses.City.isnull()]

Empty DataFrame
Columns: [ClientID, Address, Zip, Country, City]
Index: []

In [1854]:
US_addresses[US_addresses.City.str.contains('USA')]

Empty DataFrame
Columns: [ClientID, Address, Zip, Country, City]
Index: []

In [1855]:
'''Review those without zip to catch remaining errors'''
US_addresses.loc[US_addresses.Zip.isnull()]

,ClientID,Address,Zip,Country,City
72,US002913,"333 CENTENNIAL PARKWAY SUITE B LOUISVILLE, CO USA",NaN,USA,"LOUISVILLE, CO"
238,US002809,"LAGUNA NIGUEL, CA USA",NaN,USA,"LAGUNA NIGUEL, CA"
239,US002810,"LAGUNA HILLS, CA USA",NaN,USA,"LAGUNA HILLS, CA"
283,US003046,DELAWARE USA,NaN,USA,DE
284,US003048,"1434 AIR RAIL AVENUE VIRGINIA BEACH, VA USA",NaN,USA,"VIRGINIA BEACH, VA"
305,US003485,"57 SEAVIEW BOULEVARD PORT WASHINGTON,NY U.S.A.",NaN,USA,"PORT WASHINGTON,NY"
336,US002977,"NORTH CAROLINA, USA",NaN,USA,NC
337,US002963,ROCKWALL TEXAS UNITED STATES OF AMERICA,NaN,USA,"ROCKWALL, TX"
338,US002964,ROCKWALL TEXAS UNITED STATES OF AMERICA,NaN,USA,"ROCKWALL, TX"
379,US002965,"3472 88TH AVENUE NE CIRCLE PINES, MN USA",NaN,USA,"CIRCLE PINES, MN"
396,US003542,"1613 PINEVIEW DRIVE RALEIGH, NORTH CAROLINA UN...",NaN,USA,"RALEIGH, NC"
399,US003544,"1401 CROOKS ROAD, TROY, MICHIGAN USA",NaN,USA,"TROY, MI"
474,US003072,"941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA",NaN,USA,"CAMARILLO, CA"
520,US002961,SAN DIEGO USA,NaN,USA,"SAN DIEGO, CA"
589,US003247,"10 SAINT JAMES AVENUE, 11TH FLOOR | BOSTON, MA...",NaN,USA,"BOSTON, MA"
613,US003269,TEXAS USA,NaN,USA,TX
665,US003143,"PLYMOUTH, MN USA",NaN,USA,"PLYMOUTH, MN"
696,US003215,"BURNSVILLE, MN USA",NaN,USA,"BURNSVILLE, MN"
763,US002527,"3411 SILVERSIDE RD., RODNEY BLDG. SUITE 104, W...",NaN,USA,"WILMINGTON, DE"
892,US003394,"941 AVENIDA ACASO, CAMARILLO, CALIFORNIA, USA",NaN,USA,"CAMARILLO, CA"
974,US000050,"9000 CROW CANYON ROAD, SUITE S393, DANVILLE, C...",NaN,USA,DANVILLE CA
1071,US000147,IN. U.S.A.,NaN,USA,IN
1085,US000161,"INTERNATIONAL TOWER, SUITE 1760 S. FIGUEROA .,...",NaN,USA,"Los Angeles, CA"
1288,US000373,"DELAWARE, U.S.A.",NaN,USA,DE
1351,US000436,"810 VERMONT AVENUE N. W., WASHINGTON, D. C. 20...",NaN,USA,"Washington, DC"
1776,US000862,美国加州新港海滨詹伯瑞路4311号,NaN,USA,"NEW PORT, CA"
1895,US000982,"301 MERRITT 7, NORWALK, CONNECTICUT UNITED STA...",NaN,USA,"NORWALK, CT"
2224,US001319,"2711 CENTERVILLE ROAD, SUITE 400, CITY OF WILM...",NaN,USA,"WILMINGTON, DE"
2234,US001330,"WASHINGTON, DISTRICT OF COLUMBIA USA",NaN,USA,"WASHINGTON, DC"
2306,US001403,"225 INDUSTRIAL DRIVE SALINE, MICHIGAN UNITED S...",NaN,USA,"SALINE, MI"
2365,US001463,美国 加州 佛利蒙 利马街51号,NaN,USA,"NEW PORT, CA"
2447,US001545,"6444 SOUTH 6TH STREET ROAD SPRINGFIELD, ILLINO...",NaN,USA,"SPRINGFIELD, IL"
2709,US001815,"2 WARE STREET, APT. 507, CAMBRIDGE, MASSACHUSE...",NaN,USA,"CAMBRIDGE, MA"
2812,US001922,"330 BLAISDELL ROAD ORANGEBURG, NEW YORK 0962, ...",NaN,USA,"Orangeburg, NY"
2887,US002000,"15025 SW KOLL PARKWAY BEAVERTON, OREGON UNITED...",NaN,USA,"BEAVERTON, OR"
2888,US002001,"150 NORTH MARTINGALE ROAD, SCHAUMBURG, ILLINOI...",NaN,USA,"SCHAUMBURG, IL"
2944,US002057,OFFICE OF TECHNOLOGY TRANSFER & ECONOMIC DEVEL...,NaN,USA,"Honolulu, HI"
2981,US002094,"8905 S.W. 87TH AVENUE, MIAMI, USA",NaN,USA,"MIAMI, FL"
2993,US002106,DELAWARE USA,NaN,USA,DE
3179,US002297,AUSTIN TEXAS USA,NaN,USA,"AUSTIN, TX"
3208,US002327,"103 CARNEGIE CENTER, SUITE 300, PRINCETON, NJ USA",NaN,USA,"PRINCETON, NJ"
3313,US002434,"340 GREEN OAKS LANE, SOUTHLAKE, TX USA",NaN,USA,"SOUTHLAKE, TX"
3368,US002489,5 PEARL COURT ALLENDALE PARK NEW JERSEY USA,NaN,USA,"ALLENDALE, NJ"
3411,US003480,"101 PEAVEY ROAD CHASKA, MINNESOTA US",NaN,USA,"CHASKA, MN"
3448,US002712,"CALIFORNIA, USA",NaN,USA,"VAN NUYS, CA"
3515,US003080,"PACIFIC PALISADES, CALIFORNIA USA",NaN,USA,"PACIFIC PALISADES, CA"
3516,US003081,"LOS ANGELES, CALIFORNIA USA",NaN,USA,"LOS ANGELES, CA"

In [1856]:
'''Match all the cities with standard formatting'''
US_addresses.loc[US_addresses.Zip.isnull(),'City'].replace(regex_city_dict,inplace=True)
US_addresses.loc[US_addresses.Zip.isnull(),'City']

72             LOUISVILLE, CO
238         LAGUNA NIGUEL, CA
239          LAGUNA HILLS, CA
283                        DE
284        VIRGINIA BEACH, VA
305        PORT WASHINGTON,NY
336                        NC
337              ROCKWALL, TX
338              ROCKWALL, TX
379          CIRCLE PINES, MN
396               RALEIGH, NC
399                  TROY, MI
474             CAMARILLO, CA
520             SAN DIEGO, CA
589                BOSTON, MA
613                        TX
665              PLYMOUTH, MN
696            BURNSVILLE, MN
763            WILMINGTON, DE
892             CAMARILLO, CA
974               DANVILLE CA
1071                       IN
1085          Los Angeles, CA
1288                       DE
1351           Washington, DC
1776             NEW PORT, CA
1895              NORWALK, CT
2224           WILMINGTON, DE
2234           WASHINGTON, DC
2306               SALINE, MI
2365             NEW PORT, CA
2447          SPRINGFIELD, IL
2709            CAMBRIDGE, MA
2812           Orangeburg, NY
2887            BEAVERTON, OR
2888           SCHAUMBURG, IL
2944             Honolulu, HI
2981                MIAMI, FL
2993                       DE
3179               AUSTIN, TX
3208            PRINCETON, NJ
3313            SOUTHLAKE, TX
3368            ALLENDALE, NJ
3411               CHASKA, MN
3448             VAN NUYS, CA
3515    PACIFIC PALISADES, CA
3516          LOS ANGELES, CA
Name: City, dtype: object

In [1857]:
'''Add zips through look up by cities'''
cities_from_zipcodes = zipcodes['Place Name'].str.upper()+ ', '+zipcodes['State_Abbr']
city_zip_dict = dict(zip(cities_from_zipcodes, zipcodes['Zip Code']))
city_zip_dict

{'HOLTSVILLE, NY': '11742',
 'AGAWAM, MA': '01001',
 'AMHERST, MA': '01004',
 'BARRE, MA': '01005',
 'BELCHERTOWN, MA': '01007',
 'BLANDFORD, MA': '01008',
 'BONDSVILLE, MA': '01009',
 'BRIMFIELD, MA': '01010',
 'CHESTER, MA': '01011',
 'CHESTERFIELD, MA': '01012',
 'CHICOPEE, MA': '01022',
 'CUMMINGTON, MA': '01026',
 'EASTHAMPTON, MA': '01027',
 'EAST LONGMEADOW, MA': '01028',
 'EAST OTIS, MA': '01029',
 'FEEDING HILLS, MA': '01030',
 'GILBERTVILLE, MA': '01031',
 'GOSHEN, MA': '01032',
 'GRANBY, MA': '01033',
 'GRANVILLE, MA': '01034',
 'HADLEY, MA': '01035',
 'HAMPDEN, MA': '01036',
 'HARDWICK, MA': '01037',
 'HATFIELD, MA': '01038',
 'HAYDENVILLE, MA': '01039',
 'HOLYOKE, MA': '01041',
 'HUNTINGTON, MA': '01050',
 'LEEDS, MA': '01053',
 'LEVERETT, MA': '01054',
 'LUDLOW, MA': '01056',
 'MONSON, MA': '01057',
 'NORTH AMHERST, MA': '01059',
 'NORTHAMPTON, MA': '01063',
 'FLORENCE, MA': '01062',
 'NORTH HATFIELD, MA': '01066',
 'OAKHAM, MA': '01068',
 'PALMER, MA': '01069',
 'PLAINFIELD, MA': '01070',
 'RUSSELL, MA': '01071',
 'SHUTESBURY, MA': '01072',
 'SOUTHAMPTON, MA': '01073',
 'SOUTH BARRE, MA': '01074',
 'SOUTH HADLEY, MA': '01075',
 'SOUTHWICK, MA': '01077',
 'THORNDIKE, MA': '01079',
 'THREE RIVERS, MA': '01080',
 'WALES, MA': '01081',
 'WARE, MA': '01082',
 'WARREN, MA': '01083',
 'WEST CHESTERFIELD, MA': '01084',
 'WESTFIELD, MA': '01086',
 'WEST HATFIELD, MA': '01088',
 'WEST SPRINGFIELD, MA': '01090',
 'WEST WARREN, MA': '01092',
 'WHATELY, MA': '01093',
 'WHEELWRIGHT, MA': '01094',
 'WILBRAHAM, MA': '01095',
 'WILLIAMSBURG, MA': '01096',
 'WORONOCO, MA': '01097',
 'WORTHINGTON, MA': '01098',
 'SPRINGFIELD, MA': '01199',
 'LONGMEADOW, MA': '01116',
 'INDIAN ORCHARD, MA': '01151',
 'PITTSFIELD, MA': '01203',
 'ADAMS, MA': '01220',
 'ASHLEY FALLS, MA': '01222',
 'BECKET, MA': '01223',
 'BERKSHIRE, MA': '01224',
 'CHESHIRE, MA': '01225',
 'DALTON, MA': '01227',
 'GLENDALE, MA': '01229',
 'GREAT BARRINGTON, MA': '01230',
 'HINSDALE, MA': '01235',
 'HOUSATONIC, MA': '01236',
 'LANESBOROUGH, MA': '01237',
 'LEE, MA': '01238',
 'LENOX, MA': '01240',
 'LENOX DALE, MA': '01242',
 'MIDDLEFIELD, MA': '01243',
 'MILL RIVER, MA': '01244',
 'MONTEREY, MA': '01245',
 'NORTH ADAMS, MA': '01247',
 'NORTH EGREMONT, MA': '01252',
 'OTIS, MA': '01253',
 'RICHMOND, MA': '01254',
 'SANDISFIELD, MA': '01255',
 'SAVOY, MA': '01256',
 'SHEFFIELD, MA': '01257',
 'SOUTH EGREMONT, MA': '01258',
 'SOUTHFIELD, MA': '01259',
 'SOUTH LEE, MA': '01260',
 'STOCKBRIDGE, MA': '01263',
 'TYRINGHAM, MA': '01264',
 'WEST STOCKBRIDGE, MA': '01266',
 'WILLIAMSTOWN, MA': '01267',
 'WINDSOR, MA': '01270',
 'GREENFIELD, MA': '01302',
 'ASHFIELD, MA': '01330',
 'ATHOL, MA': '01331',
 'BERNARDSTON, MA': '01337',
 'BUCKLAND, MA': '01338',
 'CHARLEMONT, MA': '01339',
 'COLRAIN, MA': '01340',
 'CONWAY, MA': '01341',
 'DEERFIELD, MA': '01342',
 'DRURY, MA': '01343',
 'ERVING, MA': '01344',
 'HEATH, MA': '01346',
 'LAKE PLEASANT, MA': '01347',
 'MILLERS FALLS, MA': '01349',
 'MONROE BRIDGE, MA': '01350',
 'MONTAGUE, MA': '01351',
 'GILL, MA': '01354',
 'NEW SALEM, MA': '01355',
 'NORTHFIELD, MA': '01360',
 'ORANGE, MA': '01364',
 'PETERSHAM, MA': '01366',
 'ROWE, MA': '01367',
 'ROYALSTON, MA': '01368',
 'SHELBURNE FALLS, MA': '01370',
 'SOUTH DEERFIELD, MA': '01373',
 'SUNDERLAND, MA': '01375',
 'TURNERS FALLS, MA': '01376',
 'WARWICK, MA': '01378',
 'WENDELL, MA': '01379',
 'WENDELL DEPOT, MA': '01380',
 'FITCHBURG, MA': '01420',
 'ASHBURNHAM, MA': '01430',
 'ASHBY, MA': '01431',
 'AYER, MA': '01432',
 'DEVENS, MA': '01434',
 'BALDWINVILLE, MA': '01436',
 'EAST TEMPLETON, MA': '01438',
 'GARDNER, MA': '01440',
 'WESTMINSTER, MA': '01473',
 'GROTON, MA': '01471',
 'HARVARD, MA': '01451',
 'HUBBARDSTON, MA': '01452',
 'LEOMINSTER, MA': '01453',
 'LITTLETON, MA': '01460',
 'LUNENBURG, MA': '01462',
 'PEPPERELL, MA': '01463',
 'SHIRLEY, MA': '01464',
 'STILL RIVER, MA': '01467',
 'TEMPLETON, MA': '01468',
 'TOWNSEND, MA': '01469',
 'WEST GROTON, MA': '01472',
 'WEST TOWNSEND, MA': '01474',
 'WINCHENDON, MA': '01475',
 'AUBURN, MA': '01501',
 'BERLIN, MA': '01503',
 'BLACKSTONE, MA': '01504',
 'BOYLSTON, MA': '01505',
 'BROOKFIELD, MA': '01506',
 'CHARLTON, MA': '01507',
 'CHARLTON CITY, MA': '01508',
 'CHARLTON DEPOT, MA': '01509',
 'CLINTON, MA': '01510',
 'EAST BROOKFIELD, MA': '01515',
 'DOUGLAS, MA': '01516',
 'FISKDALE, MA': '01518',
 'GRAFTON, MA': '01519',
 'HOLDEN, MA': '01520',
 'HOLLAND, MA': '01521',
 'JEFFERSON, MA': '01522',
 'LANCASTER, MA': '01523',
 'LEICESTER, MA': '01524',
 'LINWOOD, MA': '01525',
 'MANCHAUG, MA': '01526',
 'MILLBURY, MA': '01527',
 'MILLVILLE, MA': '01529',
 'NEW BRAINTREE, MA': '01531',
 'NORTHBOROUGH, MA': '01532',
 'NORTHBRIDGE, MA': '01534',
 'NORTH BROOKFIELD, MA': '01535',
 'NORTH GRAFTON, MA': '01536',
 'NORTH OXFORD, MA': '01537',
 'NORTH UXBRIDGE, MA': '01538',
 'OXFORD, MA': '01540',
 'PRINCETON, MA': '01541',
 'ROCHDALE, MA': '01542',
 'RUTLAND, MA': '01543',
 'SHREWSBURY, MA': '01546',
 'SOUTHBRIDGE, MA': '01550',
 'SOUTH GRAFTON, MA': '01560',
 'SOUTH LANCASTER, MA': '01561',
 'SPENCER, MA': '01562',
 'STERLING, MA': '01564',
 'STURBRIDGE, MA': '01566',
 'UPTON, MA': '01568',
 'UXBRIDGE, MA': '01569',
 'WEBSTER, MA': '01570',
 'DUDLEY, MA': '01571',
 'WESTBOROUGH, MA': '01581',
 'WEST BOYLSTON, MA': '01583',
 'WEST BROOKFIELD, MA': '01585',
 'WEST MILLBURY, MA': '01586',
 'WHITINSVILLE, MA': '01588',
 'SUTTON, MA': '01590',
 'WORCESTER, MA': '01655',
 'CHERRY VALLEY, MA': '01611',
 'PAXTON, MA': '01612',
 'FRAMINGHAM, MA': '01705',
 'ACTON, MA': '01720',
 'BOXBOROUGH, MA': '01719',
 'ASHLAND, MA': '01721',
 'BEDFORD, MA': '01730',
 'HANSCOM AFB, MA': '01731',
 'BOLTON, MA': '01740',
 'CARLISLE, MA': '01741',
 'CONCORD, MA': '01742',
 'FAYVILLE, MA': '01745',
 'HOLLISTON, MA': '01746',
 'HOPEDALE, MA': '01747',
 'HOPKINTON, MA': '01748',
 'HUDSON, MA': '01749',
 'MARLBOROUGH, MA': '01752',
 'MAYNARD, MA': '01754',
 'MENDON, MA': '01756',
 'MILFORD, MA': '01757',
 'NATICK, MA': '01760',
 'SHERBORN, MA': '01770',
 'SOUTHBOROUGH, MA': '01772',
 'LINCOLN, MA': '01773',
 'STOW, MA': '01775',
 'SUDBURY, MA': '01776',
 'WAYLAND, MA': '01778',
 'WOODVILLE, MA': '01784',
 'WOBURN, MA': '01888',
 'BURLINGTON, MA': '01805',
 'ANDOVER, MA': '05544',
 'BILLERICA, MA': '01822',
 'CHELMSFORD, MA': '01824',
 'DRACUT, MA': '01826',
 'DUNSTABLE, MA': '01827',
 'HAVERHILL, MA': '01835',
 'GEORGETOWN, MA': '01833',
 'GROVELAND, MA': '01834',
 'LAWRENCE, MA': '01843',
 'METHUEN, MA': '01844',
 'NORTH ANDOVER, MA': '01845',
 'LOWELL, MA': '01854',
 'MERRIMAC, MA': '01860',
 'NORTH BILLERICA, MA': '01862',
 'NORTH CHELMSFORD, MA': '01863',
 'NORTH READING, MA': '01889',
 'NUTTING LAKE, MA': '01865',
 'PINEHURST, MA': '01866',
 'READING, MA': '01867',
 'TEWKSBURY, MA': '01876',
 'TYNGSBORO, MA': '01879',
 'WAKEFIELD, MA': '01880',
 'WEST BOXFORD, MA': '01885',
 'WESTFORD, MA': '01886',
 'WILMINGTON, MA': '01887',
 'WINCHESTER, MA': '01890',
 'LYNN, MA': '01910',
 'SAUGUS, MA': '01906',
 'SWAMPSCOTT, MA': '01907',
 'NAHANT, MA': '01908',
 'AMESBURY, MA': '01913',
 'BEVERLY, MA': '01915',
 'BOXFORD, MA': '01921',
 'BYFIELD, MA': '01922',
 'DANVERS, MA': '01923',
 'ESSEX, MA': '01929',
 'GLOUCESTER, MA': '01931',
 'HAMILTON, MA': '01936',
 'HATHORNE, MA': '01937',
 'IPSWICH, MA': '01938',
 'LYNNFIELD, MA': '01940',
 'MANCHESTER, MA': '01944',
 'MARBLEHEAD, MA': '01945',
 'MIDDLETON, MA': '01949',
 'NEWBURYPORT, MA': '01950',
 'NEWBURY, MA': '01951',
 'SALISBURY, MA': '01952',
 'PEABODY, MA': '01961',
 'PRIDES CROSSING, MA': '01965',
 'ROCKPORT, MA': '01966',
 'ROWLEY, MA': '01969',
 'SALEM, MA': '01971',
 'SOUTH HAMILTON, MA': '01982',
 'TOPSFIELD, MA': '01983',
 'WENHAM, MA': '01984',
 'WEST NEWBURY, MA': '01985',
 'ACCORD, MA': '02018',
 'BELLINGHAM, MA': '02019',
 'BRANT ROCK, MA': '02020',
 'CANTON, MA': '02021',
 'COHASSET, MA': '02025',
 'DEDHAM, MA': '02027',
 'DOVER, MA': '02030',
 'EAST WALPOLE, MA': '02032',
 'FOXBORO, MA': '02035',
 'FRANKLIN, MA': '02038',
 'GREENBUSH, MA': '02040',
 'GREEN HARBOR, MA': '02041',
 'HINGHAM, MA': '02044',
 'HULL, MA': '02045',
 'HUMAROCK, MA': '02047',
 'MANSFIELD, MA': '02048',
 'MARSHFIELD, MA': '02050',
 'MARSHFIELD HILLS, MA': '02051',
 'MEDFIELD, MA': '02052',
 'MEDWAY, MA': '02053',
 'MILLIS, MA': '02054',
 'MINOT, MA': '02055',
 'NORFOLK, MA': '02056',
 'NORTH MARSHFIELD, MA': '02059',
 'NORTH SCITUATE, MA': '02060',
 'NORWELL, MA': '02061',
 'NORWOOD, MA': '02062',
 'OCEAN BLUFF, MA': '02065',
 'SCITUATE, MA': '02066',
 'SHARON, MA': '02067',
 'SHELDONVILLE, MA': '02070',
 'SOUTH WALPOLE, MA': '02071',
 'STOUGHTON, MA': '02072',
 'WALPOLE, MA': '02081',
 'WESTWOOD, MA': '02090',
 'WRENTHAM, MA': '02093',
 'BOSTON, MA': '02298',
 'ROXBURY, MA': '02119',
 'ROXBURY CROSSING, MA': '02120',
 'DORCHESTER, MA': '02125',
 'DORCHESTER CENTER, MA': '02124',
 'MATTAPAN, MA': '02126',
 'CHARLESTOWN, MA': '02129',
 'JAMAICA PLAIN, MA': '02130',
 'ROSLINDALE, MA': '02131',
 'WEST ROXBURY, MA': '02132',
 'ALLSTON, MA': '02134',
 'BRIGHTON, MA': '02135',
 'HYDE PARK, MA': '02136',
 'READVILLE, MA': '02137',
 'CAMBRIDGE, MA': '02238',
 'SOMERVILLE, MA': '02145',
 'MALDEN, MA': '02148',
 'EVERETT, MA': '02149',
 'CHELSEA, MA': '02150',
 'REVERE, MA': '02151',
 'WINTHROP, MA': '02152',
 'MEDFORD, MA': '02155',
 'WEST MEDFORD, MA': '02156',
 'QUINCY, MA': '02269',
 'MELROSE, MA': '02176',
 'STONEHAM, MA': '02180',
 'BRAINTREE, MA': '02185',
 'MILTON, MA': '02186',
 'MILTON VILLAGE, MA': '02187',
 'WEYMOUTH, MA': '02188',
 'EAST WEYMOUTH, MA': '02189',
 'SOUTH WEYMOUTH, MA': '02190',
 'NORTH WEYMOUTH, MA': '02191',
 'BROCKTON, MA': '02305',
 'AVON, MA': '02322',
 'BRIDGEWATER, MA': '02325',
 'BRYANTVILLE, MA': '02327',
 'CARVER, MA': '02330',
 'DUXBURY, MA': '02332',
 'EAST BRIDGEWATER, MA': '02333',
 'EASTON, MA': '02334',
 'ELMWOOD, MA': '02337',
 'HALIFAX, MA': '02338',
 'HANOVER, MA': '02340',
 'HANSON, MA': '02341',
 'HOLBROOK, MA': '02343',
 'MIDDLEBORO, MA': '02349',
 'MANOMET, MA': '02345',
 'LAKEVILLE, MA': '02348',
 'MONPONSETT, MA': '02350',
 'ABINGTON, MA': '02351',
 'NORTH CARVER, MA': '02355',
 'NORTH EASTON, MA': '02357',
 'NORTH PEMBROKE, MA': '02358',
 'PEMBROKE, MA': '02359',
 'PLYMOUTH, MA': '02362',
 'KINGSTON, MA': '02364',
 'SOUTH CARVER, MA': '02366',
 'PLYMPTON, MA': '02367',
 'RANDOLPH, MA': '02368',
 'ROCKLAND, MA': '02370',
 'SOUTH EASTON, MA': '02375',
 'WEST BRIDGEWATER, MA': '02379',
 'WHITE HORSE BEACH, MA': '02381',
 'WHITMAN, MA': '02382',
 'LEXINGTON, MA': '02421',
 'BROOKLINE, MA': '02446',
 'BROOKLINE VILLAGE, MA': '02447',
 'WALTHAM, MA': '02454',
 'NORTH WALTHAM, MA': '02455',
 'NEW TOWN, MA': '02456',
 'BABSON PARK, MA': '02457',
 'NEWTON, MA': '02458',
 'NEWTON CENTER, MA': '02459',
 'NEWTONVILLE, MA': '02460',
 'NEWTON HIGHLANDS, MA': '02461',
 'NEWTON LOWER FALLS, MA': '02462',
 'NEWTON UPPER FALLS, MA': '02464',
 'WEST NEWTON, MA': '02465',
 'AUBURNDALE, MA': '02466',
 'CHESTNUT HILL, MA': '02467',
 'WABAN, MA': '02468',
 'WATERTOWN, MA': '02477',
 'ARLINGTON, MA': '02476',
 'ARLINGTON HEIGHTS, MA': '02475',
 'BELMONT, MA': '02478',
 'WAVERLEY, MA': '02479',
 'WELLESLEY HILLS, MA': '02481',
 'WELLESLEY, MA': '02482',
 'NEEDHAM, MA': '02492',
 'WESTON, MA': '02493',
 'NEEDHAM HEIGHTS, MA': '02494',
 'NONANTUM, MA': '02495',
 'BUZZARDS BAY, MA': '02542',
 'CATAUMET, MA': '02534',
 'CHILMARK, MA': '02535',
 'EAST FALMOUTH, MA': '02536',
 'EAST SANDWICH, MA': '02537',
 'EAST WAREHAM, MA': '02538',
 'EDGARTOWN, MA': '02539',
 'FALMOUTH, MA': '02541',
 'WOODS HOLE, MA': '02543',
 'MENEMSHA, MA': '02552',
 'MONUMENT BEACH, MA': '02553',
 'NANTUCKET, MA': '02584',
 'NORTH FALMOUTH, MA': '02556',
 'OAK BLUFFS, MA': '02557',
 'ONSET, MA': '02558',
 'POCASSET, MA': '02559',
 'SAGAMORE, MA': '02561',
 'SAGAMORE BEACH, MA': '02562',
 'SANDWICH, MA': '02563',
 'SIASCONSET, MA': '02564',
 'VINEYARD HAVEN, MA': '02568',
 'WAREHAM, MA': '02571',
 'WEST FALMOUTH, MA': '02574',
 'WEST TISBURY, MA': '02575',
 'WEST WAREHAM, MA': '02576',
 'HYANNIS, MA': '02601',
 'BARNSTABLE, MA': '02630',
 'BREWSTER, MA': '02631',
 'CENTERVILLE, MA': '02634',
 'CHATHAM, MA': '02633',
 'COTUIT, MA': '02635',
 'CUMMAQUID, MA': '02637',
 'DENNIS, MA': '02638',
 'DENNIS PORT, MA': '02639',
 'EAST DENNIS, MA': '02641',
 'EASTHAM, MA': '02642',
 'EAST ORLEANS, MA': '02643',
 'FORESTDALE, MA': '02644',
 'HARWICH, MA': '02645',
 'HARWICH PORT, MA': '02646',
 'HYANNIS PORT, MA': '02647',
 'MARSTONS MILLS, MA': '02648',
 'MASHPEE, MA': '02649',
 'NORTH CHATHAM, MA': '02650',
 'NORTH EASTHAM, MA': '02651',
 'NORTH TRURO, MA': '02652',
 'ORLEANS, MA': '02653',
 'OSTERVILLE, MA': '02655',
 'PROVINCETOWN, MA': '02657',
 'SOUTH CHATHAM, MA': '02659',
 'SOUTH DENNIS, MA': '02660',
 'SOUTH HARWICH, MA': '02661',
 'SOUTH ORLEANS, MA': '02662',
 'SOUTH WELLFLEET, MA': '02663',
 'SOUTH YARMOUTH, MA': '02664',
 'TRURO, MA': '02666',
 'WELLFLEET, MA': '02667',
 'WEST BARNSTABLE, MA': '02668',
 'WEST CHATHAM, MA': '02669',
 'WEST DENNIS, MA': '02670',
 'WEST HARWICH, MA': '02671',
 'WEST HYANNISPORT, MA': '02672',
 'WEST YARMOUTH, MA': '02673',
 'YARMOUTH PORT, MA': '02675',
 'ASSONET, MA': '02702',
 'ATTLEBORO, MA': '02703',
 'CHARTLEY, MA': '02712',
 'CUTTYHUNK, MA': '02713',
 'DARTMOUTH, MA': '02714',
 'DIGHTON, MA': '02715',
 'EAST FREETOWN, MA': '02717',
 'EAST TAUNTON, MA': '02718',
 'FAIRHAVEN, MA': '02719',
 'FALL RIVER, MA': '02724',
 'SOMERSET, MA': '02726',
 'MARION, MA': '02738',
 'MATTAPOISETT, MA': '02739',
 'NEW BEDFORD, MA': '02746',
 'ACUSHNET, MA': '02743',
 'NORTH DARTMOUTH, MA': '02747',
 'SOUTH DARTMOUTH, MA': '02748',
 'NORTH ATTLEBORO, MA': '02761',
 'PLAINVILLE, MA': '02762',
 'ATTLEBORO FALLS, MA': '02763',
 'NORTH DIGHTON, MA': '02764',
 'NORTON, MA': '02766',
 'RAYNHAM, MA': '02767',
 'RAYNHAM CENTER, MA': '02768',
 'REHOBOTH, MA': '02769',
 'ROCHESTER, MA': '02770',
 'SEEKONK, MA': '02771',
 'SWANSEA, MA': '02777',
 'BERKLEY, MA': '02779',
 'TAUNTON, MA': '02783',
 'WESTPORT, MA': '02790',
 'WESTPORT POINT, MA': '02791',
 'ADAMSVILLE, RI': '02801',
 'ALBION, RI': '02802',
 'ASHAWAY, RI': '02804',
 'BARRINGTON, RI': '02806',
 'BLOCK ISLAND, RI': '02807',
 'BRADFORD, RI': '02808',
 'BRISTOL, RI': '02809',
 'CAROLINA, RI': '02812',
 'CHARLESTOWN, RI': '02813',
 'CHEPACHET, RI': '02814',
 'CLAYVILLE, RI': '02815',
 'COVENTRY, RI': '02816',
 'WEST GREENWICH, RI': '02817',
 'EAST GREENWICH, RI': '02818',
 'EXETER, RI': '02822',
 'FISKEVILLE, RI': '02823',
 'FORESTDALE, RI': '02824',
 'FOSTER, RI': '02825',
 'GLENDALE, RI': '02826',
 'GREENE, RI': '02827',
 'GREENVILLE, RI': '02828',
 'HARMONY, RI': '02829',
 'HARRISVILLE, RI': '02830',
 'HOPE, RI': '02831',
 'HOPE VALLEY, RI': '02832',
 'HOPKINTON, RI': '02833',
 'JAMESTOWN, RI': '02835',
 'KENYON, RI': '02836',
 'LITTLE COMPTON, RI': '02837',
 'MANVILLE, RI': '02838',
 'MAPLEVILLE, RI': '02839',
 'NEWPORT, RI': '02841',
 'MIDDLETOWN, RI': '02842',
 'NORTH KINGSTOWN, RI': '02852',
 'NORTH SCITUATE, RI': '02857',
 'OAKLAND, RI': '02858',
 'PASCOAG, RI': '02859',
 'PAWTUCKET, RI': '02862',
 'CENTRAL FALLS, RI': '02863',
 'CUMBERLAND, RI': '02864',
 'LINCOLN, RI': '02865',
 'PORTSMOUTH, RI': '02871',
 'PRUDENCE ISLAND, RI': '02872',
 'ROCKVILLE, RI': '02873',
 'SAUNDERSTOWN, RI': '02874',
 'SHANNOCK, RI': '02875',
 'SLATERSVILLE, RI': '02876',
 'SLOCUM, RI': '02877',
 'TIVERTON, RI': '02878',
 'WAKEFIELD, RI': '02880',
 'KINGSTON, RI': '02881',
 'NARRAGANSETT, RI': '02882',
 'PEACE DALE, RI': '02883',
 'WARREN, RI': '02885',
 'WARWICK, RI': '02889',
 'WESTERLY, RI': '02891',
 'WEST KINGSTON, RI': '02892',
 'WEST WARWICK, RI': '02893',
 'WOOD RIVER JUNCTION, RI': '02894',
 'WOONSOCKET, RI': '02895',
 'NORTH SMITHFIELD, RI': '02896',
 'WYOMING, RI': '02898',
 'PROVIDENCE, RI': '02940',
 'CRANSTON, RI': '02921',
 'NORTH PROVIDENCE, RI': '02911',
 'EAST PROVIDENCE, RI': '02914',
 'RIVERSIDE, RI': '02915',
 'RUMFORD, RI': '02916',
 'SMITHFIELD, RI': '02917',
 'JOHNSTON, RI': '02919',
 'AMHERST, NH': '03031',
 'AUBURN, NH': '03032',
 'BROOKLINE, NH': '03033',
 'CANDIA, NH': '03034',
 'CHESTER, NH': '03036',
 'DEERFIELD, NH': '03037',
 'DERRY, NH': '03038',
 'EAST CANDIA, NH': '03040',
 'EAST DERRY, NH': '03041',
 'EPPING, NH': '03042',
 'FRANCESTOWN, NH': '03043',
 'FREMONT, NH': '03044',
 'GOFFSTOWN, NH': '03045',
 'DUNBARTON, NH': '03046',
 'GREENFIELD, NH': '03047',
 'GREENVILLE, NH': '03048',
 'HOLLIS, NH': '03049',
 'HUDSON, NH': '03051',
 'LITCHFIELD, NH': '03052',
 'LONDONDERRY, NH': '03053',
 'MERRIMACK, NH': '03054',
 'MILFORD, NH': '03055',
 'MONT VERNON, NH': '03057',
 'NASHUA, NH': '03064',
 'NEW BOSTON, NH': '03070',
 'NEW IPSWICH, NH': '03071',
 'NORTH SALEM, NH': '03073',
 'PELHAM, NH': '03076',
 'RAYMOND, NH': '03077',
 'SALEM, NH': '03079',
 'LYNDEBOROUGH, NH': '03082',
 'TEMPLE, NH': '03084',
 'WILTON, NH': '03086',
 'WINDHAM, NH': '03087',
 'MANCHESTER, NH': '03111',
 'HOOKSETT, NH': '03106',
 'BEDFORD, NH': '03110',
 'WATERVILLE VALLEY, NH': '03215',
 'ANDOVER, NH': '03216',
 'ASHLAND, NH': '03217',
 'BARNSTEAD, NH': '03218',
 'BELMONT, NH': '03220',
 'BRADFORD, NH': '03221',
 'BRISTOL, NH': '03222',
 'CAMPTON, NH': '03223',
 'CANTERBURY, NH': '03224',
 'CENTER BARNSTEAD, NH': '03225',
 'CENTER HARBOR, NH': '03226',
 'CENTER SANDWICH, NH': '03227',
 'CONTOOCOOK, NH': '03229',
 'DANBURY, NH': '03230',
 'EAST ANDOVER, NH': '03231',
 'ELKINS, NH': '03233',
 'EPSOM, NH': '03234',
 'FRANKLIN, NH': '03235',
 'GILMANTON, NH': '03237',
 'GLENCLIFF, NH': '03238',
 'GRAFTON, NH': '03240',
 'HEBRON, NH': '03241',
 'HENNIKER, NH': '03242',
 'HILL, NH': '03243',
 'HILLSBOROUGH, NH': '03244',
 'HOLDERNESS, NH': '03245',
 'LACONIA, NH': '03247',
 'GILFORD, NH': '03249',
 'LINCOLN, NH': '03251',
 'LOCHMERE, NH': '03252',
 'MEREDITH, NH': '03253',
 'MOULTONBOROUGH, NH': '03254',
 'NEWBURY, NH': '03255',
 'NEW HAMPTON, NH': '03256',
 'NEW LONDON, NH': '03257',
 'CHICHESTER, NH': '03258',
 'NORTH SANDWICH, NH': '03259',
 'NORTH SUTTON, NH': '03260',
 'NORTHWOOD, NH': '03261',
 'NORTH WOODSTOCK, NH': '03262',
 'PITTSFIELD, NH': '03263',
 'PLYMOUTH, NH': '03264',
 'RUMNEY, NH': '03266',
 'SALISBURY, NH': '03268',
 'SANBORNTON, NH': '03269',
 'SOUTH NEWBURY, NH': '03272',
 'SOUTH SUTTON, NH': '03273',
 'SUNCOOK, NH': '03275',
 'TILTON, NH': '03299',
 'WARNER, NH': '03278',
 'WARREN, NH': '03279',
 'WASHINGTON, NH': '03280',
 'WEARE, NH': '03281',
 'WENTWORTH, NH': '03282',
 'SPRINGFIELD, NH': '03284',
 'THORNTON, NH': '03285',
 'WILMOT, NH': '03287',
 'WINNISQUAM, NH': '03289',
 'NOTTINGHAM, NH': '03290',
 'WEST NOTTINGHAM, NH': '03291',
 'WOODSTOCK, NH': '03293',
 'CONCORD, NH': '03305',
 'BOW, NH': '03304',
 'LOUDON, NH': '03307',
 'KEENE, NH': '03435',
 'ANTRIM, NH': '03440',
 'ASHUELOT, NH': '03441',
 'BENNINGTON, NH': '03442',
 'CHESTERFIELD, NH': '03443',
 'DUBLIN, NH': '03444',
 'SULLIVAN, NH': '03445',
 'SWANZEY, NH': '03446',
 'FITZWILLIAM, NH': '03447',
 'GILSUM, NH': '03448',
 'HANCOCK, NH': '03449',
 'HARRISVILLE, NH': '03450',
 'HINSDALE, NH': '03451',
 'JAFFREY, NH': '03452',
 'MARLBOROUGH, NH': '03455',
 'MARLOW, NH': '03456',
 'NELSON, NH': '03457',
 'PETERBOROUGH, NH': '03458',
 'RINDGE, NH': '03461',
 'SPOFFORD, NH': '03462',
 'STODDARD, NH': '03464',
 'TROY, NH': '03465',
 'WEST CHESTERFIELD, NH': '03466',
 'WESTMORELAND, NH': '03467',
 'WEST PETERBOROUGH, NH': '03468',
 'WEST SWANZEY, NH': '03469',
 'WINCHESTER, NH': '03470',
 'LITTLETON, NH': '03561',
 'BERLIN, NH': '03570',
 'BETHLEHEM, NH': '03574',
 'BRETTON WOODS, NH': '03575',
 'COLEBROOK, NH': '03576',
 'ERROL, NH': '03579',
 'FRANCONIA, NH': '03580',
 'GORHAM, NH': '03581',
 'GROVETON, NH': '03582',
 'JEFFERSON, NH': '03583',
 'LANCASTER, NH': '03584',
 'LISBON, NH': '03585',
 'SUGAR HILL, NH': '03586',
 'MILAN, NH': '03588',
 'MOUNT WASHINGTON, NH': '03589',
 'NORTH STRATFORD, NH': '03590',
 'PITTSBURG, NH': '03592',
 'RANDOLPH, NH': '03593',
 'TWIN MOUNTAIN, NH': '03595',
 'WEST STEWARTSTOWN, NH': '03597',
 'WHITEFIELD, NH': '03598',
 'ACWORTH, NH': '03601',

In [1858]:
US_addresses.loc[US_addresses.Zip.isnull(),'Zip'] = lookup_values_by_keys2(city_zip_dict,
                                                                           US_addresses.loc[US_addresses.Zip.isnull()],
                                                                           'City', keylen=False)

US_addresses.loc[US_addresses.Zip.isnull()]

,ClientID,Address,Zip,Country,City
283,US003046,DELAWARE USA,NaN,USA,DE
305,US003485,"57 SEAVIEW BOULEVARD PORT WASHINGTON,NY U.S.A.",NaN,USA,"PORT WASHINGTON,NY"
336,US002977,"NORTH CAROLINA, USA",NaN,USA,NC
613,US003269,TEXAS USA,NaN,USA,TX
665,US003143,"PLYMOUTH, MN USA",NaN,USA,"PLYMOUTH, MN"
974,US000050,"9000 CROW CANYON ROAD, SUITE S393, DANVILLE, C...",NaN,USA,DANVILLE CA
1071,US000147,IN. U.S.A.,NaN,USA,IN
1085,US000161,"INTERNATIONAL TOWER, SUITE 1760 S. FIGUEROA .,...",NaN,USA,"Los Angeles, CA"
1288,US000373,"DELAWARE, U.S.A.",NaN,USA,DE
1351,US000436,"810 VERMONT AVENUE N. W., WASHINGTON, D. C. 20...",NaN,USA,"Washington, DC"
1776,US000862,美国加州新港海滨詹伯瑞路4311号,NaN,USA,"NEW PORT, CA"
2365,US001463,美国 加州 佛利蒙 利马街51号,NaN,USA,"NEW PORT, CA"
2812,US001922,"330 BLAISDELL ROAD ORANGEBURG, NEW YORK 0962, ...",NaN,USA,"Orangeburg, NY"
2944,US002057,OFFICE OF TECHNOLOGY TRANSFER & ECONOMIC DEVEL...,NaN,USA,"Honolulu, HI"
2993,US002106,DELAWARE USA,NaN,USA,DE

In [1864]:
zipmap = {305:'11050',
          336:'94506',
           1085:'90012', 
           1776:np.nan, 
           2365:np.nan, 
           2812:'10962',
           2944:'96822'}

citymap = {305:'Port Washington, NY',
           336:'Danville, CA',
           974: 'Danville, CA',
           1085:'Los Angeles, CA',
           1776:'Newport Beach, CA',
           2365:'Fremont, CA',
           2812:'Orangeburg, NY',
           2944:'Honolulu, HI'}


US_addresses.loc[list(zipmap.keys()), 'Zip'] = (US_addresses.loc[list(zipmap.keys())].index
                                                      .to_series()
                                                      .map(zipmap))

US_addresses.loc[list(citymap.keys()), 'City'] = (US_addresses.loc[list(citymap.keys())].index
                                                      .to_series()
                                                      .map(citymap))

US_addresses.loc[US_addresses.Zip.isnull()]

,ClientID,Address,Zip,Country,City
283,US003046,DELAWARE USA,NaN,USA,DE
613,US003269,TEXAS USA,NaN,USA,TX
665,US003143,"PLYMOUTH, MN USA",NaN,USA,"PLYMOUTH, MN"
974,US000050,"9000 CROW CANYON ROAD, SUITE S393, DANVILLE, C...",NaN,USA,"Danville, CA"
1071,US000147,IN. U.S.A.,NaN,USA,IN
1288,US000373,"DELAWARE, U.S.A.",NaN,USA,DE
1351,US000436,"810 VERMONT AVENUE N. W., WASHINGTON, D. C. 20...",NaN,USA,"Washington, DC"
1776,US000862,美国加州新港海滨詹伯瑞路4311号,NaN,USA,"Newport Beach, CA"
2365,US001463,美国 加州 佛利蒙 利马街51号,NaN,USA,"Fremont, CA"
2993,US002106,DELAWARE USA,NaN,USA,DE

## `US_addresses` combined with client name and other info, export to excel

In [1874]:
final = pd.merge(left=US_addresses,
                 right=HQ_clients[['客户代码','客户名称','客户类别','客户中文名称', '电话','传真', '状态']] ,
                 left_on='ClientID',
                 right_on='客户代码')

final = final.drop('客户代码',axis=1)
print(final.shape[0])
final.head()

3622

,ClientID,Address,Zip,Country,City,客户名称,客户类别,客户中文名称,电话,传真,状态
0,US002562,"ONE BLOSSOM ROAD, ROCHESTER, NY 14610 USA",14610,USA,"Rochester, NY",CERION，LLC,(S),丝润有限责任公司,NaN,NaN,NaN
1,US002565,"600 NORTH BRAND BLVD., SUITE 230 GLENDALE, CA ...",91203,USA,"Glendale, CA","AD-VANTAGE NETWORKS, INC.",(S),AD-优势网络股份公司,NaN,NaN,NaN
2,US002566,C/O R.R. DONNELLEY & SONS COMPANY 111 SOUTH WA...,60606,USA,"Chicago, IL","TOPS Products, LLC",(S),托普斯产品有限责任公司,NaN,NaN,NaN
3,US002567,"430 CARMEL COURT CANTON, GEORGIA 30114 USA",30114,USA,"Canton, GA","BRIGHENTI, Peter",(S),彼得·布里根蒂,NaN,NaN,NaN
4,US002568,"200 SIDNEY STREET SUITE 310 CAMBRIDGE, MASSACH...",02139,USA,"Cambridge, MA","RANA THERAPEUTICS, INC.",(S),RANA医疗有限公司,NaN,NaN,NaN

In [1875]:
final.to_excel('Final US addresses.xlsx')

## PENDING

#### Revise `US_addresses` to include client name

#### Review the code using the following functions and revise to use `df.replace(dict)`
        - extract_match_from_a_patlist
        - extract_match_from_a_pat_df
        - extract_match_of_a_pat
        
#### Add other better tools to my personal notes, like `df.replace(dict)` to replace regex search in loop

#### Make a simplified version of this notebook for faster execution